### ISSUE TITLE
Q: Bold and/or Italic text within 'cell()' or 'multi_cell()'?

### ISSUE THREAD

**Issue by pwt** [PyFPDF/fpdf2#108]
First, a big thanks for all the work on this library. I'm already using it to produce professional-looking PDF documents efficiently.

Is it possible to produce inline **bold** and/or *italic* text when using `cell()` or `multi_cell()`? I note the discussion in #52, but I don't know how I'd use the HTML renderer to replace or augment what I'm currently doing with cell/multi_cell.

**Comment by Lucas-C** [comment]
Do you need to put **all** of the cell content in bold or italic?
If so, `set_font` will let you switch to bold/italic before rendering the cell.

Else, I'm afraid that currently `fpdf2` won't let you easily do what you want...

There is an example of table rendering with `write_html` there:
https://pyfpdf.github.io/fpdf2/Tables.html#using-write_html
However bold/inline styling inside HTML table cells won't work as expected.

I'll post some code here tomorrow displaying a potential workaround I have in mind.

**Comment by alexp1917** [comment]
@Lucas-C i think we might as well start supporting this, otherwise this is a bit ridiculous in my opinion, but the question is how to preserve apis, docs, backwards compatibility, etc...

```python
import os, fpdf


pdf = fpdf.FPDF()
pdf.add_page()
pdf.set_font('helvetica')

def write(self, txt):
    w = pdf.get_string_width(txt)
    pdf_cell(w, txt=txt)

pdf_cell = pdf.cell
pdf.cell = write

pdf.cell(0, txt='hello ')
pdf.set_font(style='B')
pdf.cell(0, txt='world')
pdf.set_font(style='')
pdf.cell(0, txt='!...')
pdf.output('output.pdf')
# os.system('evince output.pdf') # replace with your pdf program, this is ubuntu's

```

**Comment by Lucas-C** [comment]
There is a potential workaround:
```python
from fpdf import FPDF

DATA = (
    ("First name", "Last name", "Age", "City"),
    ("Lucas", "Cimon", "31", "Saint-        -sur-Loire"),
)
COL_WIDTHS = (.2, .2, .15, .45)

pdf = FPDF()
pdf.add_page()
pdf.set_font("Courier", size=10)         # this trick is easier with monospaced fonts
line_height = pdf.font_size * 2.5
for row in DATA:
    for i, datum in enumerate(row):
        col_width = COL_WIDTHS[i] * pdf.epw
        x, y = pdf.x, pdf.y
        pdf.multi_cell(col_width, line_height, datum, border=1, ln=3)
        if datum.endswith("sur-Loire"):  # performing a 2nd pass on the target cell
            text = "      Mathurin"      # part of cell context to put in bold, with padding matching the word horizontal position
            pdf.set_xy(x, y)             # positioning FPDF to re-draw the same cell
            pdf.set_font(style="BI")     # switching to bold italic
            pdf.multi_cell(col_width, line_height, text, border=1, ln=3)
            pdf.set_font(style="")       # switching back to regular
    pdf.ln(line_height)
pdf.output('issue_108.pdf')
```

**Comment by Lucas-C** [comment]
Now I agree that it'd be nice if `FPDF.cell` / `FPDF.multi_cell` / `FPDF.write` could support setting only part of text as bold / italic.

The question is: **what would be the best way to provide this feature to users**, while staying mostly backward-compatible & aiming at a clean library APi at the same time?

Maybe those 3 functions could support minimal [Markdown](https://en.wikipedia.org/wiki/Markdown#Example)-like markup?
Starting with just `**bold**` & `_italic_`, and enabling this behaviour only if `markdown=True` is passed to those 3 functions?

What do you think?
Would that suit your need @pwt?

**Comment by pwt** [comment]
Thanks for the responses, folks.

> What do you think?
> Would that suit your need @pwt?

Yes, I believe that would work well, althoughI think we'd need to enable escapes (`\**`, etc?) as part of this. Note that I've been tending to use `multi_cell()` rather than `cell()` in my applications.

**Comment by Lucas-C** [comment]
A PR implementing this is ready for reviewing: https://github.com/PyFPDF/fpdf2/pull/154

**Comment by MechMachOth** [comment]
I found a video on youtube where a guy uses a function to calculate the width of a word depending on the font applied, "https://www.youtube.com/watch?v=CozYzrz7f-k&ab_channel=ChartExplorers" , it works fine for one cell, but not for multi_cell. for my case I needed to put some words in bold in a regular multi_cell , so I started by setting up a regular myulti_cell and I redid another regular multi_cell with the same (x,y) replacing the words that I didn't want to bold with empty spaces and it worked perfectly (for bolded words only, for underlined and italic it doesn't work).

**Comment by Lucas-C** [comment]
@MechMachOth : note that in the latest versions of `fpdf2`, `multi_cell()` support supports `markdown=True` so that you can define bold text this way:

    text **between asterisks** is in bold

**Comment by MechMachOth** [comment]
@Lucas-C : Thank you, I spent two days looking for this ^^. I will redo with markdown it's better

**Comment by MechMachOth** [comment]
@lucas-C : but it only works for standard fonts, what if I use Calibri?

**Comment by Lucas-C** [comment]
As described in the documentation, you will need to use `add_font(..., style="B")`: https://pyfpdf.github.io/fpdf2/TextStyling.html#markdowntrue

Code example: https://github.com/PyFPDF/fpdf2/blob/master/test/text/test_cell.py#L155

**Comment by MechMachOth** [comment]
Merci @Lucas-C (y)
