### ISSUE TITLE
Parenthesis is not shown correctly in Justified mode if UNICODE font is used

### ISSUE THREAD

**Issue by mrkaragoz** [PyFPDF/fpdf2#122]
Open parenthesis '(' and close parenthesis ')' is not shown correctly in justified mode if UNICODE font is used. Parenthesis' were replaced with two squares which I believe are Japanese letters.

**Comment by Lucas-C** [comment]
Thank you for reporting this issue.

This is probably related to https://github.com/PyFPDF/fpdf2/issues/118

What version of `fpdf2` are you using?

**Comment by mrkaragoz** [comment]
Sorry for not adding version info beforehand. My "fpdf" version is 2.3.1.

Now, when I try with version 2.3.2 problem solved. Thank you for your quick reply.

**Comment by mrkaragoz** [comment]
My bad for not trying with the latest version :^)

**Comment by Lucas-C** [comment]
No worries 😉
