### ISSUE TITLE
Feature request: table of contents

### ISSUE THREAD

**Issue by alallier** [PyFPDF/fpdf2#124]
Anyway easy way to create a table of contents?

I see this [old class definition](https://github.com/reingart/pyfpdf/blob/master/attic/TOC.py) in the original project but that doesn't work

**Comment by Lucas-C** [comment]
`pyfpdf2` currently has no built-in way to generate a table of contents, but this would be a nice new feature for sure!

**Comment by alallier** [comment]
I have a solution where I loop over table of contents level items at the beginning and use the links to link later in the document. But it's impossible to list page numbers because you don't know the page number ahead of time (chicken and the egg type problem).

The solutions I've seen basically abstract away the add page function to keep track of page numbers within the program (like what I linked above)

**Comment by Lucas-C** [comment]
This would really be a great feature.

There are features of the PDF format that may be related to this and that we may want to support: Logical Structure & Bookmarks

**Comment by Lucas-C** [comment]
I have opened https://github.com/PyFPDF/fpdf2/pull/130 in order to implement the document outline & table of contents features.

**Comment by Lucas-C** [comment]
As indicated on #130, the PR is ready for review

**Comment by Lucas-C** [comment]
This has been released: https://github.com/PyFPDF/fpdf2/releases/tag/2.3.3

**Comment by alallier** [comment]
Wow you guys work so quick! I saw the traffic and didn't even get a chance to sit down before you released it!

Awesome work thank you!

**Comment by alallier** [comment]
(I think I can speak for many here but) it's so refreshing to see this type of interaction in open source community. Not something I'd normally do but if you have a link I'd love to (donate) buy you a beer/coffee for your quick work!

**Comment by Lucas-C** [comment]
Those are really kind words, thank you!

I don't ask for money for any of my open wource / libre software work,
but if you feel generous I have an [itch.io page](https://lucas-c.itch.io) where people can donate for the pen & paper games I create.
They're in French so that may not be of any use to you 😊
I also plan to release (on itch.io) a PDF video game made with `fpdf2`, hopefully tomorrow or Saturday.
