### ISSUE TITLE
write_html: proper handling of <img> inside <td>

### ISSUE THREAD

**Issue by Kewings** [PyFPDF/fpdf2#125]
i use jinja2 to render html code:
```
<table>
    <tr>
        <td width='100%' colspan="2">{{topic}}</td>
    </tr>
    <tr>
        <td width='50%'><img src='{{pic0}}' height='{{pic_height}}' width='{{pic_width}}'/></td>
        <td width='50%'><img src='{{pic1}}' height='{{pic_height}}' width='{{pic_width}}'/></td>
    </tr>
    <tr>
        <td width='100%' colspan="2">{{notes}}</td>
    </tr>
</table>
```
when i write_html, and pdf.output, it shows pictures not expected:
![image](https://user-images.githubusercontent.com/29881381/114368255-ce709980-9baf-11eb-8f0c-be6f38a52d0c.png)

does anyone have ideas?

**Comment by Lucas-C** [comment]
I @Kewings.

Sadly your code snippet is not enough to easily reproduce your problem...
We would need the Python code, images & version of `fpdf2` used in order to reproduce this issue.

You provided 2 screenshots and stated that it does not work "as expected".
But what did you expect precisely here?

In hope this could be useful for you to troubleshoot your issue, using the following Python code I get the output I expect:
```python
from fpdf import FPDF, HTMLMixin

class PDF(FPDF, HTMLMixin):
    pass

pdf = PDF()
pdf.add_page()
pdf.set_font("Helvetica", size=15)
pdf.write_html('''<table>
    <tr>
        <td width="100%" colspan="2">Some topic</td>
    </tr>
    <tr>
        <td width="50%"><img src="test/image/image_types/insert_images_insert_jpg.jpg" height="100" width="200"/></td>
        <td width="50%"><img src="test/image/image_types/insert_images_insert_png.png" height="100" width="200"/></td>
    </tr>
    <tr>
        <td width="100%" colspan="2">Bla bla bla</td>
    </tr>
</table>''')
pdf.output("repro.pdf")
```

The images used are hosted in this repository: https://github.com/PyFPDF/fpdf2/tree/master/test/image/image_types

**Comment by Kewings** [comment]
> I @Kewings.
> 
> Sadly your code snippet is not enough to easily reproduce your problem...
> We would need the Python code, images & version of `fpdf2` used in order to reproduce this issue.
> 
> You provided 2 screenshots and stated that it does not work "as expected".
> But what did you expect precisely here?
> 
> In hope this could be useful for you to troubleshoot your issue, using the following Python code I get the output I expect:
> 
> ```python
> from fpdf import FPDF, HTMLMixin
> 
> class PDF(FPDF, HTMLMixin):
>     pass
> 
> pdf = PDF()
> pdf.add_page()
> pdf.set_font("Helvetica", size=15)
> pdf.write_html('''<table>
>     <tr>
>         <td width="100%" colspan="2">Some topic</td>
>     </tr>
>     <tr>
>         <td width="50%"><img src="test/image/image_types/insert_images_insert_jpg.jpg" height="100" width="200"/></td>
>         <td width="50%"><img src="test/image/image_types/insert_images_insert_png.png" height="100" width="200"/></td>
>     </tr>
>     <tr>
>         <td width="100%" colspan="2">Bla bla bla</td>
>     </tr>
> </table>''')
> pdf.output("repro.pdf")
> ```
> 
> The images used are hosted in this repository: https://github.com/PyFPDF/fpdf2/tree/master/test/image/image_types

Hi Lucas-C,

thanks for your reply.
same html code as you writed, i got pdf like:
![image](https://user-images.githubusercontent.com/29881381/114510409-3afb9f00-9c69-11eb-9ca7-83cba482a16c.png)

and what i want is like :
![image](https://user-images.githubusercontent.com/29881381/114510627-74340f00-9c69-11eb-9b7c-d8b103c11171.png)

html code is:
```
<table>
    <tr>
        <td width="100%" colspan="2">Insert 2 Piture Parallel</td>
    </tr>
    <tr>
        <td width="50%"><img src="test/image/image_types/1.jpg" height="180" width="300"/></td>
        <td width="50%"><img src="test/image/image_types/2.png" height="180" width="300"/></td>
    </tr>
    <tr>
        <td width="100%" colspan="2">but picture shows serially</td>
    </tr>
    <tr>
        <td width='50%'>td1</td><td width='50%'>td2</td>
    </tr>
</table>
```

**Comment by Lucas-C** [comment]
OK, thanks for the extra explanations.

My understanding is that you want a side-by-side layout using HTML table cells.
Is that correct?

I think I see how to modify `HTML2FPDF` in `fpdf/html.py` in order for `<img>` tags inside `<td>` cells to be positioned correctly.
I'll report here soon if this works as I expect.

**Comment by Kewings** [comment]
yeah, many thanks.

**Comment by Kewings** [comment]
and maybe another issue used write_html can be fixed together?

**Comment by Lucas-C** [comment]
I opened https://github.com/PyFPDF/fpdf2/pull/126 to implement my fix.

Regarding your other issue, try passing `table_line_separators=True` to `FPDF.write_html`

**Comment by Lucas-C** [comment]
I have just merged #126.

@Kewings you can test the latest version this way:

    pip install git+https://github.com/PyPDF/fpdf2.git@master

If you can confirm that it solves your initial issue, I'll close this.

**Comment by Kewings** [comment]
> I opened #126 to implement my fix.
> 
> Regarding your other issue, try passing `table_line_separators=True` to `FPDF.write_html`

this issue is resolved, thanks.

**Comment by Kewings** [comment]
> I have just merged #126.
> 
> @Kewings you can test the latest version this way:
> 
> ```
> pip install git+https://github.com/PyPDF/fpdf2.git@master
> ```
> 
> If you can confirm that it solves your initial issue, I'll close this.

i firstly uninstalled fpdf2 in my compute, and i tried ```pip install git+https://github.com/PyFPDF/fpdf2.git@master```, then double checked fpdf2/html.py in github with my site_packages, and confirmed they are same.
but issue not resolved.
still get same page as:
![image](https://user-images.githubusercontent.com/29881381/114643848-063f2480-9d09-11eb-8997-cb7147e2986a.png)
code is:
```
<table>
    <tr>
        <td width='100%' colspan="2"><b>Insert 2 Piture Parallel</b></td>
    </tr>
    <tr>
        <td width='50%'><img src='D:\Code\1.png' height='200' width='200'/></td>
    </tr>
    <tr>
        <td width='50%'><img src='D:\Code\2.png' height='200' width='200'/></td>
    </tr>
    <tr>
        <td width='100%' colspan="2"><i>but picture shows serially</i></td>
    </tr>
</table>
```

**Comment by Lucas-C** [comment]
> version num in master is still 2.3.2

Yes, I'll wait for a few days before making a new release on Pypi. The version on the `master` will then be bumped.

> do you have idea to make the image in td centering?

No, and I may not have the time to look at this soon. But feel free to open another issue on this subject.

**Comment by Lucas-C** [comment]
For centering `<img>` in `<td>`, check out https://github.com/PyFPDF/fpdf2/pull/128
