### ISSUE TITLE
Reference manual docs not available

### ISSUE THREAD

**Issue by ralhei** [PyFPDF/fpdf2#138]
When going to the reference manual and then clicking e.g. on 'cell' (https://pyfpdf.github.io/fpdf2/reference/cell.html) this leads to a 404. Seems like some html files did not get uploaded properly.

**Comment by Lucas-C** [comment]
Thank you for reporting the issue!
I'll have a look at this very soon

**Comment by joncombe** [comment]
dashed_line, ellipse, image, line, link, ln, multi_cell, output, rect, set_font, set_left_margin, set_margins, set_right_margin, set_top_margin

**Comment by Lucas-C** [comment]
Fixed by https://github.com/PyFPDF/fpdf2/commit/5438a48

It was a dummy typo I made weeks ago...
Thank you both for reporting the issue!
