### ISSUE TITLE
image() with pillow.Image.Image creates fake duplicates

### ISSUE THREAD

**Issue by the-yrr** [PyFPDF/fpdf2#139]
The name of the image is used to check for duplicates

For pillow images this is str(name)  (the "name" variable is the image)
the image name will be something like:

<PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=2048x2803 at 0x1EA56628F40>

this identifier is not unique and created massive problems with random wrong images

I propose to change the code to something like this (works for me), maybe add a type check for pillow.Image.Image:
```python
        if isinstance(name, str):
            img = None
        elif isinstance(name, io.BytesIO):
            name, img = hashlib.md5(name.getvalue()).hexdigest(), name
        else:
            name, img = hashlib.md5(name.tobytes()).hexdigest(), name # new changed code
            #name, img = str(name), name # old code
            ### CHANGED NAME TO HASH ###
```

**Comment by Lucas-C** [comment]
This may be a duplicate of https://github.com/PyFPDF/fpdf2/issues/131

Could you provide the version of `fpdf2` you are using please?

**Comment by the-yrr** [comment]
I use version 2.3.3, just updated it 2 days ago.
the code snip is from the "image" function in the "fpdf.py" file, the block starts at line 1720 in my file.

it is not quite a duplicate of #131, the ByteIO was fixed, but not the pillow.Image.Image error I encountered (as can be seen in the code snip). The problem itself is the same though.


after reading the changelog:
I tried to add an image using a BytesIO object containing a webp image (undecoded data, not pixel data), which didn't work. I am not sure whether this is supposed to work or not.

**Comment by Lucas-C** [comment]
OK, thanks for the explanations.

There is the unit test validating that `BytesIO` are supported:
https://github.com/PyFPDF/fpdf2/blob/master/test/image/image_types/test_insert_images.py#L63

Could you provide some Python code reproducing your issue please?
How is your usage of `FPDF.image` different from this unit test?

**Comment by the-yrr** [comment]
this should give a pdf with images containing row + column position, e.g.
00, 01, 02, 03
10, 11, 12, 13
...

I added a pdf generated by the script. As you can easily see, it does not work after the first line

[duplicate.pdf](https://github.com/PyFPDF/fpdf2/files/6399006/duplicate.pdf)

```python
from PIL import Image, ImageDraw, ImageFont # pillow package
from fpdf import FPDF # fpdf2 package (needs pillow)


pdf = FPDF(orientation = "P", unit = "mm", format = "A4")
pdf.set_auto_page_break(auto = False) # , margin = 20 (specified unit, default 2cm)
pdf.set_margin(0)
pdf.add_page()

fnt = ImageFont.truetype("arial.ttf", 40)

for y in range(5):
  for x in range(4):
    im = Image.new(mode = "RGB", size = (100, 100), color = (60, 255, 10))
    draw = ImageDraw.Draw(im)
    draw.text((20,20), "{0}{1}".format(y,x), fill = (0,0,0), font=fnt)
    
    pdf.image(im, x = x*50+5, y = y*50+5, w = 45)

pdf.close()
pdf.output('duplicate.pdf')
```

**Comment by Lucas-C** [comment]
This was some excellent minimal code reproducing the issue!

This was fixed and released: https://github.com/PyFPDF/fpdf2/releases/tag/2.3.4

Thank you for reporting it 😉
