### ISSUE TITLE
Margins documentation is broken: https://pyfpdf.github.io/fpdf2/Margins.html

### ISSUE THREAD

**Issue by aquatic7** [PyFPDF/fpdf2#142]
A topic says, all links to the margins documentation is broken: https://pyfpdf.github.io/fpdf2/Margins.html

**Comment by Lucas-C** [comment]
What do you mean exactly by "broken"?

When I visit this documentation page, this is what I see:
![2021-05-03 22_53_36-Margins - fpdf2](https://user-images.githubusercontent.com/925560/116932413-826ebd00-ac62-11eb-92db-db32b43f7e70.png)

This was reently ( https://github.com/PyFPDF/fpdf2/issues/138 ) fixed, could it be a browser cache issue?
Could you try to `CTRL + SHIFT + R` and see if the problem persists?

**Comment by aquatic7** [comment]
I mean the links for:

    set_margin
    set_left_margin
    set_right_margin
    set_top_margin
    set_margins
    set_auto_page_break

https://pypi.org/project/fpdf2/fpdf/#fpdf.FPDF.set_margin
https://pypi.org/project/fpdf2/fpdf/#fpdf.FPDF.set_left_margin
https://pypi.org/project/fpdf2/fpdf/#fpdf.FPDF.set_right_margin
https://pypi.org/project/fpdf2/fpdf/#fpdf.FPDF.set_top_margin
https://pypi.org/project/fpdf2/fpdf/#fpdf.FPDF.set_margins
https://pypi.org/project/fpdf2/fpdf/#fpdf.FPDF.set_auto_page_break

![image](https://user-images.githubusercontent.com/18247537/116938955-0a50c900-ac5b-11eb-81c3-e8ecd520a066.png)

**Comment by Lucas-C** [comment]
Ok, got it, thank you!

This should be fixed now
