### ISSUE TITLE
issue regarding .txt to pdf

### ISSUE THREAD

**Issue by santhoshcameo** [PyFPDF/fpdf2#146]
Hi All, 

I could not find this in the documentation, how can I simply convert a .txt file to pdf by reading from a directory? the output should follow the same alignment of the .txt file, could someone help?

**Comment by Lucas-C** [comment]
This could be a starting point for you:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.set_font("Helvetica")
pdf.add_page()
with open("lorem-ipsum.txt") as text_file:
    pdf.multi_cell(pdf.epw, 8, text_file.read())
pdf.output("output.pdf")
```
[lorem-ipsum.txt](https://github.com/PyFPDF/fpdf2/files/6511290/lorem-ipsum.txt)

**Comment by santhoshcameo** [comment]
thank you Lucas, I will definitely try this.

**Comment by Lucas-C** [comment]
Great!
I'm closing this issue now then.
