### ISSUE TITLE
Support justified HTML paragraphs

### ISSUE THREAD

**Issue by boghison** [PyFPDF/fpdf2#149]
It is not currently possible to use `<p align="justify">text</p>` with `write_html`. I suspect it is because paragraphs are created using `cell` instead of `multi_cell`. However, the documentation does not explicitly mention which values for the `align` attribute are valid.

**Comment by Lucas-C** [comment]
Thanks for the report!

I opened https://github.com/PyFPDF/fpdf2/pull/150 to suggest a fix
