### ISSUE TITLE
Unicode font usage still calls into the util string functions

### ISSUE THREAD

**Issue by alexanderankin** [PyFPDF/fpdf2#15]
some code still reaches the util string functions with a buffer:

```python
def escape(s):
    "Add \ before \, ( and )"
    return s.replace('\\', '\\\\') \
            .replace(')', '\\)') \
            .replace('(', '\\(') \
            .replace('\r', '\\r')
```

this is obviously bad and is why i had to yank the `2.1.0`.

**Comment by Lucas-C** [comment]
Bad news :(
What are the consequences ? Do you have a test case where this cause a bug ?

**Comment by alexanderankin** [comment]
I think its just any unicode font, that whole section of code is lacking code coverage

**Comment by alexanderankin** [comment]
<details>
<summary>here's what im working with to run the code</summary>

```python
import unittest
import sys
import os
from . import get_ttf_basic

sys.path.insert(0,
  os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    os.path.join('..', '..')
  )
)

import fpdf
import test
from test.utilities import relative_path_to, \
                           set_doc_date_0, \
                           calculate_hash_of_file

# python -m unittest test.fonts.issue_15.Issue15
# python3 -m unittest test.fonts.issue_15.Issue15

class Issue15(unittest.TestCase):
  def test_issue_15(self):

    basic_ttfs = get_ttf_basic()
    basic_ttf = basic_ttfs[4]
    print(basic_ttf) # /path to ttf file

    example_name_ac = 'HELLO WORLD'
    example_name_example = example_name_ac
    pdf = fpdf.FPDF('L', 'pt', 'A4')
    pdf.add_font('Some Font', '', basic_ttf, uni=True)
    pdf.add_font('Some Font', 'B', basic_ttf, uni=True)

    pdf.add_page()
    # pdf.image(example_background, x=0, y=0, h=200, w=200)
    pdf.ln(10)
    pdf.set_font('Some Font', 'B', 45)
    pdf.cell(100, 47, example_name_example, ln=2, align="C")

    outfile = relative_path_to('line_output1.pdf')
    pdf.output(outfile)
    # print(calculate_hash_of_file(outfile)) # is the output changing
    # self.assertEqual(known_good_hash, calculate_hash_of_file(outfile))
    os.system('evince ' + outfile)
    os.unlink(outfile)


if __name__ == '__main__':
  unittest.main()

## Development of demo mostly done as written above.
    # self.assertEqual(known_good_hash, calculate_hash_of_file(outfile))
    # os.unlink(outfile)
```

</details>

**Comment by alexanderankin** [comment]
by the way, im running this test with `python3 -m unittest test.fonts.issue_15.Issue15` and `python3 -m unittest test.image.image_types.insert_images.InsertImagesTest.test_insert_jpg` breaks for some reason, even though the image is loaded the hash changed (png, bmp, and gif are still the same). my work is on the `15_utils_handle_str_bytes` [branch][1]

[1]: https://github.com/alexanderankin/pyfpdf/tree/15_utils_handle_str_bytes

**Comment by alexanderankin** [comment]
ok so the tests pass, im not exactly sure thats everything. other than that its ready for pr/merging.

I had to remove the import in `test/__init__.py` so that means that partially running the test suite doesn't work (or was that only on python 2? i started out today double checking everything for python 2 out of habit).

**Comment by alexanderankin** [comment]
Ok, the person who reported the problem has tried out the new code, so i am going to publish the changes from the 15_utils... branch as the next patch version, which would be 2.1.1

**Comment by Lucas-C** [comment]
Great! :)

**Comment by Lucas-C** [comment]
What's the status on this?
Will it be closed by https://github.com/alexanderankin/pyfpdf/pull/26 ?

**Comment by alexanderankin** [comment]
oh this should be closed I think, I just don't recall which commit fixed it...

**Comment by Lucas-C** [comment]
I don't think you merged your branch though: https://github.com/alexanderankin/pyfpdf/tree/15_utils_handle_str_bytes

**Comment by Lucas-C** [comment]
Maybe a new Pypi release could be nice once you'll have merged or closed this?
-> https://pypi.org/project/fpdf2/#history

**Comment by Lucas-C** [comment]
Closing this now that v2.2.0 has been released: https://pypi.org/project/fpdf2/
