### ISSUE TITLE
write_html won't accept bold text

### ISSUE THREAD

**Issue by keremnymn** [PyFPDF/fpdf2#156]
I load the fonts this way:

`pdf.add_font('ArialUnicode',fname='/content/arial.ttf',uni=True)`

Also the bold font:

`pdf.add_font('ArialUnicodeB',fname='/content/arialbld.ttf',uni=True)`

But when I try to render an HTML with <b> tag, this exception raises:

`FPDFException: Undefined font: arialunicodeB - Use built-in fonts or FPDF.add_font() beforehand`

Is this is a known bug?

**Comment by Lucas-C** [comment]
You just need to load the font this way:
```python
pdf.add_font('ArialUnicode', style='B', fname='/content/arialbld.ttf', uni=True)
```

Keywords are even optional if you pass the parameters in the correct order:

```python
pdf.add_font('ArialUnicode', 'B', '/content/arialbld.ttf', True)
```

**Comment by keremnymn** [comment]
Unfortunately, same error again :/

Loading fonts:
```
pdf.add_font('ArialUnicode', '', '/content/arial.ttf', True)
pdf.add_font('ArialUnicode', 'B', '/content/arialbld.ttf', True)
```

Exception:

`FPDFException: Undefined font: arialunicodeb - Use built-in fonts or FPDF.add_font() beforehand`

Full log:

![Ekran Alıntısı](https://user-images.githubusercontent.com/59928017/120929968-e8cc7c80-c6f3-11eb-84eb-25acee78c4b7.JPG)

**Comment by Lucas-C** [comment]
This is indeed a bug. Thanks for reporting it!

I opened https://github.com/PyFPDF/fpdf2/pull/157 to fix this.
