### ISSUE TITLE
Function set_image_filter not in library but shows in docs

### ISSUE THREAD

**Issue by mat100payette** [PyFPDF/fpdf2#159]
The [docs ](https://pyfpdf.github.io/fpdf2/Images.html) for image manipulation show the following snippet:

```py
from fpdf import FPDF

pdf = FPDF()
pdf.set_image_filter("DCTDecode")
pdf.add_page()
pdf.image("docs/fpdf2-logo.png", x=20, y=60)
pdf.output("pdf-with-image.pdf")
```

However I can't find `set_image_filter` anywhere. Is this outdated ?

**Comment by Lucas-C** [comment]
No, this just has just not been released yet:
https://github.com/PyFPDF/fpdf2/blob/master/CHANGELOG.md#240---not-released-yet

I'm planning a new released by the end of the week.

**Comment by Lucas-C** [comment]
Note that, in the meantime, you can test the latest version this way:

    pip install git+https://github.com/PyPDF/fpdf2.git@master

**Comment by Lucas-C** [comment]
I'm waiting for the last open PR to be finished.

Note that this synta does **not** require authentication credentials, only a `git` client.
