### ISSUE TITLE
Image takes incredible amount of disk space

### ISSUE THREAD

**Issue by mat100payette** [PyFPDF/fpdf2#160]
I'm using images about 800KB in size, yet the resulting pdf is a massive 12MB! When I simply remove the image call, I effectively get a PDF that is under 1MB. Clearly something isn't ok there?

```py
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.image("my_image.jpg", x=0, y=0)
pdf.output("massive.pdf")
```

**Comment by mat100payette** [comment]
Here's some more context:

```py
with BytesIO() as final_image_bytes:

    in_image.save(final_image_bytes, format = 'jpeg', optimize = True, quality = 85)
    print(f'Image size: {final_image_bytes.tell()}')
    
    pdf.image(final_image_bytes, w = pdf.epw, h = pdf.eph)
```

The print says `1380050` bytes, so 1.3MB. The total PDF size after the `pdf.image` call skyrockets to 15MB. That's unacceptable for our clients.

**Comment by Lucas-C** [comment]
This should improve a lot in next release, thanks to the newly supported DCTDecode image filter for JPEG images:
https://github.com/PyFPDF/fpdf2/blob/master/CHANGELOG.md#240---not-released-yet

**Comment by mat100payette** [comment]
What a coincidence! Cant wait to see it in action; that should drastically improve our infrastructure's performance.

**Comment by Lucas-C** [comment]
A `v2.4.0` has just been released!

Does it improves your situation ?
If so, feel free to close this issue

**Comment by mat100payette** [comment]
@Lucas-C The parameter of `set_image_filter` says:
> image_filter (str): name of a support image filter or "AUTO", meaning to use the best image filter given the images provided.
What is meant here by "best image filter" ? Is it optimizing file size ? Is it doing some tradeoff between quality and size ?

**Comment by Lucas-C** [comment]
Currently, we simply use `DCTDEcode` if the image is already JPEG-compressed, otherwise the image is not compressed and the whole pixels array is stored (`FlateDecode`)
