### ISSUE TITLE
Template only allows for Interleaved 2 of 5 Barcode

### ISSUE THREAD

**Issue by davidcrab** [PyFPDF/fpdf2#161]
It seems like there is no way to use a template to create a Code 39 Barcode since this if statement is only looking for a Interleaved 2 of 5 Barcode. Am I missing something or should this be a simple addition to make it possible to use Code 39 with templates?

https://github.com/PyFPDF/fpdf2/blob/e00a49b81dd2569df3c82b34f453628a78fc4156/fpdf/template.py#L298

**Comment by Lucas-C** [comment]
The `Template` utility class is definitively not the component of `fpdf2` that received most love,
and it is sometimes a bit messy in terms of API & features support.

I opened https://github.com/PyFPDF/fpdf2/pull/163 to add support for Code 39 barcodes though.
