### ISSUE TITLE
New update (2.4.0) introduces a tiny bit of jank

### ISSUE THREAD

**Issue by mat100payette** [PyFPDF/fpdf2#166]
I have now updated to 2.4.0, and the file size is drastically improved so that's amazing. However, there's some slight jank here and there. Here's 2 things I noticed after simply updating and adding `set_image_filter('AUTO')` to my code:

1. Images became 1 pixel/unit too tall, I had to change `h = something` to `h = something - 1` otherwise the images would be moved on a new page.
2. Some symbols in my font became unsupported (?). I have a – in my code, and now it displays as a rectangle (▯) in Adobe Acrobat Reader, which is didn't prior to the update.

**Comment by Lucas-C** [comment]
Thanks for reporting those issues.

Could you please provide some Python code reproducing them in order to help finding a solution?

I'll have a look at it on my side, but without knowing what images / font files / code you are using,
I may not be able to reproduce the problems you mention

**Comment by Lucas-C** [comment]
Also, `set_image_filter('AUTO')` is unnecessary as it is now the default value:
https://github.com/PyFPDF/fpdf2/blob/2.4.0/fpdf/fpdf.py#L238

**Comment by Lucas-C** [comment]
I found a unit test reproducing your 1st issue, I'm working on it

**Comment by Lucas-C** [comment]
Could you confirm that those issues are fixed for you with the new release `v2.4.1`?

**Comment by mat100payette** [comment]
I confirm that both issues are fixed in 2.4.1.
