### ISSUE TITLE
How to add Border on page ?

### ISSUE THREAD

**Issue by Mubeen-hub** [PyFPDF/fpdf2#17]
I want to add border in each page (individual or all at once).
Image is attached for better understanding.
![image](https://user-images.githubusercontent.com/56192593/103090518-078df980-4613-11eb-96b9-db7a4dca3a22.png)

**Comment by Lucas-C** [comment]
Try this:
```python
from fpdf import FPDF
pdf = FPDF()
pdf.add_page()
pdf.rect(x=10, y=10, w=190, h=280)
pdf.rect(x=15, y=15, w=180, h=270)
pdf.output('demo.pdf')
```

Does this code snippet answers your question?

**Comment by Lucas-C** [comment]
Closing as an example as been been provided.
