### ISSUE TITLE
multi_cell returns wrong google map search link

### ISSUE THREAD

**Issue by WalidGharianiEAGLE** [PyFPDF/fpdf2#170]
Im having an issue when the content contain a google map search links. When opening the link through the generated pdf, I get directed with the wrong link. Here is an example to replicate
Version: 2.4.1

```py
# test the link
link  = "http://maps.google.com/maps?z=15&t=m&q=34.05223,-118.24368"
print(link)

from fpdf import FPDF

data = (
    ("First name", "Last name", "Age", "City"),
    ("Jules", "Smith", "34", "San Juan"),
    ("Mary", "Ramos", "45", "Orlando"),
    ("Carlson", "Banks", "19", f"{link}"),
    ("Lucas", "Cimon", "31", "Saint-Mahturin-sur-Loire"),
)

pdf = FPDF()
pdf.add_page()
pdf.set_font("Times", size=10)
line_height = pdf.font_size * 2.5
col_width = pdf.epw / 4  # distribute content evenly
for row in data:
    for datum in row:
        pdf.multi_cell(col_width, line_height, datum, border=1, ln=3, max_line_height=pdf.font_size)
    pdf.ln(line_height)
pdf.output('table_with_link.pdf')
```

**Comment by Lucas-C** [comment]
Hi @WalidGharianiEAGLE !

There are two things happening here:

* because you used `pdf.multi_cell`, the URL is broken into several lines in the cell

* a link is not added automatically, but some PDF readers will still detect that the first line of the cell starts with `http://` and allows the user to open it in a web browser.

One simple workaround here is to explicitely set a link on the target cell.
Here is a way to dot it:
```python
for row in data:
    for datum in row:
        url = link if datum == link else None
        pdf.multi_cell(col_width, line_height, datum, border=1, ln=3, max_line_height=pdf.font_size, link=url)
    pdf.ln(line_height)
```

**Comment by Lucas-C** [comment]
Does this solve your issue?

**Comment by WalidGharianiEAGLE** [comment]
@Lucas-C Thank you for the feedback and the explanation. I used a simple example where I added that link in purpose but yes your code solved that. In my case I have several different links withing a column. I tried to iterate over the list of links, but the output was not what I expected in terms of the length of the table and the links to be shown when opened. 

```py
from fpdf import FPDF

link1  = "http://maps.google.com/maps?z=15&t=m&q=34.05223,-118.24368"
link2 = "http://maps.google.com/maps?z=15&t=m&q=35.05223,-118.24368"
list_links = [link1,link2]

data = (
    ("First name", "Last name", "Age", "City"),
    ("Jules", "Smith", "34", "San Juan"),
    ("Mary", "Ramos", "45", "Orlando"),
    ("Carlson", "Banks", "19", f"{link1}"),
    ("Lucas", "Cimon", "31", f"{link2}"),
)

pdf = FPDF()
pdf.add_page()
pdf.set_font("Times", size=10)
line_height = pdf.font_size * 2.5
col_width = pdf.epw / 4 
for link in list_links : 
    for row in data:
        for datum in row:        
            url = link if datum == link else None
            pdf.multi_cell(col_width, line_height, datum, border=1, ln=3, max_line_height=pdf.font_size, link=url)
        pdf.ln(line_height)

pdf.output('table_with_links2.pdf')
```

**Comment by WalidGharianiEAGLE** [comment]
I ended up using the following:
```py
no_link_rows = [tup for tup in data if not any(i in tup for i in list_links)]
for row in no_link_rows:
    for datum in row:
        pdf.multi_cell(col_width, line_height, datum, border=1, ln=3, max_line_height=pdf.font_size, align='C')
    pdf.ln(line_height)
for url in list_links:
    link_row = list(filter(lambda x:url in  x, data))
    for row in link_row:
        for datum in row:
            pdf.multi_cell(col_width, line_height, datum, border=1, ln=3, max_line_height=pdf.font_size, link = url, align='C')
        pdf.ln(line_height)

```
This solved the issue for this particular case with `list_links`. But i think if the str of the data is as follow
```py
data = (
    ("First name", "Last name", "Age", "City"),
    ("Jules", "Smith", "34", "San Juan"),
    ("Mary", "Ramos", "45", f"{link1}"),
    ("Carlson", "Banks", "19", "Los Angeles"),
    ("Lucas", "Cimon", "31", f"{link2}"),
)
```
The distribution of the data in this case withing the table will not be as expected 
or lets say there are many other links in different columns, The solution will not likely to solve the link issue.

**Comment by Lucas-C** [comment]
Glad you found a solution to your issue!

This may be an alternate solution:
```python
for link in list_links : 
    for row in data:
        for datum in row:        
            url = link if datum.startswith("http") else None
            pdf.multi_cell(col_width, line_height, datum, border=1, ln=3, max_line_height=pdf.font_size, link=url)
        pdf.ln(line_height)
```

**Comment by Lucas-C** [comment]
If you are happy a solution shared in this thread, can this issue be closed?

**Comment by WalidGharianiEAGLE** [comment]
Thank you for the suggestion, but the alternative solution you provided didn't actually solve it. It rewrites the table twice. For my side I believe that the issue could be closed since i found a working solution, although it might be revisited in the future if the links are distributed in different columns.
