### ISSUE TITLE
Optional markdown support is missing in the 'multi_cell()' and 'write()' methods

### ISSUE THREAD

**Issue by pwt** [PyFPDF/fpdf2#171]
Support for an optional `markdown` parameter was meant to have been added to the `cell()`, `multi_cell()` and `write()` methods (issue #108, PR #154), to allow rendering of inline bold, italic (etc.) text within a cell.

Support for the `markdown` parameter is present in the `cell()` method, but is missing from the `multi_cell()` and `write()` methods in FPDF2 v2.4.1.

Support **is** present in commit 508f39da36edc479538488657ff1c586d5f6f8ac, which is meant to be part of merged PR #154, but somehow this hasn't made it into the release.

**Comment by Lucas-C** [comment]
Thanks for opening this PR to keep track of this.

As mentioned in comment https://github.com/PyFPDF/fpdf2/issues/108#issuecomment-853628742
adding support for pseudo-Markdown styling in `multi_cell()` & `write()` will require some extra work.

I have written some unit tests but I may not have the time to implement this soon.

Pull requests are very welcome!

**Comment by pwt** [comment]
Apologies, @Lucas-C -- I'd missed that comment.

(I will take a look to see if I could help with the implementation, but I suspect there'll be too much of an FPDF learning curve for me to contribute efficiently.)

**Comment by Lucas-C** [comment]
There are some unit tests to get started:

[test_multi_cell_markdown.py.txt](https://github.com/PyFPDF/fpdf2/files/6700568/test_multi_cell_markdown.py.txt)

**Comment by YeshiNamkhai** [comment]
Hi Lucas-C,
it would great to have it for multi_cell() considering also the template feature, say I may add 'markdown':True to the type TEXT and get the multiline formatted with bold, underline and italics.
Thanks

**Comment by Lucas-C** [comment]
Agreed @YeshiNamkhai !

I probably won't tackle this one myself in the near future.
Like most [FLOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software) projects, `fpdf2` is based on volunteer work.
I you really would like this feature, please consider submitting a PR ! 😉

**Comment by YeshiNamkhai** [comment]
Well,  I have no time to get it work in the last release, but adding few lines already does the job.

    @check_page
    def multi_cell(
        self,
        w,
        h=None,
        txt="",
        border=0,
        align="J",
        fill=False,
        split_only=False,
        link="",
        ln=0,
        max_line_height=None,
        #add this:
        markdown=False,
    ):

then inside the function add  markdown=True

            # Explicit line break
            if c == "\n":
                if self.ws > 0:
                    self.ws = 0
                    self._out("0 Tw")

                if max_line_height and h > max_line_height:
                    height = max_line_height
                    h -= height
                else:
                    height = h
                new_page = self.cell(
                    w,
                    h=height,
                    txt=substr(s, j, i - j),
                    border=b,
                    ln=2,
                    align=align,
                    fill=fill,
                    link=link,
                    #add this:
                    markdown=True,
                )
                page_break_triggered = page_break_triggered or new_page
                text_cells.append(substr(s, j, i - j))

for every call of self.cell

**Comment by Lucas-C** [comment]
I am very surprised that it is actually as easy to implement 😲

When I worked on adding pseudo-Markdown support for `FPDF.cell`, I expected more complications with `multi_cell` due to the line breaks.

Anyway, I added your suggestion, thank you @YeshiNamkhai !
https://github.com/PyFPDF/fpdf2/blob/master/CHANGELOG.md#added
