### ISSUE TITLE
Feature Request: Allow "FPDF.add_font" to accept a bytes/buffer object

### ISSUE THREAD

**Issue by EmperorArthur** [PyFPDF/fpdf2#172]
Hello,

This is more of a nice to have than anything, but in playing around, I found [this `pymupdf-fonts`](https://pypi.org/project/pymupdf-fonts/)convenient package. and thought it would be great if it could be loaded into the code without an extra step.

In addition, accepting bytes or buffers would allow for use with setuptools [Resource Manager API](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#resourcemanager-api) when using this as part of a larger project.

**Comment by Lucas-C** [comment]
Interesting!

I'll try to check out soon how `fpdf2` could work along this [pymupdf-fonts](https://github.com/pymupdf/pymupdf-fonts) library

**Comment by Lucas-C** [comment]
Just a quick heads-up: I haven't been able to install `pymupdf` on my laptop (the required steps are [a bit convoluted](https://github.com/pymupdf/PyMuPDF/issues/358#issuecomment-529868242)) so I haven't been able to progress on this subject yet.

Anyone is very welcome to have a look a it!

**Comment by EmperorArthur** [comment]
Oh, I didn't bother with that.  I just installed the fonts package.  https://pypi.org/project/pymupdf-fonts/

I believe they're ignoring the whole api I was talking about and just base64 encoding the data.

**Comment by Lucas-C** [comment]
Alright, but the code to parse & load those font buffers are defined in MuPDF:
https://github.com/kobolabs/mupdf/blob/master/include/mupdf/fitz/font.h#L81

Without PyMuPDF, it will be difficult to extract those fonts...

**Comment by Lucas-C** [comment]
On a related note, we plan to move to `fonttools`: https://github.com/PyFPDF/fpdf2/issues/418

I'm not sure this will solve this initial request here, but I'm going to close this issue for now
