### ISSUE TITLE
How to repeat table headers across all the PDF pages in document

### ISSUE THREAD

**Issue by korniichuk** [PyFPDF/fpdf2#173]
Hi fpdf2 community,

first of all thank you very much for the great work (maintenance, documentation, and many more).
I am looking for an option to **repeat table header** for long tables (2+ pages).
Many thanks for your help.

Example visualization of my question: https://www.extendoffice.com/documents/word/5433-word-table-header-repeat.html

**Comment by Lucas-C** [comment]
I opened a PR to document a recipe that performs what you want:
https://github.com/PyFPDF/fpdf2/pull/176

Does that provide the functionality you need @korniichuk ?

Alternatively, you can implement your own `table()` method.
There is an example crafted by another fpdf2 user:
* video: https://www.youtube.com/watch?v=euNvxWaRQMY
* code: https://github.com/bvalgard/create-pdf-with-python-fpdf2/blob/main/create_table_fpdf2.py

**Comment by korniichuk** [comment]
@Lucas-C `will_page_break` method looks great! Thank you very much for your help. We can close the issue now.

**Comment by Lucas-C** [comment]
Great!
It may not be released before a few weeks,
but in the meantime you can replace this call by this simple check:
`pdf.y + cell_height > pdf.page_break_trigger`
