### ISSUE TITLE
Bug: Templates do not work with images

### ISSUE THREAD

**Issue by EmperorArthur** [PyFPDF/fpdf2#175]
When attempting to use templates to arrange QR codes, I found that it produces an error.

The error may occur in the render call, but the issue is with the assignment.  The fact the data is stored in `pdf.texts` gives a hint to the problem, which is `Template.__setitem__` always calls `str(value)`.

Example Code:
```python
import qrcode
from fpdf import Template
barcode_page_elements = [
            {
                "name": "barcode_0",
                "type": "I",
                "x1": 50,
                "y1": 50,
                "x2": 100,
                "y2": 100,
                "priority": 0,
                "text": None,
            },
            {
                "name": "barcode_1",
                "type": "I",
                "x1": 150,
                "y1": 150,
                "x2": 200,
                "y2": 200,
                "priority": 0,
                "text": None,
            }
]
pdf = Template(format="letter", elements=barcode_page_elements)
pdf.add_page()
pdf["barcode_0"] = qrcode.make("Test 0").get_image()
pdf["barcode_1"] = qrcode.make("Test 1").get_image()
pdf.render("out.txt")
```

**Comment by EmperorArthur** [comment]
Note: Given how multi-page works with templates, I would suggest considering marking `__setitem__` as deprecated, and adjusting the instructions/examples to directly set the appropriate page within `pdf.texts`.

**Comment by Lucas-C** [comment]
I have just submitted https://github.com/PyFPDF/fpdf2/pull/177 to solve this issue
