### ISSUE TITLE
Feature Request: set_link x arg

### ISSUE THREAD

**Issue by mrEscen** [PyFPDF/fpdf2#178]
Hello,

Currently consider fpdf2 best pdf creator for my needs and plan to use it for generating technical drawing packages.
Each technical page is a high res image with a device rectangle on top with additional data. 
Those package contains a large amount of pages with hundreds of devices, an fast and easy navigation is therefor crucial.

Is it possible to add a 'x' argument to set_link?
That makes it possible, combined with zoom, to jump and focus on an specific part of a page, in my case containing a device but I can come up with more use cases.

**Comment by Lucas-C** [comment]
Good idea, and this actually easy to implement!

I opened PR https://github.com/PyFPDF/fpdf2/pull/179 to support this
