### ISSUE TITLE
Thai text not rendered correctly

### ISSUE THREAD

**Issue by bnyw** [PyFPDF/fpdf2#184]
I've found that Thai text not rendered correctly in [unicode.pdf](https://github.com/reingart/pyfpdf/raw/master/tutorial/unicode.pdf)
from this code [Example](https://pyfpdf.github.io/fpdf2/Unicode.html#:~:text=parameter%20of%20add_font.-,Example,-This%20example%20uses)
I also ran the example code myself and the result is the same.
It should be "สวัสดีชาวโลก" in a single line.

**Comment by Lucas-C** [comment]
Thank you for reporting the issue!

What font are you using?
Could you provide some minimal Python code reproducing the problem please?

**Comment by Lucas-C** [comment]
@all-contributors please add @bnyw for bug

**Comment by bnyw** [comment]
I use the font shown in this [Example](https://pyfpdf.github.io/fpdf2/Unicode.html#:~:text=parameter%20of%20add_font.-,Example,-This%20example%20uses), you can download the font [here](https://github.com/bnyw/bnyw/blob/main/Waree.ttf)

this is the code you can use to recreate this issue
```
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.add_font("waree", fname="Waree.ttf", uni=True)
pdf.set_font("waree")
pdf.write(txt="สวัสดีชาวโลก ทดสอบฟอนต์, Hello world font test.")
pdf.output("style.pdf")
```
I've tried some more fonts and the results are still the same.

**Comment by Lucas-C** [comment]
Thanks to @moe-25, there is an upcoming PR adding support for unicode charcters above 0xFFFF: https://github.com/PyFPDF/fpdf2/pull/183

@bnyw, could you please check if your issue is solved when using the version from this branch?

    pip install git+https://github.com/moe-25/fpdf2.git@feature_emoticons

**Comment by bnyw** [comment]
@Lucas-C It gave me this error 
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 4457: character maps to <undefined>`.

**Comment by Lucas-C** [comment]
Interesting... There seems to be an issue with the `README.md` or `setup.py` file...
I'll look into it ASAP

**Comment by moe-25** [comment]
I guess PR #183 won't solve the problem. The cause seems to be that character \u0E31 has a width of 65535 which is so wide that a line break is forced.

@bnyw: Could you please try the following hack and check if the result looks satisfying?
```
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.add_font("waree", fname="Waree.ttf", uni=True)
pdf.set_font("waree")
pdf.current_font["cw"] = [0 if x == 65535 else x for x in pdf.current_font["cw"]]
pdf.write(txt="สวัสดีชาวโลก ทดสอบฟอนต์, Hello world font test.")
pdf.output("style.pdf")
```

**Comment by bnyw** [comment]
@moe-25 I've tested it and it's kind of work the result still has space after those characters which it shouldn't have.
![184_2](https://user-images.githubusercontent.com/32655514/125604730-a96b52ec-9f77-4354-a912-edbe8dde8eb0.png)

I tried change character width to 1 and it's working!
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.add_font("waree", fname="Waree.ttf", uni=True)
pdf.set_font("waree")
pdf.current_font["cw"] = [1 if x == 65535 else x for x in pdf.current_font["cw"]]
pdf.write(txt="สวัสดีชาวโลก ทดสอบฟอนต์, Hello world font test.")
pdf.output("style.pdf")
```
![184_3](https://user-images.githubusercontent.com/32655514/125605015-d84b81d7-d9c2-4bf7-87a8-8cdd597f04a6.png)

**Comment by Lucas-C** [comment]
I did not manage to reproduce your `UnicodeDecodeError` exception using the [code snippet you provided @bnyw ](https://github.com/PyFPDF/fpdf2/issues/184#issuecomment-876556198)

But glad to see you found a solution using @moe-25 hack! 💖

Do you see how this could be properly handled by `fpdf2`?

**Comment by Lucas-C** [comment]
I opened https://github.com/PyFPDF/fpdf2/pull/191 to properly fix this

The resulting PDF is slightly different, as it seems to introduce extra whitespaces:
https://github.com/PyFPDF/fpdf2/blob/issue_184/test/fonts/thai_text.pdf

What do you think @bnyw : are those whitespaces normal for that font / language, or they shouldn't appear?

@moe-25 : would you be kind enough to review this PR please?

**Comment by Lucas-C** [comment]
This has just been released in fpdf2.4.3
