### ISSUE TITLE
Rotated text cells

### ISSUE THREAD

**Issue by arefmalek** [PyFPDF/fpdf2#190]
Hi everyone, this is my first time opening an issue, so I apologize if I miss something. 

I am looking to rotate text in multi-cells at an arbitrary angle, similar to [this issue](https://github.com/reingart/pyfpdf/issues/103) in the original FPDF repo and [this post](https://stackoverflow.com/questions/50306870/place-a-vertical-or-rotated-text-in-a-pdf-with-python) on SO. I tried using the `rotation` [function](https://pyfpdf.github.io/fpdf2/fpdf/#fpdf.FPDF.rotation) in an example I'll include below, but I didn't get the "hello" rotated at a 30 degree angle that I was anticipating. 

Is there any way to currently do this? If there is, knowing how to do it would be very helpful :) thanks!

### Example code 
```
pdf = FPDF()

pdf.add_page()
pdf.set_font('helvetica', 'B', 16)
pdf.rotation(angle=30)
pdf.text(50, 50, "Hello!")
pdf.output('tuto1.pdf')
```

**Comment by Lucas-C** [comment]
Hi @arefmalek !

Questions are very welcome, and yours is really clear, with even some code to illustrate it: great!

You'll find some usage examples of using `FPDF.rotation` here:
https://github.com/PyFPDF/fpdf2/blob/master/test/test_rotation.py

As you can see, this method is made to be used as a context-manager using `with`.

Does this solve your issue?

I'm going to improve the docs in order to make this clearer...

**Comment by Lucas-C** [comment]
@arefmalek Do you think that the new docstring would have made usage of this method clearer to you? -> https://pyfpdf.github.io/fpdf2/fpdf/#fpdf.FPDF.rotation

**Comment by arefmalek** [comment]
Hi  @Lucas-C ,

Yes! This appears to be what I needed, my document now does has a "Hello!" at a 30 degree angle with the code included below. 

```
from fpdf import FPDF
pdf = FPDF()

pdf.add_page()
pdf.set_font('helvetica', 'B', 16)

x=50
y=50
with pdf.rotation(angle=30, x=x, y=y):
    pdf.text(x=x, y=y, txt="Hello!")
pdf.output('tuto1.pdf')
```

Regarding the new docstring, I personally would recommend you either link an example of something like 
```
with rotation(angle=30, x=x, y=y):
    pdf.something()
```
(the link you gave me should be good), or explicitly mention that `with` is used similar to file IO. I truthfully wasn't sure what you meant by `with` until I opened the example.

**Comment by abubelinha** [comment]
Hi @Lucas-C and @arefmalek 

I am also trying to put rotated text cells at specific parts of the page but I still cannot understand how to control x,y position.
Tried to implement a `for` loop and see how x,y changes affect the position of a rotated text but I still cannot understand.
It seems to me that inside a `with pdf.rotation` context manager, `x` and `y` are not relative to page anymore (see my failed test below).

Using this code **I am getting a blank pdf page**, which I assume to be 210 mm wide and 297 mm high (A4-size).
So, x=10 and y=280 should be a point close to its left bottom:
```Python
from fpdf import FPDF
pdf = FPDF(orientation="P", unit="mm", format="A4")
pdf.add_page()
pdf.set_font("times")
with pdf.rotation(angle=90, x=10, y=280):
    pdf.cell(text= "This text should start at left bottom of the page and continue upwards through its left margin", border=1) 
pdf.output("fpdf-rotated-text.pdf")
```
This is a image of a Word-generated pdf showing what I am trying to achieve with fpdf2

![Rotated-margin-text](https://github.com/py-pdf/fpdf2/assets/698946/5202b3e0-108b-4978-a013-db39e970ce9c)

**Comment by abubelinha** [comment]
OK, after two days I got it myself. Newbie error:

Inside `rotation(angle,x,y)` context, I should use `text(x,y)` for accurate positioning (instead of `cell()` method, which continues writing after last text position).

Here it goes:

```Python
from fpdf import FPDF
pdf = FPDF(orientation="P", unit="mm", format="A4")
pdf.add_page()
pdf.set_font("times")
a,x,y=90,10,295 # margin banner 1
with pdf.rotation(angle=a, x=x, y=y):
banner = pdf.text(x=x, y=y,
	text= "This text should start at left bottom of the page and continue upwards through its left margin"
	) 
print(banner)  #  this outputs None
pdf.output("fpdf-lateral-banner-text.pdf")
```
Anyone figures out how to draw a solid border around this text?
`text()` method returns `None`, so I can't get dimensions of its bounding box
