### ISSUE TITLE
Not readable barcodes

### ISSUE THREAD

**Issue by ssemenukha** [PyFPDF/fpdf2#197]
Hi!

Detected issue when put some barcode in documents. Generated code can not be read. Neither POS scanner nor smartphone app.

Tried read codes from your [documentation page](https://pyfpdf.github.io/fpdf2/Barcodes.html) - it fails.

**Comment by Lucas-C** [comment]
I have checked and the [Interleaved 2 of 5](https://en.wikipedia.org/wiki/Interleaved_2_of_5) works fine,
but there is indeed an issue with the [Code 39](https://fr.wikipedia.org/wiki/Code_39) barcode generator.

**Comment by Lucas-C** [comment]
This because you need to enclose your text string into wilcards characters (`*`) in order for the resulting barcode to be valid.

I improved the docs & added a warning in the method.

Does that solve your issue @ssemenukha ?
