### ISSUE TITLE
Space appears at the end of each cell() where there is another cell() after

### ISSUE THREAD

**Issue by AubsUK** [PyFPDF/fpdf2#200]
OS: Windows 10
Name: fpdf2
Version: 2.4.2
Python: 3.9.5

When I output text into a cell(), I get a space (or probably some end-of-field character).  It **only** happens when using cell() where there is another cell() after it.

```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font('helvetica', 'B', 16)
pdf.cell(w=40, h=10, txt='Hello World!', border=1, ln=1)
pdf.cell(w=40, h=10, txt='Hello World!', border=1, ln=0)
pdf.ln(h=10)
pdf.ln(h=10)
pdf.cell(w=40, h=10, txt='Hello World!', border=1, ln=0)
pdf.cell(w=40, h=10, txt='Hello World!', border=1, ln=0)

pdf.output('tutorial2.pdf', 'F')
```

The space is visible when highlighting all text produced from the code above

![image](https://user-images.githubusercontent.com/68870168/128646922-82a8ea3f-49a6-451e-8168-7ceec41bcd8c.png)
![image](https://user-images.githubusercontent.com/68870168/128646971-0bfdd140-967e-449c-a030-dd76225ddc86.png)

Any thoughts? - I'm using single characters in each cell and the 'special character' is being picked up by a reader that is looking for single characters in each cell.

**Comment by Lucas-C** [comment]
I have tested and I do not reproduce this behaviour with either Sumatra PDF nor Adobe PDF Reader.

What reader are you using?

**Comment by AubsUK** [comment]
> What reader are you using?

I'd tried with Firefox, Chrome and Adobe PDF Reader. All three showed the same. I actually think it's an end of cell field that doesn't get added to the end of a row. I think it's there with Microsoft Word too.

I had to change my code in the end to use the HTML write method as I don't think it was the 'fake character' causing the issue, but that the reader was looking at each cell as a single table instead of the table as a whole. Sorry for wasting time.

**Comment by Lucas-C** [comment]
No worries, thank you for closing this then
