### ISSUE TITLE
Draw footer without creating a new page

### ISSUE THREAD

**Issue by takase1121** [PyFPDF/fpdf2#201]
Is it possible to draw the footer without using `add_page()`?

**Comment by Lucas-C** [comment]
Sure, you can simply call the `.footer()` method manually.

If it triggers a page break and you want avoid that, do this:
```python
pdf.in_footer = True
pdf.footer()
pdf.in_footer = False
```

Does that answers your question @takase1121 ?

**Comment by takase1121** [comment]
> Does that answers your question @takase1121 ?

Exactly what I needed to know, thanks!
