### ISSUE TITLE
Expose multicell justify option in templates

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#207]
While the multicell has an align="J" option to justify text, this is not currently exposed to the templates.
It would require a simple modification in three places, changing 

```
align = {"L": "L", "R": "R", "I": "L", "D": "R", "C": "C", "": ""}.get(
            align
        )  # D/I in spanish

```
to 

```
align = {"L": "L", "R": "R", "I": "L", "D": "R", "C": "C", "J":"J", "": ""}.get(
            align
        )  # D/I in spanish
```
in each instance.
I could obviously do that myself, but executing a fork and sending a pull request feels like a bit of overkill in this case...
Thanks for your consideration!

**Comment by Lucas-C** [comment]
I opened https://github.com/PyFPDF/fpdf2/pull/208 to implement this

**Comment by gmischler** [comment]
Cool, thanks a lot!

I see you got rid of translation dicts with the spanish codes instead of adding to them, which I didn't dare suggest as I wasn't sure about their history.
But yeah, they were a bit confusing...

**Comment by Lucas-C** [comment]
This has just been released in fpdf2.4.3
