### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by alexanderankin** [PyFPDF/fpdf2#21]
Creating an issue to track all the other issues with font handling. Fonts did not really work with the original code. This issue is supposed to track progress towards figuring it out and implementing changes.

**Comment by alexanderankin** [comment]
#20 is a new one that I haven't seen yet. typically the problem with font handling is that like the cmap is out of range for some unicode characters or something like that.

**Comment by Lucas-C** [comment]
I'm not sure there is a need for a "global" issue given there are already specific issues.
What do you think?

**Comment by alexanderankin** [comment]
I figured that in the long term font handling should be "overhauled" (actually, hauled out to the trash and replaced with some font library), so this would be a good place to discuss. Also, I'm used to JIRA's "epic" concept which lets issues be linked to one another. I would prefer we keep this open for now.

I somehow think that even after #26 theres gonna be some unicode stuff that crops up just because font handling is for font libs not fpdf.

**Comment by Lucas-C** [comment]
If you're used to JIRA, you may want to check out GitHub Projects: https://github.com/alexanderankin/pyfpdf/projects

I fully agree about using a dedicated lib for font handling!

**Comment by bwdalmijn** [comment]
Hi,
Dont know if my question belongs here, but starting a seperate issue for it seems a bit much.
The self.charwidths attribute of the TTFontFile class is a list.
However the FPDF class wants it to be a dictionary.
Is my observation correct? Is it easy to fix? (I'm not that much at home in the ttfonts python file).

Kind regards,

**Comment by alexanderankin** [comment]
Thanks, this is exactly the kind of discussion this issue was intended for.
I unfortunately have a busy start but have in the past very
fruitlessly tried to study those details myself.

**Comment by Lucas-C** [comment]
@bwdalmijn What makes you think that "the FPDF class wants it to be a dictionary" ?

**Comment by bwdalmijn** [comment]
@Lucas-C When i try adding a font and then using it (TrueType Fontfile that is):
The functions I use are slightly modified compared to yours, but the mechanics are the same.
```python
pdf.add_font("courier",style='',fname="cour.ttf",file_type="uni")
pdf.add_font("courier",style='B',fname="courb.ttf",file_type="uni")
pdf.add_font("courier",style='I',fname="couri.ttf",file_type="uni")
pdf.add_font("courier",style='BI',fname="courbi.ttf",file_type="uni")
pdf.set_font("courier",9)
```
when "compiling" i get the error message:
```python
AttributeError: 'list' object has no attribute 'get'
```

This refers to the "cw" element of a font in the dictionary FPDF.fonts.
The 'cw' element of a core-font, for instance, is a dictionary, where the characters are used as keys for their respective widths.
This way the functions in the fpdf class know how to extract the widths for each character.
This is missing when a ttf file is broken down and made into a font dictionary.

This should explain what i meant earlier.

Kind regards,

**Comment by Lucas-C** [comment]
Thank you for the detailed explanations.

There is a minimal code snippet showing how to load "courier.ttf" and use it to render some text:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.add_font("Courier", style="", fname="courier.ttf", uni=True)
pdf.set_font("Courier", "", 36)
pdf.text(50, 50, "Hello!")
pdf.output("hello.pdf")
```

I have just tested this with latest version of the code on this repository, and it works fine.

Maybe the exception you got came from your custom code?

To help you we will need a minimal code that reproduces your issue, with a specific published version of `fpdf2`.
Otherwise I'm sorry but we won't be able to help you 😔

**Comment by bwdalmijn** [comment]
Hi @Lucas-C,

Thank you for the reply. 
If it works fine for you then correct assumption would be that my alterations caused the error, yes.
Thank you for trying it out. 
I will dig a bit to see what's going on. 
If you're interested I could drop the main fpdf.py somewhere. That is basically all that differs.

King regards,

**Comment by Lucas-C** [comment]
`fpdf/fpdf.py` changed a lot in the last 2 weeks, with the addition of `black` as code formatter.
Your version may be very different now.

If yours adds some useful features, and you want to contribute to this repo by adding them in `fpdf2`, feel free to open a _Pull Request_ to submit your code!

**Comment by alexanderankin** [comment]
https://github.com/reingart/pyfpdf/issues/181
