### ISSUE TITLE
Failing unit-tests?

### ISSUE THREAD

**Issue by RubendeBruin** [PyFPDF/fpdf2#212]
I'm about to start implementing #91 , but many of the html unit-tests fail on my machine:

![image](https://user-images.githubusercontent.com/34062862/132296552-a25dec90-0bc1-4e3b-bc72-1281f5c1d5e3.png)

running the latest master and using qpdf.

_Visually_ the produced pdf looks the same as the reference pdf, but the qpdf based comparison fails on differences like: 
![image](https://user-images.githubusercontent.com/34062862/132298011-40173a0c-dc28-4b16-925d-2967c971c338.png)

**Comment by Lucas-C** [comment]
Hi @RubendeBruin 

Thanks for the report

The paths to the temporary PDF files generated by the tests should be displayed in the tests output.

Could you provide the PDF file resulting from `test_issue_156` on your computer please?

**Comment by RubendeBruin** [comment]
My mistake, the checkout of master was not clean. It passes now.

consider closed.
