### ISSUE TITLE
set font windows-1255

### ISSUE THREAD

**Issue by igorg2** [PyFPDF/fpdf2#214]
when i using a multi_cell command like this "pdf.multi_cell(pdf.epw, 8, text_file.read())"
i received error "nicodeEncodeError: 'latin-1' codec can't encode characters in position 75-79: ordinal not in range(256)"
i my text is with character encoding windows-1255 , how can i set encoding windows-1255 instead of default latin-1 ?

**Comment by Lucas-C** [comment]
Hi @igorg2!

Thanks for reporting you issue.

Could you please provide a minimal Python code snippet that produces this error,
so that we can help you with this encoding problem?

**Comment by igorg2** [comment]
Thanks for your attention
I founded a solution with set a right TrueType font .

**Comment by Lucas-C** [comment]
Alright, glad you found a solution to your problem 😊

Closing this ticket then
