### ISSUE TITLE
Insufficient line height for large heading tags <h1>, <h2>

### ISSUE THREAD

**Issue by ping** [PyFPDF/fpdf2#223]
This is apparent when the heading text is long and wraps over 2 lines or more.
Even the `<p>` tag line-height is a little too short in my opinion, but it's not half as bad as `<h1>` `<h2>`.

Since there is no css support, is there any way to influence line height?

> DejaVuSans, size 14
> ![Screenshot - DejaVuSans](https://user-images.githubusercontent.com/104607/134097139-d059189c-33f7-4ab1-9e68-11f8fb9b737b.png)

> Default (no font specification)
> ![Screenshot 2021-09-21 at 9 04 38 AM](https://user-images.githubusercontent.com/104607/134097216-4ad5adc6-8ff9-4dbd-8723-279ba09059fd.png)

```
$ python --version
Python 3.7.4
```
Code to replicate the problem:

```python
from fpdf import FPDF, HTMLMixin


class PDF(FPDF, HTMLMixin):
    pass


pdf = PDF(orientation="P", unit="mm", format="A4")
pdf.add_font("DejaVuSans", fname="fonts/DejaVuSans.ttf", uni=True)
pdf.set_font("DejaVuSans", size=14)

pdf.add_page()
long_title = "The Quick Brown Fox Jumped Over The Lazy Dog "
html_content = f"""
<h1>H1   {long_title*2}</h1>
<h2>H2   {long_title*2}</h2>
<h3>H3   {long_title*2}</h3>
<h4>H4   {long_title*3}</h4>
<h5>H5   {long_title*3}</h5>
<h6>H6   {long_title*4}</h6>
<p>P   {long_title*5}<p>
"""
pdf.write_html(html_content)
pdf.output("test.pdf")
```

**Comment by Lucas-C** [comment]
Thanks for reporting the issue

I have opened https://github.com/PyFPDF/fpdf2/pull/236 to fix this

**Comment by Lucas-C** [comment]
I also opened https://github.com/PyFPDF/fpdf2/pull/237 to make headings sizes configurable

**Comment by ping** [comment]
@Lucas-C 
Thanks for the fixes. I found some issues with the fix after updating my local install to fb9af3d.

1. The TOC rendering has become messed up.

![fb9af3d_toc](https://user-images.githubusercontent.com/104607/135179919-65e8e8b0-77dc-430f-ad01-4fa96b5d4c1b.png)
 
2. The subsequent `<p>` tag rendered after the headings now becomes incrementally smaller, depending on the prior heading size. They look like they're being set to the same font size as the heading tag.

![fb9af3d_content](https://user-images.githubusercontent.com/104607/135180144-458ab584-7e06-43a8-8328-912b1953db27.png)

Code to replicate the problem:

```python
from fpdf import FPDF, HTMLMixin


class PDF(FPDF, HTMLMixin):
    pass


pdf = PDF(orientation="P", unit="mm", format="A4")
pdf.add_font("DejaVuSans", fname="fonts/DejaVuSans.ttf", uni=True)
pdf.set_font("DejaVuSans", size=14)

pdf.add_page()
long_title = "The Quick Brown Fox Jumped Over The Lazy Dog "
html_content = f"""
<h1>TOC - Master fb9af3d</h1>
<toc pages="1"></toc>
<h1>H1   A Shorter Title</h1>
<p>P   {long_title*3}<p>
<h1>H1   {long_title}</h1>
<p>P   {long_title*3}<p>
<h1>H1   {long_title*2}</h1>
<p>P   {long_title*3}<p>
<h2>H2   {long_title*2}</h2>
<p>P   {long_title*3}<p>
<h3>H3   {long_title*2}</h3>
<p>P   {long_title*3}<p>
<h4>H4   {long_title*3}</h4>
<p>P   {long_title*3}<p>
<h5>H5   {long_title*3}</h5>
<p>P   {long_title*3}<p>
<h6>H6   {long_title*4}</h6>
<p>P   {long_title*3}<p>
"""
pdf.write_html(html_content)
pdf.output("test.pdf")
```

**Comment by Lucas-C** [comment]
Thanks for the feedback @ping

I have added a new code fix.
Could you test the latest version on the `master` branch please?

**Comment by ping** [comment]
@Lucas-C Thanks for the quick fix. The decreasing font problem has been indeed been solved.
The TOC also looks better now.

I've found another issue with the TOC rendering but it is a problem that aready exists on v2.4.3 and not specific to this issue fix. Should I create a new issue for this?

1. This problem occurs when a long heading title (which wraps) comes after a shorter heading title. The second same level heading (example, 1st short `<h1>` followed by 2nd long `<h1>`) becomes indented compared to the previous heading. This is most obvious with `<h5>` `<h6>` in screenshot below.

2. I've also noticed that the "........." (I don't know what to call it) that comes before the page number is no longer rendered when the TOC line wraps due to length.

![toc_left_offsets](https://user-images.githubusercontent.com/104607/135265157-34166871-3554-4ddc-85d0-9d9310245166.png)

**Comment by Lucas-C** [comment]
You can customize the TOC rendering: https://pyfpdf.github.io/fpdf2/fpdf/html.html#fpdf.html.HTML2FPDF.render_toc

**Comment by Lucas-C** [comment]
I reckon there could be some documentation on how to do that.

Would you mind reviewing https://github.com/PyFPDF/fpdf2/pull/239 please @ping?
I tried to make things clearer & easier about HTML TOC rendering customization in this PR.

**Comment by Lucas-C** [comment]
@all-contributors please add @ping for bug

**Comment by Lucas-C** [comment]
@ping do you think this issue can be solved? :)

**Comment by ping** [comment]
Looks good to me. Thanks for the quick fix!
