### ISSUE TITLE
FPDF.rotation() behaves weirdly

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#226]
While implementing offset and rotated rendering of template data, I ran into quite some weird behaviour.

```python
import  fpdf

fix = True

def stamp(pdf, x, y):
    pdf.set_text_color(0x0)
    pdf.set_fill_color(0xFFFFFF)
    pdf.set_draw_color(0x0)
    pdf.set_line_width(0)

    pdf.set_font("times", "", 20)

    pdf.rect(0+x,  0+y, 50, 50, style="FD")
    pdf.line(0+x,  0+y, 50+x, 50+y)
    pdf.line(0+x, 50+y, 50+x,  0+y)
    pdf.set_xy(0+x, 52+y)
    pdf.cell(50,5,"this is a label", border=0, ln=0, align="L", fill=True)

pdf = fpdf.FPDF()
pdf.add_page()

if fix:
    pdf.set_font("helvetica", "", 10)

for r,x,y in ((5, 50,50),(10,50,120), (15,120,50),(20,120,120)):
    with pdf.rotation(r, x, y):
        stamp(pdf, x,y)

pdf.output("badrot.pdf")
```
While `fix = True`. everything looks fine - at least at first sight.
Taking another look you'll notice that only the first "stamp" is using the font set in the subroutine, the others take the one from the top level.
If you remove the top-level font setting (`fix = False`), part of the page simply disappears. It may be still there, though, just painted in white. This is the most reduced example I could come up with that shows some effect, but there's other stuff that can happen...

If you're willing to fetch https://github.com/gmischler/fpdf2/blob/master/fpdf/template.py , you can try the following:

```python
import  fpdf

elements = [ { "name": "box", "type": "B", "x1": 0, "y1": 0, "x2": 50, "y2": 50,
            #"rotate": 15.0,
            },
        { "name": "d1", "type": "L", "x1": 0, "y1": 0, "x2": 50, "y2": 50,
            "rotate": 15.0,
            },
        { "name": "d2", "type": "L", "x1": 0, "y1": 50, "x2": 50, "y2": 0,
            "rotate": 15.0,
            },
        { "name": "label", "type": "T", "x1": 0, "y1": 52, "x2": 50, "y2": 57, "text": "Label",
            #"rotate": 15.0,
            },
        ]
pdf = fpdf.FPDF()
pdf.add_page()
pdf.set_font("courier", "", 10)
templ = fpdf.template.FlexTemplate(pdf, elements)
templ["label"] = "Offset: 50 / 50 mm, Rotate: 5°"
templ.render(offsetx=50, offsety=50
        #, rotate=5
        )
templ["label"] = "Offset: 50 / 120 mm, Rotate: 10°"
templ.render(offsetx=50, offsety=120
        , rotate=10
        )
templ["label"] = "Offset: 120 / 50 mm, Rotate: 15°"
templ.render(offsetx=120, offsety=50
        , rotate=15
        )
templ["label"] = "Offset: 120 / 120 mm, Rotate: 30°"
templ.render(offsetx=120, offsety=120
        , rotate=30.0
        )
pdf.output("badrot.pdf")
```

The way as presented, everything looks fine.
If you activate any of the commented-out `rotate` arguments/keys, most elements in the generated pdf will get a completely black background. We *do* have a top-level font setting here, and the template sets its own default "helvetica", which actually gets used. In this case, the main trigger rather seems to be the total number of rotations on the page.

It took me a while to figure out that certain combinations of font settings can trigger this for the minimal example at top, but I have no idea if that's the actual reason or just another symptom. The PDF generation side of things here is a complete mystery to me (and will remain one), so I wouldn't even know where to look.

There seems to be no documentation for the rotation functionality (besides the generated API reference), so I'm not sure if this is actually meant to be used, or still a work in progress. Maybe those exmples help someone with better understanding to figure out where the problem lies, and hopefully come up with a fix.

**Comment by Lucas-C** [comment]
Thanks for reporting this!

Some methods simply should not be used inside a `FPDF.rotation` context:
```python
pdf.add_page
pdf.set_font
pdf.set_font_size
pdf.set_draw_color
pdf.set_fill_color
pdf.set_text_color
pdf.set_line_width
pdf.set_stretching
```


I opened this PR in order to forbid this:
https://github.com/PyFPDF/fpdf2/pull/229

**Comment by Lucas-C** [comment]
@allcontributors please add @gmischler for bug
