### ISSUE TITLE
Template type for code39 ignores template field conventions

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#227]
`Template.cod39()` uses field names just directly taken from `FPDF.code39()`, instead of adhering to the standard template format. This kind-of "worked" for elements dicts, but was impossible to use with csv files.

I'm going to fix this together with my refactoring, deriving the required values as follows:

```python
x = x1
y = y1
## w = x2 - x1
w = size
h = y2 - y1
```
edit: the "barcode" type uses "size" for the bar width, so I'll do the same.

It looks like the function has only been in there for a few months, so I hope not too many people already rely on the broken API in user code... 
We should probably raise an explanatory exception when one of the bad field names is used (at least for a while), and also mention the change in the documentation.

**Comment by Lucas-C** [comment]
Sounds good to me!

Thanks for spotting this and for planning to submit a PR in order to improve things!

**Comment by Lucas-C** [comment]
It seems that you fixed this as part of https://github.com/PyFPDF/fpdf2/pull/228, am I right?

**Comment by gmischler** [comment]
Yes, it's fixed in #228.
