### ISSUE TITLE
Template.split_multcell() modifies document

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#238]
`FPDF.multi_cell(split_only=True)` is designed not to modify the file, and that's what `Template.Split_multicell()` uses.

But...

To actually make it work, it needs to call `FPDF.set_font()` first. And that does modify the document, even if the effect is not immediately visible. Because it happens asynchronously to the actual rendering of the related template element, it will quite often lead to spurious data in PDF documents. Or does `FPDF()` check whether a font setting is actually used, before writing it into the file?

If not, there would be a relatively simple solution on the `Template()` side. Since I'm fiddling in the area anyway: Would it make sense to create a seperate dummy `FPDF()` instance for this purpose? Then the extra content would go there, and not unnecessarily pollute the target document.

**Comment by Lucas-C** [comment]
> does FPDF() check whether a font setting is actually used, before writing it into the file?

Whenever a font is add with `add_font`, it will be inserted in the PDF, whether `set_font` is used or not

> Would it make sense to create a seperate dummy FPDF() instance for this purpose?

It is certainly doable, but it would add quite some complexity to the code...

Why don't you want to call `set_font` in or before calling `Template.Split_multicell` exactly?

**Comment by gmischler** [comment]
> > Would it make sense to create a seperate dummy FPDF() instance for this purpose?
> 
> It is certainly doable, but it would add quite some complexity to the code...
> 
> Why don't you want to call `set_font` in or before calling `Template.Split_multicell` exactly?
> 
> In [#228 (comment)](https://github.com/PyFPDF/fpdf2/pull/228#issuecomment-931551230) you wrote:
> 
> > Splitting text doesn't modify the target document anymore.
> 
> What approach did you chose in the end?
