### ISSUE TITLE
Suggestion: rename repo "fpdf2"

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#25]
This would make clearer for all users that this repo is the source code behind the `fpdf2` lib: https://pypi.org/project/fpdf2/

What do you think?

**Comment by alexanderankin** [comment]
yeah, that makes sense. should i just like... do it?

**Comment by Lucas-C** [comment]
Whenever you want yes, but this will have many impacts on links in the documentation

**Comment by Lucas-C** [comment]
@alexanderankin As you moved this repo to a dedicated org, do you mind if I perform the renaming of this repo into `fpdf2`, and I make the changes everywhere needed in the docs?

**Comment by alexanderankin** [comment]
yeah thats fine.

**Comment by Lucas-C** [comment]
Done, ang global renaming performed in https://github.com/PyFPDF/fpdf2/commit/73e1b8542bb15e9aec96d82ba5bf531a847b81fc
