### ISSUE TITLE
multi_cell with split_only=True requires add_page

### ISSUE THREAD

**Issue by edsonitk** [PyFPDF/fpdf2#279]
Hi,

Using pyfpdf I could use multi_cell (split_only=True) just to know the number of lines in the string but now using pyfpd2 I have to previously use add_page().
mistake:
fpdf.errors.FPDFException: No page open, you need to call add_page() first

**Comment by Lucas-C** [comment]
Thanks!

I'm closing this then, but feel free to reopen the issue if you'd like to discuss it further or suggestions for changes.
