### ISSUE TITLE
Feature Request: Support soft hyphen in Multicell

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#291]
The [soft hyphen](https://en.wikipedia.org/wiki/Soft_hyphen) (Unicode `U+00AD`) is used by a lot of text processing software to mark a position in a word where breaking the line with a normal hyphen would be acceptable. If used appropriately, the result are text blocks that flow much more naturally, especially when long words are used in a narrow column. The edge(s) get much less jagged in aligned text, and big gaps between words are avoided in justified text.
There are some variations in detail, but the general procedure is this: As long as there is no need for a line break near it, it is simply ignored and not rendered at all. In a case where the line breaking zone falls within that word, the soft hyphen gets replaced by a normal hyphen and a newline. 

Sounds simple enough...
Unfortunately, `.multi_cell()` already does some of the most complicated processing in fpdf, because it has to deal with both manual (on `\n`) and automatic (on whitespace) line breaks, as well as with page breaks on top of that. To add yet more features and special cases, it should probably be refactored into several subroutines.

I'm currently rather reluctant to delve quite that deep into the guts of the system myself, so I guess we'll have to put this one up for grabs for the moment.

**Comment by Lucas-C** [comment]
Thank you @gmischler for suggesting this valuable feature!

**Comment by oleksii-shyman** [comment]
Hello, I would like to work on this feature.
Can I get assigned to me?

**Comment by Lucas-C** [comment]
Great!
Sure, done

**Comment by oleksii-shyman** [comment]
Status update -> created a draft pull request here

https://github.com/PyFPDF/fpdf2/pull/308

**Comment by Lucas-C** [comment]
Good job @oleksii-shyman on providing this feature,
and improving the code base at the same time!

Soft hyphen is now supported in both `cell()` & `multi_cell()` methods now!
