### ISSUE TITLE
set margin

### ISSUE THREAD

**Issue by CodingBDX** [PyFPDF/fpdf2#295]
hello
i use pyfpdf i think and now i use your script but you call the function by the same name?? from fpdf ????

otherwise
i just want put margin into my pdf but i search pdf.setmargin  ? mypdf.set_margin ? set_margins?
what's is correct, please?

and other question, i put image card in my pdf and i would like background image, it's possible???

thank for answer

**Comment by Lucas-C** [comment]
Hi @bibiyanki2 and welcome!

Thanks for reaching out with your questions 😉

I may need a bit more info to be able to help you.
Could give a little more details on what you mean by this sentence:
> i use pyfpdf i think and now i use your script but you call the function by the same name?? from fpdf ????

1. How have you installed `fpdf2`? The standard way, using `pip install fpdf2`?
2. What function are you trying to call exactly? And if you are facing an error message, could you please share it here in details?
4. Have you read [the documentation on margins](https://pyfpdf.github.io/fpdf2/Margins.html)?

Regarding having a background image,
you may want to have look at this unit test providing an example of rendering an image full height or full width:
https://github.com/PyFPDF/fpdf2/blob/master/test/image/test_full_page_image.py

**Comment by bibiyanki2** [comment]
my script

` class MyFPDF(FPDF):
            
             pass
    
        def photos_pdf():
             pdf = MyFPDF("P", format='A3', unit='mm')
             photos = glob.glob(filePath1 + "/*.png")
             x = 5
             y = 5
             counter = 0
             nbre = 5
             nbre_par_page = 15
             counter2 = 0
             
             pdf.add_page()
             

             for photo in photos:
                if counter2 != nbre_par_page:    
                    if counter != (nbre):
                        
                        pdf.image(photo, x=x, y=y, w=63, h=88)
                        x += 63
                        counter += 1
                        counter2 += 1
                    
                    else:
                        
                        pdf.image(photo, x=x, y=y, w=63, h=88)
                        y += 88
                        x = 0
                        counter = 0
                        
                else:
                    
                    pdf.image(photo, x=x, y=y, w=63, h=88) 
                    pdf.add_page()
                    
                    
                    counter = 0
                    counter2 = 0
                    
                    x = 0
                    y = 0
               
           
             pdf.output(path2 + "/A4_cards.pdf", 'F')
             os.chmod(path2 + "/A4_cards.pdf", 0o777)
        photos_pdf()  `

yes i have install pip install fpdf2
i will like put margin in my pdf but not my photo "have other margin!"
and i will like put background img, but it's possible with photos??

thank for answer

**Comment by Lucas-C** [comment]
> and i will like put background img, but it's possible with photos??
Photos are images, so yes it's possible.

> i will like put margin in my pdf but not my photo "have other margin!"

Sadly, this sentence does not make much sense in English...
Comme tu sembles parler français, essaie peut-être de m'expliquer ta question ou ton problème dans la langue de Molière 😉

**Comment by gmischler** [comment]
@bibiyanki2, I think you are trying to have a background image across the full size of the of the page without any white space around it, while the rest of the contents should still be limited to the area within the page margins.

To do that, you can use `pdf.set_margin(0)` to set all margins to zero, and insert your image to the full paper size.
Then you set the margins back to some suitable values, and add the remaining content.

**Comment by Lucas-C** [comment]
Hi @CodingBDX

Have you solved your issue?

Without any feedback from you, I'm going to close this issue soon.
