### ISSUE TITLE
`Add a new default font`

### ISSUE THREAD

**Issue by TECH-SAVVY-GUY** [PyFPDF/fpdf2#301]
Hi, just wanted to ask: Can you all include [Roboto-Slab](https://fonts.google.com/specimen/Roboto+Slab) as a default font for FPDF2?

Actually, I am making a module which is dependent on this library and the `add_font()` method is not working.

![image](https://user-images.githubusercontent.com/83786816/141831622-7681439a-7759-4906-98b2-ea7456f18453.png)

The best possible solution is to add the font as a default one to the FPDF2 library itself.

Let me know if it can be done. In case, you want me to help add the font to the library, kindly tell me the steps that I need to follow.

**Comment by Lucas-C** [comment]
Hi @TECH-SAVVY-GUY

> the `add_font()` method is not working.

You did not provide details on what error you are facing, so it will be very difficult to help you...

I just tested embedding this font, and it works fine:
```python
import fpdf

pdf = fpdf.FPDF()
pdf.add_page()
pdf.add_font("RobotoSlab", fname="RobotoSlab-Regular.ttf", uni=True)
pdf.set_font("RobotoSlab", size=36)
pdf.cell(txt="Testing RobotoSlab font", w=pdf.epw, align="C")
pdf.output("issue_301.pdf")
```

**Comment by TECH-SAVVY-GUY** [comment]
Hey, sorry for the late response.

Actually, I was building my a module which depended on the `FPDF2` package.

I wanted to add my custom font in the module itself. That's why I wanted to contribute in adding a font to this package by default.

Anyways, I discarded that thought and used one of the default fonts that `FPDF2` provides already.

Feel free to check out my [module ](https://pypi.org/project/csv2pdf/)➜ https://github.com/TECH-SAVVY-GUY/csv2pdf

**Comment by Lucas-C** [comment]
Nice!

**Comment by Lucas-C** [comment]
I added a mention of your project on this documentation page:
https://pyfpdf.github.io/fpdf2/#community
(it should appear in less than 5min)

Is it OK for you to close this issue then @TECH-SAVVY-GUY ?

**Comment by TECH-SAVVY-GUY** [comment]
> I added a mention of your project on this documentation page: https://pyfpdf.github.io/fpdf2/#community (it should appear in less than 5min)

Thanks for mentioning my project! 😁

> Is it OK for you to close this issue then @TECH-SAVVY-GUY ?

Sure, I am closing this issue 😄
