### ISSUE TITLE
colspan and rowspan in html_write() function

### ISSUE THREAD

**Issue by Zwolfen** [PyFPDF/fpdf2#304]
Hello, can html_write() use such properties as "colspan" and "rowspan"?
Or maybe there is another way to make more complicated tables with html_write() function?
And i just dont get the way how?

simply example

```python
html_write(f"""<table border="1">
    <thead>
        <tr>
            <th width="20%" rowspan="2">1</th>
            <th width="80%" colspan="2">2</th>
        </tr>
        <tr>
            <th width="48%">2.1</th>
            <th width="32%">2.2</th>
        </tr>
    </thead>
    <tbody>
    <tr>
    <td width="20%" align="center">1.1</td>
    <td width="32%" align="center">2.1.1</td>
    <td width="48%" align="center">2.2.1</td>
    </tr>
    </tbody></table>""")
```

![simply_table_html](https://user-images.githubusercontent.com/16862799/143901924-6a79af60-2014-4c8b-aa85-6b876f0ca41f.JPG)

and what i get now, trying to use same html code. (i know that now such properties are not supported)
![pdf_file_table](https://user-images.githubusercontent.com/16862799/143902635-a862aa7c-aff0-472c-a304-d4d61af7eca1.JPG)

**Comment by Lucas-C** [comment]
`colspan` is supported. Example:
* [unit test](https://github.com/PyFPDF/fpdf2/blob/master/test/html/test_html.py#L366)
* [resulting PDF](https://github.com/PyFPDF/fpdf2/blob/master/test/html/test_img_inside_html_table_centered_with_caption.pdf)

`rowspan` is however not supported yet.

**Comment by Lucas-C** [comment]
@Zwolfen: did I answered you question?
Regarding this issue, can we close it, or would like to keep it open as a feature request?
If so, would you like to implement such feature?

**Comment by Lucas-C** [comment]
Closing this for now.
For reference, another user wrote some code (not based on HTML) that generates a table header with some rowspan:
https://github.com/PyFPDF/fpdf2/discussions/373
