### ISSUE TITLE
Suggestion: migrate all the docs in docs/reference into docstrings

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#31]
It seems to me that the API docs generated with `pdoc` serve the same purpose as the Markdown files in [docs/reference](https://github.com/alexanderankin/pyfpdf/tree/master/docs/reference).

Hence the idea would be to remove `docs/reference` after migrating all those useful API docs directly in the code as docstrings.

Moreover, in my experience the closest the doc is to the code, the higher are the chances to keep it up-to-date as the code evolves.

What do you think?

**Comment by alexanderankin** [comment]
yes i think this seems worthwhile but also quite a chore so the best thing here is to make an example PR and leave comments with how exactly it works and then i can help out with this too.

**Comment by alexanderankin** [comment]
So an example of this would be in #33 and specifically on these lines:

https://github.com/alexanderankin/pyfpdf/blob/5278440725706b39e864364226166ca9d40cdf2a/fpdf/template.py#L161-L167

**Comment by Lucas-C** [comment]
Progress status: **30% migrated**
```
$ grep -lF issues/31 docs/reference/*.md | wc -l
17
$ ls docs/reference/*.md | wc -l
55
```
