### ISSUE TITLE
Not displaying Russian text in the table of contents

### ISSUE THREAD

**Issue by lcomrade** [PyFPDF/fpdf2#320]
Russian characters are not displayed in the table of contents.
But English text, numbers and special characters are displayed normally.

**Error details**
I don't get any exceptions.

**Minimal code**
```python
from fpdf import FPDF
from fpdf import TitleStyle

if __name__ == "__main__":
    # Setup
    pdf = FPDF("P", "mm", "A4")
    pdf.add_page()

    pdf.add_font("FreeMono", fname="FreeMono.ttf", uni=True)
    pdf.add_font("FreeMonoBold", fname="FreeMonoBold.ttf", uni=True)
    pdf.set_font("FreeMono", style="", size=18)

    pdf.set_section_title_styles(TitleStyle(
        font_family="FreeMonoBold",
        font_style="",
        font_size_pt=24,
        color=None,
        underline=False,
        t_margin=10,
        l_margin=10,
        b_margin=0,
    ))

    # Write text
    pdf.start_section("Русский, English, 1 2 3...")

    pdf.write(8, "Русский текст в параграфе.")
    pdf.ln(15)

    # Save result
    pdf.output("test.pdf")

```

**Environment**
* GNU/Linux
* Python 3.9.2
* `fpdf2` 2.4.6

**Comment by lcomrade** [comment]
The table of contents should be `Русский, English, 1 2 3...`, but it displays `, English, 1 2 3...`.

![image](https://user-images.githubusercontent.com/70049256/149939089-e8fa1598-53c4-445c-aeb3-d895b6f1566a.png)

**Comment by Lucas-C** [comment]
Thank you for reporting this @lcomrade

This is strange as we should have a test covering this already:
* https://github.com/PyFPDF/fpdf2/blob/master/test/html/test_html.py#L433
* https://github.com/PyFPDF/fpdf2/blob/master/test/html/html_heading_hebrew.pdf
* introduced in https://github.com/PyFPDF/fpdf2/pull/222/files

I'll try to have a closer look at it this evening

**Comment by Lucas-C** [comment]
@all-contributors please add @lcomrade for bug

**Comment by Lucas-C** [comment]
OK so in fact the existing test shares the same issue:
the hebrew text is not rendered in the outline.

I guess we need to find the correct encoding to use when embedding unicode text in the document outline.
