### ISSUE TITLE
Improve error msg to suggest using a unicode font when getting UnicodeEncodeError: 'latin-1' codec can't encode character

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#330]
Some unicode characters cannot be rendered using the built-in fonts.

This issue was first reported in https://github.com/reingart/pyfpdf/issues/86#issuecomment-1020683025.

**Minimal code**
```python
#!/usr/bin/env python3
import fpdf
pdf = fpdf.FPDF()
pdf.add_page()
pdf.set_font("Helvetica", size=15)
pdf.cell(txt="Joséō"")
pdf.output("issue_330.pdf")
```

**Output**
```
Traceback (most recent call last):
  File "issue_330.py", line 7, in <module>
    pdf.cell(txt="Joséō")
  File "/opt/fpdf2/fpdf/fpdf.py", line 221, in wrapper
    return fn(self, *args, **kwargs)
  File "/opt/fpdf2/fpdf/fpdf.py", line 2014, in cell
    txt = self.normalize_text(txt)
  File "/opt/fpdf2/fpdf/fpdf.py", line 2948, in normalize_text
    return txt.encode(self.core_fonts_encoding).decode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u014d' in position 4: ordinal not in range(256)
```

**Comment by Lucas-C** [comment]
A workaround is to use a unicode font instead of a built-in one

**Comment by Lucas-C** [comment]
I tested this case with [borb](https://github.com/jorisschellekens/borb):
```python
from borb.pdf.canvas.layout.page_layout.multi_column_layout import SingleColumnLayout
from borb.pdf.canvas.layout.text.paragraph import Paragraph
from borb.pdf.document import Document
from borb.pdf.page.page import Page
from borb.pdf.pdf import PDF

pdf = Document()
page = Page()
pdf.append_page(page)
layout = SingleColumnLayout(page)
layout.add(Paragraph("Joséō"))    
with open("issue_330_borb.pdf", "wb") as pdf_file:
    PDF.dumps(pdf_file, pdf)
```
It results in this error:
```
AssertionError: Font Helvetica can not represent 'ō'
```

**Comment by Lucas-C** [comment]
Hence, as I suspected, rendering those characters with the builtin font is not possible.
We should improve `fpdf2` error message though.

**Comment by mtkumar123** [comment]
Hello, I would like to work on this issue if possible please. I'm new to contributing to open source projects, but I think I should be able to do this as a first issue, and learn more about PyFPDF.

**Comment by Lucas-C** [comment]
Great and welcome @mtkumar123! 😊

A good starting point is our documentation page dedicated to [Development](https://pyfpdf.github.io/fpdf2/Development.html).

You'll also find many guides there: https://github.com/freeCodeCamp/how-to-contribute-to-open-source

But most important: feel free to ask any question you'd like, may it be related to this projets, to Python, or to the tools & methodology we use.

**Comment by mtkumar123** [comment]
Created PR https://github.com/PyFPDF/fpdf2/pull/396
Let me know if I have missed anything, I can work on it!

**Comment by Lucas-C** [comment]
Solved by https://github.com/PyFPDF/fpdf2/pull/396
