### ISSUE TITLE
_substitute_page_number function is logging message as INFO level

### ISSUE THREAD

**Issue by luciano-schirmer** [PyFPDF/fpdf2#331]
IMHO, it should log at DEBUG level. Logging it as INFO ends up bloating the log of the application that uses fpdf. I didn't find a way to suppress this log message and I think it is not useful information at INFO level.

The code is in [this line](https://github.com/PyFPDF/fpdf2/blob/4a636e1eab8300ca95535ec8b6cf0fcfa752d4a9/fpdf/fpdf.py#L3073).

I noticed that this is the only log message that uses INFO level.

**Comment by luciano-schirmer** [comment]
Note: [Documentation](https://pyfpdf.github.io/fpdf2/Logging.html) says that fpdf logs messages at DEBUG level. It doesn't mention INFO level, so it may be a bug.

**Comment by Lucas-C** [comment]
I think this is a totally fine suggestion 😊
Do you want to contribute a PR?
Else I'll do the change myself.

**Comment by luciano-schirmer** [comment]
I'd be glad to contribute in a couple of days.
