### ISSUE TITLE
Make FPDF.write() use _render_styled_cell_text()

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#340]
In #308, @oleksii-shyman introduced a new `FPDF._render_styled_cell_text` method.
It should also be used by the `FPDF.write` method in order to harmonize code.

Unit tests already exist that cover `FPDF.write` behavior, so this refactoring should be relatively straightforward.

_cf._ #339 for more context

**Comment by harshlancer** [comment]
Can I work on this issue?

**Comment by Lucas-C** [comment]
Sure @harshlancer, and welcome!

I'm going to _assign_ you this issue to reflect your interest on it.

As a starting point I would recommend that you get a look at the [Development documentation page](https://pyfpdf.github.io/fpdf2/Development.html). Maybe start to get the sources with `git`, install it with `pip install -e .` and launch the [unit tests](https://pyfpdf.github.io/fpdf2/Development.html#testing) with `pytest`.

If you have any questions (on the code, tests, how things work...), feel free to ping me! 😊

**Comment by Lucas-C** [comment]
Hi @harshlancer !

Have you been able to look at this? 😊
