### ISSUE TITLE
Simplify specifying the new position after multline text

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#343]
When having a closer look at how to best adapt `.write()` to the new line wrapping code (per #340), I ended up struggling a bit with the concept behind the `ln=#` parameter to both `.multicell()` and `.write()`, and now also `._render_styled_cell_text()`.  Judging by its name, I suspect that originally it was only meant as a `True/False` value to indicate wether the position should move to a new line. Later it seems to have been increasingly overloaded to also indicate horizontal movement (or maybe it was badly designed right from the start, who knows...) Either way, using an arbitrary single numerical value to indicate movement choices in both x and y is rather confusing and unintuitive. 

To improve the clarity of the API and also simplify maintenance, I think it would make sense to seperate the two functionalities. The simplest way is probably to introduce a seperate argument `new_xpos=""`, with a single character value choice of `"L|R|S|E"`, for **L**eft/**R**ight of the requested cell extents, or **S**tart/**E**nd of the actual text rendered. 

The `ln=` parameter could then again be reduced to a `True|False` choice of moving to a new line or not, ideally with a deprecation warning for other uses.

Any thoughts? Better names for the new parameter?

**Comment by gmischler** [comment]
On closer inspection, it's even worse than I first thought, since `.multi_cell()` actually uses different semantics than the other two (assuming we can trust the docstrings):
```
_render_styled_cell_text()
	`0`: to the right;
	`1`: to the beginning of the next line
	`2`: below. 

cell()
	`0`: to the right;
	`1`: to the beginning of the next line;
	`2`: below. 

multi_cell()
	`0`: to the bottom right;
	`1`: to the beginning of the next line;
	`2`: below with the same horizontal offset;
	`3`: to the right with the same vertical offset.
```
And no, a non-true value doesn't necessarily indicate no line jump. This conflicts with reusing `ln=False` for staying on the same line.
So we would need a different parameter for the vertical displacement as well. Would it be too confusing to have both `ln=#` and `new_line=True` available at the same time? Maybe `add_line`/`next_line`/`trailing_nl`/whatever?

**Comment by Lucas-C** [comment]
`eol` = _"end of text"_ sounds good IMHO 😊

If we want to support all combinations of the values for `eot_x` & `eot_y` you listed, that would be 5 x 3 = 15 options.
If we want to support those 15 possible behaviours, the solution of having two distinct `eot_x` & `eot_y` parameters seems right.
But do we really want to support all those cases?
So far, I do not recall any user asking for more than the 3/4 possible options actually available with `ln`.

**Comment by gmischler** [comment]
> If we want to support those 15 possible behaviours, the solution of having two distinct `eot_x` & `eot_y` parameters seems right. But do we really want to support all those cases? So far, I do not recall any user asking for more than the 3/4 possible options actually available with `ln`.

Build it and they will come! :wink:

I'm trying to think about the most easily accessible and understandable API at the moment.
Whether there will be some fewer or some more options in the end... They don't really cost anything, do they?

**Comment by Lucas-C** [comment]
No they don't cost much :) It's all about ease of use I think.

**Comment by gmischler** [comment]
Along the same lines...

I see that `.cell()` and `._render_styled_cell_text()` have a `center=False` parameter, which when set to True overrides all other positioning and alignment settings and centers the text between the page margins. 
This is unnecessarily redundant and confusing. It clutters the code, and the user-side replacement is a trivial one-liner.
Can we pretty please get rid of that as well?

**Comment by Lucas-C** [comment]
Seems OK with me if `align="C"` does the exact same thing 😊
Go on and submit a PR ! 😉
