### ISSUE TITLE
cell() computes wrong width

### ISSUE THREAD

**Issue by mcerveny** [PyFPDF/fpdf2#351]
Something wrong between 2.5.0 -> 2.5.1 with cell() width compute (with markdown=True)

[test_2.5.1.pdf](https://github.com/PyFPDF/fpdf2/files/8197885/test_2.5.1.pdf)
[test_2.5.0.pdf](https://github.com/PyFPDF/fpdf2/files/8197886/test_2.5.0.pdf)

Testing code:
```python
import fpdf

pdf = fpdf.FPDF(orientation='portrait', unit='mm', format='A4')
pdf.add_page()
pdf.set_fill_color(255, 255, 0)
pdf.set_font('helvetica',size=10)
for rep in range(5,20):
  pdf.cell(markdown=True, txt="**" + "i"*rep + "M**")
  pdf.cell(ln=1,txt="XXX", fill=True)
for rep in range(5,20):
  pdf.cell(markdown=True, txt="" + "i"*rep + "M")
  pdf.cell(ln=1,txt="XXX", fill=True)
pdf.output('test.pdf')
```

**Comment by Lucas-C** [comment]
Thanks for reporting this @mcerveny!

I have found a fix. Commit should be merged very soon.
