### ISSUE TITLE
Tag structured pdf

### ISSUE THREAD

**Issue by henrik1348** [PyFPDF/fpdf2#355]
I want to create a tag structured pdf to improve accessibilty. I tried using html_write() and html tags but the pdf the script returns dosen't provide a tag structure at all (Only tags for images with alt_text). 

Is there a way to create a tag structured pdf using FPDF?

**Comment by Lucas-C** [comment]
Hi @henrik1348 

Thank you for opening this discussion

What have basic support for marked sequences, currently implemented through a private method:
```python
with pdf._marked_sequence(title=title, alt_text=alt_text):
    ... # insert content
```
This is used to insert image `/Title` & `/Alt` text, and to build the [document outline](https://pyfpdf.github.io/fpdf2/DocumentOutlineAndTableOfContents.html).

However `fpdf2` currently does not provide a clean, public API for users to build a propper Tagged PDF, conforming to the PDFspec. This would include a logical structure like the one in [section 14.7.6 of the PDF spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf)

**Comment by henrik1348** [comment]
Thanks a lot @Lucas-C !
I will try it out!

**Comment by Lucas-C** [comment]
Great! I'd be happy to get your feedback after you tried things out 😊

**Comment by henrik1348** [comment]
@Lucas-C 
does _marked_sequence() takes any other arguments than title and alt_text?

**Comment by Lucas-C** [comment]
Currently `_marked_sequence()` can only render structure elements with the `Figure` type,
it is hardcoded in the code: [`fpdf.py` line 2976](https://github.com/PyFPDF/fpdf2/blob/2.5.1/fpdf/fpdf.py#L2976)

This method can receive as named arguments any of the entries described in [section 14.7.2 of the PDF spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf): `iD`, `a`, `c`, `r`, `lang`, `e`, `actualText`

**Comment by Lucas-C** [comment]
Have you been able to build tagged PDFs as you wished @henrik1348?
Regarding this issue, should we close it, or would you like to keep it open as a feature request?

**Comment by henrik1348** [comment]
No, I havent. I made a workaround, using docxtpl and go from word to pdf afterwards, then I get the correct tagg structure. 
We can close it. :) Thanks for your help!
