### ISSUE TITLE
Documenting text functions and improving documentation outline

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#360]
In the context recent changes to various text functions (most recently #343 / #350) it has come up that there is no in-depth explanation of those functions and their differences (let alone the new positioning options) other than in the docstrings. Since I've modifying some of that functionality already, I probably should also add such a page, though in a seperate PR to keep things manageable.
In addition, while looking through the docs, I found that the TOC seems to have grown a lot over time without anyone adding much structure to it, which makes it quite hard to find any specific information. I tried to play around with it a bit and this is the most reasonable structure I could come up with:

* Tutorial
    * English
    * Français
    * Deutsch
    * ...
* Page Layout
    * Page Format and Orientation
    * Margins
    * Templates
    * Tables
* Text Content
    * Adding Text (new)
    * Line Breaks
    * Page Breaks
    * Text Styling
    * Unicode
    * Emojis, Symbols & Dingbats
* Graphics Content
    * Images
    * Shapes
    * Barcodes
    * Drawing
    * SVG
    * Charts & Graphs (formerly "Maths")
* PDF Features
    * Links
    * Metadata
    * Annotations
    * Presentation Mode
    * Document Outline & Table of Contents
* Processing Web Content
    * HTML
    * Web2Py
* Reading and Postprocessing
    * pdfrw
    * Borb
* Development
    * Development Guidelines
    * Logging
* API
* FAQ

Any objections when I modify it that way, or any better ideas? There are a few items that could go in several places.
Do I understand this right, that the documentation outline is defined in mkdocs.yml? Is there an easy way to test its processing locally?

**Comment by Lucas-C** [comment]
Wow, that's a great plan, thanks @gmischler !

No objection at all, I've been thinking aboutre-structuring the docs' ToC for a few months, without taking the time to do it so far. Much appreciated 😊

I think some page contents are maybe a bit outdated (`Unicode` & `Web2Py` for example) but they could be edited later on.

Go on, please submit a PR! 🙏
