### ISSUE TITLE
How to highlight text (without highlighting the entire cell)?

### ISSUE THREAD

**Issue by JDeepD** [PyFPDF/fpdf2#377]
I want to do something like this using fpdf2:

![image](https://user-images.githubusercontent.com/64089730/161375775-f9185b9c-3950-4532-afb3-a5400706114e.png)

Is it possible?

**Comment by Lucas-C** [comment]
`fpdf2` currently does not support _Text Markup Annotations_, but we already support text annotations so I think implementing those should be relatively easy. I'll have a look at this tomorrow

**Comment by Lucas-C** [comment]
I implemented this in https://github.com/PyFPDF/fpdf2/pull/378

While waiting for the next release, you can test it this way:

    pip install git+https://github.com/PyFPDF/fpdf2.git@master
