### ISSUE TITLE
fpdf2-manual.pdf: fix rendering of Hindi tutorial

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#381]
The `fpdf2` PDF manual ( <https://pyfpdf.github.io/fpdf2/fpdf2-manual.pdf> ) recently incorporated the tutorials in all languages.

However the [Hindi tutorial](https://pyfpdf.github.io/fpdf2/Tutorial-%E0%A4%B9%E0%A4%BF%E0%A4%82%E0%A4%A6%E0%A5%80.html) does not get rendered well at all.

We should find a way to configure the [mkdocs plugin used](https://github.com/PyFPDF/fpdf2/blob/2.7.3/mkdocs.yml#L64) to properly render this tutorial, maybe by specifying the font to use for this section.

Or just skip those pages from the PDF manual for now.

**Comment by gmischler** [comment]
That might turn out to be a challenge on several levels.

* Tell [mkdocs-with-pdf](https://github.com/orzih/mkdocs-with-pdf) which font you want.
* Mkdocs passing the information on to [WeasyPrint](weasyprint.org).
* WeasyPrint being able to do better than us with our issue #365.

I don't see any non-latin text in the WeasyPrint examples, and at first glance it looks like a highly automated solution with limited configurability. I think I'm not going to enter any bets either way for now...

**Comment by Lucas-C** [comment]
Damn, that sure looks to much trouble for a PDF manual.

Maybe we should go for option B then: tell `mkdocs-with-pdf` to skip this tutorial,
and just not include it in the resulting PDF.

**Comment by gmischler** [comment]
Or option C: fix #365 and do it with fpdf... :wink:

**Comment by gmischler** [comment]
@Lucas-C, now that #820 has landed, maybe we can switch to using fpdf2 itself for generating the PDF manual?
Then we could include the tutorials in all languages.

**Comment by Lucas-C** [comment]
> @Lucas-C, now that #820 has landed, maybe we can switch to using fpdf2 itself for generating the PDF manual? Then we could include the tutorials in all languages.

This seems like a big task to me, but I'm open to this if anyone want to do it! 😊

Maybe a first would be to look at how https://github.com/orzih/mkdocs-with-pdf does PDF generation,
and see how `fpdf2` could be used instead
