### ISSUE TITLE
Add a documentation page with examples on how to embed panda objects

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#393]
**Please explain your intent**
Provide documentation to users on how to generate a PDF from [Panda](https://pandas.pydata.org/) dataframes or plots

**Additional notes**
* we already provide documentation on how to include Matplotlib charts: https://pyfpdf.github.io/fpdf2/Maths.html#using-matplotlib - This new documentation section could be added on the same page
* dataframes should be rendered as [tables](https://pyfpdf.github.io/fpdf2/Tables.html)

By contributing this documentation page you, as a benevolent [FLOSS](https://en.wikipedia.org/wiki/Free/libre_and_open-source_software) developper, will provide access to the large community of fpdf2 users to a standard and useful PDF integration with a well-know library.
You will also be added into the [contributors list & map](https://github.com/PyFPDF/fpdf2#contributors-).

**Comment by iwayankurniawan** [comment]
Hi, Could you please assign this one to me? Thanks

**Comment by Lucas-C** [comment]
Sure! Done
