### ISSUE TITLE
New feature: provide support for style attributes in SVG files

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#404]
**Context**
Our current [SVG parser](https://github.com/PyFPDF/fpdf2/blob/master/fpdf/svg.py) has [some limitations](https://pyfpdf.github.io/fpdf2/SVG.html#currently-unsupported-notable-svg-features), among which the lack of support for CSS styling.
This means that the following [simple example from MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/style#example) will not be colored when embedded by `fpdf2` in a PDF document:
```svg
<rect width="80"  height="40" x="10" y="10"
      style="fill: skyblue; stroke: cadetblue; stroke-width: 2;"/>
```

**Goal**
Provide support for parsing `style="..."` attribute in SVG files and convert them to [PDF drawing primitives](https://pyfpdf.github.io/fpdf2/Drawing.html).
Some unit tests should be added covering this feature.
Once tests pass for basic SVG files, more complex SVG example files can be found there, under the GNU license: [Ghostscript examples](https://commons.wikimedia.org/wiki/Example_images#Ghostscript_examples).

---

By implementing this feature you, as a benevolent [FLOSS](https://en.wikipedia.org/wiki/Free/libre_and_open-source_software) developper, will provide access to the community of fpdf2 users to a standard and useful PDF functionality.
You will also be added into the [contributors list & map](https://github.com/PyFPDF/fpdf2#contributors-).
Moreover, by working on this feature, you will learn about PDF & SVG file formats and the lifecycle & structure of a popular Python library.

**Comment by RedShy** [comment]
Hi! I would like to work on the issue, can I work on it?
This would be my first time to contribute to an open source project and I'm excited!

I have setup my local environment with black, pylint. I have ran pytest and 10 tests failed: [Full log](https://pastebin.com/TG5xGRUH)
![](https://user-images.githubusercontent.com/24901693/167269673-3dd8a673-45ba-4229-b030-6c5c4580cb84.png)


My idea for this feature is to add a function _parse_style_ in the function _apply_styles_ in _svg.py_ that:
1. Takes the attributes and values of `style="..."`
2. Insert these key-value pairs in _svg_element.attrib_

In this way we could reuse _svg_attr_map_ that seems already to work, but maybe it needs to be expanded. It could be a good approach?

By the way, the game in PDF is really amazing, I didn't thought something like this could be possible!

**Comment by Lucas-C** [comment]
> Hi! I would like to work on the issue, can I work on it?

Sure!

>  This would be my first time to contribute to an open source project and I'm excited!

Great! And welcome 😊

> I have setup my local environment with black, pylint. I have ran pytest and 10 tests failed

Your may not have a recent enough version of Pillow.
`fpdf2` requires [Pillow>=9.1.0](https://github.com/PyFPDF/fpdf2/blob/master/setup.py#L34).
Could you run `pip freeze` to check what version of Pillow you have installed?

> It could be a good approach?

Sounds good to me! Go and try that!

> By the way, the game in PDF is really amazing, I didn't thought something like this could be possible!

Thank you! ❤️
I'm working on another one ^^

**Comment by RedShy** [comment]
Thank you for the fast response, yes I have Pillow 8.4.0, I will update it and retry the tests!
