### ISSUE TITLE
text running out of the <td><>

### ISSUE THREAD

**Issue by deepakmeena635** [PyFPDF/fpdf2#405]
Describe the bug
1. the line in second td goes beyond the page
2. <img width="698" alt="image" src="https://user-images.githubusercontent.com/37202245/165628054-0f4c59f8-ae3b-4f0e-af9d-70648961b2a6.png">
3. on using <font color="some color"  > the part enclosed resets to the start of the td
<img width="698" alt="image" src="https://user-images.githubusercontent.com/37202245/165628629-56193d1c-8803-4026-b1ec-0e99d7f4a99a.png">

4. on using bgcolor the text in the  entire page from the start of the first occurence of tr with bg color becomes of the same color

you can ignore the last one, i'll raise that as another later issue if needed 
**Error details**
No Exceptions are raised

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python

from fpdf import FPDF

    from fpdf import FPDF, HTMLMixin

    class myPDF(FPDF, HTMLMixin):
        pass
    o = myPDF()
    o.add_page()

    reds, rede = "<<REDS>>", "<<REDE>>" ##TODO: MAKE CONDITIONAL TO ARGUMENTS 
    greens, greene = "<<GREENS>>", "<<GREENE>>"
    def  toHtml(s1,s2):
        res =  f"""<tr>
                        <td width="50%">{s1}</td>
                        <td width="50%">{s2}</td>
                    </tr>"""
        if reds in s1 or greens in s2:
            res =  f"""<tr >
                            <td   width="50%">{s1}</td>
                            <td    width="50%">{s2}</td>
                        </tr>""".replace(reds, 
                                        "<font color=\"red\">"
                                ).replace(rede,
                                        "</font>"
                                ).replace(greens, 
                                        "<font color=\"green\">"
                                ).replace(greene,
                                        "</font>"
                                )
        return res

    pre_file = f"""this is the {reds}first {rede} line
    this is the second line
    this is a really long third {reds} line that i dont know for {rede} some reason goes beyond the page width"""
    post_file = f"""this is the {greens}first {greene} line
    this is the second line
    this is a really long third {greens} line that i dont know for {greene} some reason goes beyond the page width"""
    
    pdfFile = "".join([toHtml(l1,l2) for l1,l2 in zip(pre_file.split('\n'), post_file.split('\n'))])
    pdfFile = f"<table>{pdfFile}</table>"

    o.set_font('helvetica')
    o.set_font_size(14)
    o.write_html(pdfFile)
    o.output("demo2.pdf",)

```

**Environment**
* OS (Windows, Mac OSX, Linux flavour...): Mac
* Python version: 3.9 
* `fpdf2` version used : master branch

**Comment by Lucas-C** [comment]
Hi @deepakmeena635
Thank you for taking the time to report this.

Are you aware of the current limitations of the HTML renderer?
https://pyfpdf.github.io/fpdf2/HTML.html#supported-html-features

Typically, as mentioned in the docs, multi-lines cells (= automatic line wrapping) are not supported: https://github.com/PyFPDF/fpdf2/issues/91

Do you really need to work with HTML?
Otherwise I would recommend to use the [multi_cell()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.multi_cell) method that will provide automatic line wrapping.
You can also find recipes on building tables in the documentation:
https://pyfpdf.github.io/fpdf2/Tables.html

Also, I don't understand this sentence:
> on using the part enclosed resets to the start of the td

**Comment by deepakmeena635** [comment]
Sure, please close this
