### ISSUE TITLE
ValueError: Invalid value for parameter "new_x" (0),must be instance of Enum XPos

### ISSUE THREAD

**Issue by feiticeir0** [PyFPDF/fpdf2#413]
Describe the bug

**Error details**
ValueError: Invalid value for parameter "new_x" (0),must be instance of Enum XPos

**Minimal code**
This is straight taken from the tutorial 2 for Header and Footer
```python
from fpdf import FPDF


class PDF(FPDF):
    def header(self):
        # Rendering logo:
        self.image("../docs/fpdf2-logo.png", 10, 8, 33)
        # Setting font: helvetica bold 15
        self.set_font("helvetica", "B", 15)
        # Moving cursor to the right:
        self.cell(80)
        # Printing title:
        self.cell(30, 10, "Title", 1, 0, "C")
        # Performing a line break:
        self.ln(20)

    def footer(self):
        # Position cursor at 1.5 cm from bottom:
        self.set_y(-15)
        # Setting font: helvetica italic 8
        self.set_font("helvetica", "I", 8)
        # Printing page number:
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", 0, 0, "C")


# Instantiation of inherited class
pdf = PDF()
pdf.add_page()
pdf.set_font("Times", size=12)
for i in range(1, 41):
    pdf.cell(0, 10, f"Printing line number {i}", 0, 1)
pdf.output("tuto2.pdf")

```

**Environment**
* Oracle Linux EL 8 - Kernel 5.4.17-2136.304.4.1-el8uek
* Python 3.6.8
* `fpdf2` 2.5.2

**Comment by abishek** [comment]
I moved to 2.5.0 to get past this. `new_x` and `new_y` are parameters added to `cell` method from what I understand in the code. So we need to update the code to include the parameters or go to a slightly older version until we can fix it properly. The parameters replace the previously used `ln` parameter. 

source: https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.cell

**Comment by feiticeir0** [comment]
I will then move to a lower version until this gets fixed. 
Thank you

**Comment by abishek** [comment]
oh, but I don't think it's an issue. It is a breaking change. We have to update the codebase to work with the new API :-)

**Comment by Lucas-C** [comment]
Indeed, this deprecation was announced in `v2.5.2`: https://github.com/PyFPDF/fpdf2/blob/master/CHANGELOG.md#deprecated-1

I'm sorry the tutorial is outdated, I will fix this asap.

You can still use `ln` for now, but you will have to pass arguments by name:
```python
self.cell(30, 10, "Title", 1, ln=0, align="C")
```
or:
```python
self.cell(w=30, h=10, txt="Title", border=1, ln=0, align="C")
```

Note however that `ln` will be removed at some point, so we recommend to all users to switch to the new `new_x` / `new_y` syntax.

Ping @gmischler: I don't think we planned this impact regarding `FPDF.cell` usage with arguments passed by value 😔

**Comment by Lucas-C** [comment]
The new release has landed:
* https://github.com/PyFPDF/fpdf2/releases/tag/2.5.4
* https://pypi.org/project/fpdf2/#history

**Comment by gmischler** [comment]
@feiticeir0 & @abishek : 
As you both have just found out, using all positional arguments in any non-trivial method call is often not a particularly good idea.
Your own code ends up not as readable as it could be,  and if anything in the method changes, chances of things breaking are much higher than when using keyword arguments.

Now in hindsight, squeezing the new parameters into the middle of the list wasn't a good idea on my end, and the fix of moving them to the end is correct.
At the time, I simply couldn't imagine that anyone would want to call that method with positional arguments, and I appologize for the shortsightedness... Consequently, I also didn't expect any examples in the documentation to do it that way, and thus only searched and replaced all the cases that used the explicit `ln=#`.

@Lucas-C , are you already working on changing the tutorials to a more appropriate coding practise, or should I do that?

**Comment by Lucas-C** [comment]
PR https://github.com/PyFPDF/fpdf2/pull/414 already included an updated ot the tutorial scripts 😊

**Comment by feiticeir0** [comment]
Thank you all for the replies. 
I was searching for BARCODES in fpdf and landed on fpdf2. I did install it and, after seeing the tutorial using the same functions and arguments as the fpdf, did not change anything on the code and I got the original error. 

I'll check the new tutorial and change the code accordingly  ! 
Thank you

**Comment by Lucas-C** [comment]
@allcontributors please add @feiticeir0  for bug
