### ISSUE TITLE
Error :    fpdf.errors.FPDFException: A page cannot be added on a closed document, after calling output()

### ISSUE THREAD

**Issue by Namyalg** [PyFPDF/fpdf2#425]
I am generating PDFs in python on a Flask server using `fpdf2`, and encounter this when I invoke a GET request to create the PDF consecutively. Is there a function to clear the buffer ?

`raise FPDFException( fpdf.errors.FPDFException: A page cannot be added on a closed document, after calling output() `

**Comment by Lucas-C** [comment]
> Is there a function to clear the buffer ?

Nope. You need to either:

* create a `FPDF` instance for every request
* if you want to reuse the PDF for several calls, store `bytes(pdf.output())` in shared variable, do not reuse a `FPDF` instance

You did not provide any code reproducing your issue, as suggested in the GitHub issue template, so I won't be able to help you much more...

**Comment by Namyalg** [comment]
Okay, thank you for the information
The skeleton of the code is this, where `function_to_generate_pdf()` is called multiple times, and on the second call it returned the above message

```
from fpdf import FPDF

pdf = FPDF()

def function_to_generate_pdf():
    ....
```

**Comment by Namyalg** [comment]
I was thinking of a class -based implementation where `pdf = FPDF()` is called in the constructor

**Comment by Namyalg** [comment]
> Are you using our recipe regarding `fpdf2` integration with Flask? _cf._ https://pyfpdf.github.io/fpdf2/UsageInWebAPI.html#flask

I used `send_file` to send the pdf

**Comment by Lucas-C** [comment]
> The skeleton of the code is this, where function_to_generate_pdf() is called multiple times, and on the second call it returned the above message

Beware of state sharing inside a Flask application...
Check this: https://stackoverflow.com/a/23417696/636849

> I was thinking of a class -based implementation where pdf = FPDF() is called in the constructor for each request to generate the PDF

Why not! The `FPDF` class is designed to be "subclassable".
You could do something like this:
```python
from fpdf import FPDF

class PDF(FPDF):
    def build(self):
	      self.add_page()
	      self.set_font("Helvetica", size=24)
	      self.cell(txt="hello world")
	      return self.output()

@app.route("/")
def hello_world():
    pdf = PDF()
    response = make_response(pdf.build())
    response.headers["Content-Type"] = "application/pdf"
    return response
```

**Comment by Namyalg** [comment]
Yep, it does
Tested the sample, it's exactly what I wanted!

**Comment by Namyalg** [comment]
Will including the above sample in the documentation be a good idea ?

**Comment by Lucas-C** [comment]
The one with the subclass?
IMHO it doesn't really bring much over a function-based approach.
But I will add a mention about FPDF instance reuse between calls, that's a good idea!

Closing this now

**Comment by Namyalg** [comment]
Sure, that will definitely assist use cases like mine.
