### ISSUE TITLE
Allow to draw rectangles with round corners by introducing a new `round_corners` optional argument to FPDF.rect

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#427]
The idea comes from one of @digidigital recipes: https://github.com/digidigital/Extensions-and-Scripts-for-pyFPDF-fpdf2/tree/main/roundedCorners (_cf._ #274)

There this some usage example once implemented:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.rect(x=100, y=100, w=400, h=200, round_corners=True)
pdf.rect(x=100, y=600, w=400, h=200, round_corners=("TOP_LEFT", "BOTTOM_RIGHT"))
```

`round_corners` would allow two possible values: a boolean OR an iterable of `Corner` (a subclass of [CoerciveEnum](https://pyfpdf.github.io/fpdf2/fpdf/enums.html#fpdf.enums.CoerciveEnum)) or string values that can be coerced to `Corner` enum values.

By implementing this feature you, as a benevolent [FLOSS](https://en.wikipedia.org/wiki/Free/libre_and_open-source_software) developper, will provide access to the large community of fpdf2 users to a useful PDF functionality.
As a contributor you will get review feedbacks from maintainers & other contributors, and learn about the lifecycle & structure of a Python library on the way.
You will also be added into the [contributors list & map](https://github.com/PyFPDF/fpdf2#contributors-).

**Comment by gonzalobarbaran** [comment]
Hi! I'm currently working on this feature. I already added the `round_corners` parameter that accept a boolean and i'm trying to figure out how to add the iterable of `Corner`.  I hope to finish as soon as posible

**Comment by Lucas-C** [comment]
Great! If ever you have any question regarding how to implement this, or how `fpdf2` works, feel free to ask 😊
