### ISSUE TITLE
Provide documentation on how to add IPTC metadata to PDF files

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#437]
We currently have some documentation on how to set PDF metadata on a file generated with `fpdf2`: https://pyfpdf.github.io/fpdf2/Metadata.html

However, this does **not** set IPTC metadata, aka _Windows File Properties_.
Those can apparently be set using the [IPTCInfo3](https://pypi.org/project/IPTCInfo3/) package: https://stackoverflow.com/questions/57421099/accessing-windows-file-tags-metadata-in-python

The goal of this task is to add a new section in [docs/Metadata.md](https://github.com/PyFPDF/fpdf2/blob/master/docs/Metadata.md) that explains ho to set IPTC metadata on a file generated with `fpdf2` (potentially using `IPTCInfo3` if that works).

By implementing this feature you, as a benevolent [FLOSS](https://en.wikipedia.org/wiki/Free/libre_and_open-source_software) developper, will provide access to the large community of `fpdf2` users to a useful functionality.
As a contributor you will get review feedbacks from maintainers & other contributors, and learn about the lifecycle & structure of a Python library on the way.
You will also be added into the [contributors list & map](https://github.com/PyFPDF/fpdf2#contributors-).

**Comment by pramitsingh0** [comment]
Hi. I am interested in working on this issue. I installed IPTCInfo3 package and tested it and found that it can only be used for writing metadata to image files(jpeg/jpg). If I am not wrong, you want to add metadata to pdf files right?

**Comment by Lucas-C** [comment]
Thank you for your research @pramitsingh0

`fpdf2` can already sets some "internal" PDF metadata on the files it generates:
https://pyfpdf.github.io/fpdf2/Metadata.html

But neither `fpdf2` nor `PyFPDF2` can set the content of _Windows File Properties_.
In fact, those properties may not be IPTC metadata at all, I may have mixed things up 😄
https://en.wikipedia.org/wiki/IPTC_Information_Interchange_Model

I'm going to close this issue then,
but if ever you see anything useful to document @pramitsingh0,
feel free to open a discussion / issue / PR!
