### ISSUE TITLE
Version 2.5.1 breaks manual line breaks via newline character

### ISSUE THREAD

**Issue by ryanshow** [PyFPDF/fpdf2#455]
It seems that version 2.5.1 no longer injects line breaks when the `\n` newline character is encountered with the write() or multi_cell() function.

I have an application generating PDF files without issue using version 2.5.0, but upgrading to version 2.5.1 or above breaks all the formatting in my generated documents.

Here's a basic example. I haven't tested this, but it's essentially the relevant parts of my codebase:

```python
lines = ['Hello\n', 'Sweet\n', 'World\n']
pdf = FPDF('P', 'in', 'Letter')
pdf.set_auto_page_break(False)
pdf.add_page()
pdf.set_font('Courier', '', 11)
pdf.set_margins(0.54, 0)
pdf.write(0.01, '\n')
for line in lines:
    pdf.write(0.17, line)

doc = pdf.output(dest='S')
```

**Comment by Lucas-C** [comment]
For reference, there is the output of your code with `v2.5.0`:
<img width="289" alt="issue-455-fpdf2 5 0" src="https://user-images.githubusercontent.com/925560/173185696-d7c1f24a-e40c-4350-8e66-c11dc052568f.png">

And here is the output with `v2.5.1` to `v2.5.4`:
<img width="663" alt="issue-455-fpdf2 5 4" src="https://user-images.githubusercontent.com/925560/173185726-98d4398d-9650-4a9f-87be-619ac58926e3.png">

**Comment by gmischler** [comment]
Thanks for reporting this.

The effect is slightly more specific than described, in that only a '\\n' at the very end of the supplied string will get ignored, any '\\n' somewhere else would still have the desired effect.
I just submitted PR #456 that should fix this.

**Comment by Lucas-C** [comment]
#456 was merged, so this should be fixed in the next release

**Comment by ryanshow** [comment]
Thank you for the quick response on this!
