### ISSUE TITLE
Tables Documentation Out of Date?

### ISSUE THREAD

**Issue by kingfredrickvi** [PyFPDF/fpdf2#457]
I am trying to create a table following https://pyfpdf.github.io/fpdf2/Tables.html

**Error details**
```
Traceback (most recent call last):
  File "pdfgen2.py", line 37, in asdf
    border=1, new_x="RIGHT", new_y="TOP", max_line_height=pdf.font_size)
  File "/home/asdf/fpdf/fpdf.py", line 265, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/asdf/fpdf/fpdf.py", line 2815, in multi_cell
    f'Invalid value for parameter "new_x" ({new_x}),'
ValueError: Invalid value for parameter "new_x" (RIGHT),must be instance of Enum XPos
```

**Minimal code**
```python
from fpdf import FPDF

pdf = FPDF()

pdf.multi_cell(col_width, line_height, Title,
            border=1, new_x="RIGHT", new_y="TOP", max_line_height=pdf.font_size)
```

**Possible Fix**
I read through the pull request from April ( https://github.com/PyFPDF/fpdf2/pull/350/files/855b905ddeb638d88481473f212e6a111387f911#diff-b44ed7a29a52f08d574d9d8a3ab66e269455682942f45dc33cf55d85d688a341 ) and making the following change to my code appeared to fix my issue:

```python
from fpdf import FPDF, XPos, YPos

pdf = FPDF()

pdf.multi_cell(col_width, line_height, Title,
            border=1, new_x=XPos.RIGHT, new_y=YPos.TOP, max_line_height=pdf.font_size)
```

Thanks

**Comment by Lucas-C** [comment]
Sorry for the inconvenience: the documentation matches the state of the latest version of the code on this repo, unreleased yet.

The code you used in the end is perfectly valid, and will continue to be valid onwards.

You can test the latest, unreleased, version of `fpdf2` with this command:

    pip install git+https://github.com/PyFPDF/fpdf2.git@master

I'm planning to perform a release before the end of the month.

**Comment by Lucas-C** [comment]
fpdf2 [v2.5.5](https://github.com/PyFPDF/fpdf2/releases/tag/2.5.5) has been released

Closing this now
