### ISSUE TITLE
fpdf2 default table example not working

### ISSUE THREAD

**Issue by mangoez** [PyFPDF/fpdf2#471]
I'm just learning how to use fpdf but it seems that your examples are not working?

Describe the bug

**Error details**
AttributeError                            Traceback (most recent call last)
Input In [11], in <cell line: 15>()
     13 pdf.set_font("Times", size=10)
     14 line_height = pdf.font_size * 2.5
---> 15 col_width = pdf.epw / 4  # distribute content evenly
     16 for row in data:
     17     for datum in row:

AttributeError: 'FPDF' object has no attribute 'epw'

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF

data = (
    ("First name", "Last name", "Age", "City"),
    ("Jules", "Smith", "34", "San Juan"),
    ("Mary", "Ramos", "45", "Orlando"),
    ("Carlson", "Banks", "19", "Los Angeles"),
    ("Lucas", "Cimon", "31", "Saint-Mahturin-sur-Loire"),
)

pdf = FPDF()
pdf.add_page()
pdf.set_font("Times", size=10)
line_height = pdf.font_size * 2.5
col_width = pdf.epw / 4  # distribute content evenly
for row in data:
    for datum in row:
        pdf.multi_cell(col_width, line_height, datum, border=1,
                new_x="RIGHT", new_y="TOP", max_line_height=pdf.font_size)
    pdf.ln(line_height)
pdf.output('table_with_cells.pdf')
```
If you don't know how to build a minimal reproducible example, please check this tutorial: https://stackoverflow.com/help/minimal-reproducible-example

**Environment**
* Windows 11
* Python version: 3.8.3
* `fpdf2` version: latest

**Comment by mangoez** [comment]
Apologies, when I installed fpdf I did
pip install fpdf and not fpdf2

**Comment by Lucas-C** [comment]
No problem, glad you you figured it out
