### ISSUE TITLE
Kannada characters are not displaying properly with Fpdf2 and Python3

### ISSUE THREAD

**Issue by gksathyarao** [PyFPDF/fpdf2#474]
With fpdf2, Kannada characters are not displayed properly. Characters are jumbled . Looks to be issue with all Indian languages we use Half characters lot in Indian languages . Normally Half characters are written below the characters 
Code example:

**Minimal code**
```python
from fpdf import FPDF
                   
pdf = FPDF()
pdf.add_page()
pdf.add_font('kan','','/Users/sathyarao/Library/Fonts/AnekKannada-VariableFont_wdth,wght.ttf')
pdf.set_font("kan",size=30)
ktext='ಕನ್ನಡ ರಾಜ್ಯ ಹೇಮ್ಮೇಯ ನಾಡು'
pdf.cell(150, 30, txt = ktext , align='c')
pdf.ln(30)
pdf.output('font.pdf')
print(ktext)
```

Correct way to display it is "ಕನ್ನಡ ರಾಜ್ಯ ಹೇಮ್ಮೇಯ ನಾಡು" but in PDF it shows/display as 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/60440667/180146436-3344aaa0-8772-4316-a55c-843ce176774e.png">

I tried  most of  Kannada/UNi code fonts  and issue reproduces in all types fonts.  Looks to issue with fpdf2
Please fix at the earliest 

**Environment**
* OS Mac OS
* Python version 3.10.2
* `fpdf2` version used - latest ( not sure how check latest version )

**Comment by gmischler** [comment]
Thanks for reporting.

The reason why this happens is explained in issue #365. Yes, all indic scripts have this problem, as will any other scripts with mandatory ligatures.
I'm not aware of any open source PDF libary that has solved this. If you happen to know one, please tell us so we can check out how they've done it.

Someone is currently working on #418, which will build the foundation for an eventual fix, but please don't expect any wonders in the short or even intermediate term.
Of course, if someone with experience in the field wants to contribute, things might go a bit faster...

**Comment by Lucas-C** [comment]
@ksathyarao : are you still facing this problem?
Do you still have questions / need help or can this issue be closed?

**Comment by Lucas-C** [comment]
I guess that after 1 month since the initial anwer, this can be closed.
Feel free to reopen another issue if needed!

**Comment by gmischler** [comment]
Fixed with #820.

**Comment by Prasaderp** [comment]
Hi, Do we have a solution to @gksathyarao. Looks to be issue with all Indian languages we use Half characters lot in Indian languages .??

I am also facing the same issue. Is there any library available for this issue for Indian Languages? @gmischler

**Comment by andersonhc** [comment]
> Hi, Do we have a solution to [@gksathyarao](https://github.com/gksathyarao). Looks to be issue with all Indian languages we use Half characters lot in Indian languages .??
> 
> I am also facing the same issue. Is there any library available for this issue for Indian Languages? [@gmischler](https://github.com/gmischler)

fpdf2 supports Indian languages if you use text shaping. See the [documentation here])https://py-pdf.github.io/fpdf2/TextShaping.html)

**Comment by Prasaderp** [comment]
@andersonhc  Thanks. I solved it using PyMuPDF library itself. I was using OCR extraction and other stuff which is not supported by fpdf2 and also PyMuPDF library supports Indic languages.
