### ISSUE TITLE
Bad Font indexing after local context

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#475]
**Error details**
After several `.local_context()` calls and font changes, fpdf seems to get confused about which is the currently active font, and either "forgets" to include all the necessary characters, or maybe misplaces them in other ways.

**Minimal code**

```python
import fpdf

pdf = fpdf.FPDF()
pdf.add_page()
pdf.add_font(family="Calibri", style="",
            fname="c:/windows/fonts/calibri.ttf")
pdf.add_font(family="Calibri", style="B",
            fname="c:/windows/fonts/calibrib.ttf")

with pdf.local_context():
    pdf.set_font('Calibri', 'B', 10)
    pdf.cell(txt='ABCDEFGH', new_x='LEFT', new_y='NEXT')

pdf.set_font('Calibri', '', 10)
pdf.cell(txt='IJKLMNOP', new_x='LEFT', new_y='NEXT')

with pdf.local_context():
    pdf.set_font('Calibri', 'B', 10)
    pdf.cell(txt='QRSTUVW', new_x='LEFT', new_y='NEXT')

pdf.set_font('Calibri', '', 10)
pdf.cell(txt='XYZ012abc,-', new_x='LEFT', new_y='NEXT')
pdf.cell(txt='3,7E-05', new_x='LEFT', new_y='NEXT')

pdf.output('test.pdf')
```
**Result**

![Unbenannt](https://user-images.githubusercontent.com/17468844/181003126-f6a760be-18bf-443a-bc8c-31d8f5b82903.PNG)

Interestingly, the first context switch doesn't have any visible effect, but the bug only gets triggered after the second one.
Apparently fpdf always includes digits and a small number of characters (including the "b") on `.add_font()`.
In the last line, the "E" is replaced by an "M". At first I thought it was trying to find glyphs in the wrong font, but the ones present (including the incorrectly replaced one) have the correct weight, so it's probably incorrectly indexing the right font.

I don't have qpdf installed here at the moment, so I haven't looked in detail at the PostScript output yet.

**Environment**
* current release 2.5.5

**Comment by gmischler** [comment]
Just had an inspiration, and a quick test confirmed the suspicion:
The cause of this bug is that `self.current_font` ist not reset to the previous value after a local context.
Should this actually be included in the context stack?

On that front, I also noticed that there are competing property definitions of `.font_size_pt` in fpdf.py and graphics_state.py.
In addition, since `.font_size` and `font_size_pt` are just different representations of the same thing, only one of them should really get stored, and the other one converted automatically.

And yet another weirdness I stumbled across: In `._do_underline()`, a `current_font` argument may be supplied. If it isn't given, it igets replaced with `self.current_font`. But after that, only values from `self.current_font` are actually used. I suspect that this is not what was really intended.

**Comment by Lucas-C** [comment]
>  Should this actually be included in the context stack?

We could, yes.
If I understand correctly, your original problem is not really a bug, it's just that `.current_font` is not included in a local context at the moment.

> On that front, I also noticed that there are competing property definitions of .font_size_pt in fpdf.py and graphics_state.py.

You're right, `font_size_pt` should be removed from `GraphicsStateMixin` as it now a property of the `FPDF` class that refers to `.font_size`.

> And yet another weirdness I stumbled across: In ._do_underline(), [...] I suspect that this is not what was really intended.

You are totally right!

Would you like to submit a PR regarding those points?
