### ISSUE TITLE
'DeviceRGB' object has no attribute 'pdf_repr'

### ISSUE THREAD

**Issue by thaicxx** [PyFPDF/fpdf2#484]
I was using the fpdf2 library to generate some pdf files after running a SQL script for a while in py_spark environment. But after doing some updates, I came across a new error msg: 'DeviceRGB' object has no attribute 'pdf_repr' while using the add_page() function in offset_rendering().
Is this a bug? 

**Code (tried to minimize as much as possible)**

#!/usr/bin/env python
# coding: utf-8 
# Type: py_spark

spark.sparkContext.addPyFile("fpdf2.tgz")

import fpdf
import json
import pyspark.sql
import numpy as np
from fpdf import FPDF, XPos, YPos
from minio import Minio
from os.path import exists
from pathlib import Path
from pyspark.sql.functions import lit
from pyspark.sql.functions import udf,col
from pyspark.sql.types import BooleanType

class PDF_TEST(FPDF):
    
    _minio_instance = None
    _regular_txt_size = 10
    _session_title_txt_size = 11
    
    def __init__(self, order_id, defense, heightcheck: bool=False, pagesize: tuple=(210, 5000)):
        self.order_id = order_id
        self.biz = 'fintech'
        self.heightcheck = heightcheck
        self.filename = order_id + '.pdf' if not heightcheck else order_id + '_heightcheck.pdf'
        self.filename_internal = order_id + '_internal.pdf'
        self.defense = defense
        FPDF.__init__(self, orientation='P', unit='mm', format=pagesize)

    @classmethod
    def minio_connection(instance):
        if instance._minio_instance is None:
            GIFT_ACCESS_KEY = '${GIFT_DISP_DEF_ACCESS_KEY}'
            GIFT_SECRET_KEY = '${GIFT_DISP_DEF_SECRET_KEY}'
            instance._minio_connection = Minio('{intra_website}',
                                access_key=GIFT_ACCESS_KEY,
                                secret_key=GIFT_SECRET_KEY,
                                secure=True)
        return instance._minio_connection
        
    def footer(self):
        self.set_text_color(0)
        self.set_fill_color(r=238, g=238, b=238)
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('Courier', '', 8)
        # Page number
        self.set_x(-210)
        self.cell(10, 10, txt='', fill=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.cell(120, 10, txt='Document', fill=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.cell(0, 10, txt='1', border=0, align='R', fill=1)
        self.cell(10, 10, txt='', fill=1, new_x=XPos.RIGHT, new_y=YPos.TOP)

    def add_wallet_history(self):
        if 'wallet_history' in self.defense:
            
            #Column widths
            datewidth = 33
            typewidth = 40
            amountwidth = 12
            instituitionwidth = 45
            benefitiarywidth = 47.5
            
            #Table cell height
            cell_height = 5
            
            def print_table_header(pdf):
                #Header font definition
                pdf.set_font('Courier', 'B', 8)
                pdf.set_fill_color(r=191, g=54, b=12)
                pdf.set_text_color(255)
                #Header printing
                pdf.cell(w=5, h=cell_height, txt='', border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L', fill=0)
                pdf.cell(w=5, h=cell_height, txt='', border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L', fill=0)
                pdf.ln(cell_height)
            
            def print_caput(pdf, selfparams):
                #Add title
                pdf.ln(5)
                pdf.set_font('Arial', 'B', selfparams._session_title_txt_size)
                pdf.set_text_color(r=191, g=54, b=12)
                pdf.cell(w=150, h=8, txt='test', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                #Explanatory paragraph
                pdf.set_font('Arial', '', selfparams._regular_txt_size)
                pdf.set_text_color(0)
                paragraph = 'another test'
                pdf.multi_cell(0, 5, paragraph)
                pdf.ln(5)
            
            #Control page breaking
            with self.offset_rendering() as dummy:
                print_caput(dummy, self)
                dummy.cell(h=25, w=dummy.epw/2)
            if dummy.page_break_triggered:
                self.add_page()
            print_caput(self, self)
            print_table_header(self)
            
            #Sort transactions by date
            transactions = sorted(self.defense["wallet_history"], key=lambda d: d['create_time'])
            
            def print_transaction(pdf, transaction, fill, selfparams):
                pdf.set_font('Courier', '', 7)
                pdf.set_text_color(0)
                sku = transaction['sku']
                #Left padding
                pdf.cell(w=5, h=cell_height, txt='', border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L', fill=0)
                pdf.set_fill_color(r=255, g=204, b=188) if fill else pdf.set_fill_color(r=251, g=233, b=231)
                #Transaction Date
                pdf.cell(w=datewidth, h=cell_height, txt=transaction['create_time'].upper(), border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L', fill=True)
                #SKU (Transaction type)
                pdf.cell(w=typewidth, h=cell_height, txt='testin', border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L', fill=True)
                #Amount
                pdf.cell(w=amountwidth, h=cell_height, txt='{:.2f}'.format(transaction['amount']), border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='R', fill=True)
                pdf.cell(w=2.5, h=cell_height, txt='', border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L', fill=1) # add some padding after amount column
                #Instituition and benefitiary
                instituition = ''
                benefitiary = ''
                if sku == 'xpto':
                    if 'payee'  in transaction['order_details']: instituition = transaction['order_details']['payee']
                    if 'drawee' in transaction['order_details']: benefitiary = transaction['order_details']['drawee']
                pdf.cell(w=instituitionwidth, h=cell_height, txt=instituition.upper(), border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L', fill=True)
                pdf.cell(w=benefitiarywidth, h=cell_height, txt=benefitiary.upper(), border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L', fill=True)
                #Right padding
                pdf.cell(w=5, h=cell_height, txt='', border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L', fill=0)
                pdf.ln(cell_height)
            
            fill = False
            for transaction in transactions:
                with self.offset_rendering() as dummy:
                    print_transaction(dummy, transaction, fill, self)
                if dummy.page_break_triggered:
                    self.add_page()
                    self.ln(5)
                    print_table_header(self)
                print_transaction(self, transaction, fill, self)
                fill = not fill

    #upload a file
    def upload_file(self, filemode='E'):
        #filename: E external I for Internal
        if filemode == 'I':
            file = self.filename_internal
        else:
            file = self.filename
        #generate file
        minioClient = PDF_TEST.minio_connection()
        with open(file, 'rb') as file_data:
            file_stat = os.stat(file)
            minioClient.put_object('testing', '${GIFT_DISP_DEF_SUBDIR}' + file, file_data, file_stat.st_size)
    
    #generate a test file
    def test_report(self, output: bool=True, upload: bool=True, deletefiles: bool=True, outputdir: str=''):

        self.alias_nb_pages()
        self.add_page()
        self.add_wallet_history()
        
        required_page_height = self.get_y()
        
        if(output):
            if(outputdir!=''):
                Path(outputdir).mkdir(parents=True, exist_ok=True)
                outputdir = './' + outputdir + '/'
            self.output(outputdir + self.filename)
            if(upload and not self.heightcheck): self.upload_file()
            if(deletefiles): shutil.rmtree(self.order_id)

        return required_page_height

def check_valid_json(jsoninput):
  try:
    json.loads(jsoninput, strict=False)
  except ValueError as e:
    return False
  return True

#method call
if __name__ == '__main__':

    #Initialize spark session
    spark = SparkSession \
        .builder \
        .enableHiveSupport() \
        .getOrCreate()

    #Run the query to get json data
    query = """
    select {db}.order_id, {db}.document_info
    from {db}
    """.
    json_test = spark.sql(query)

    #Check if any malformed json
    udf_check_json = udf(lambda jsoninput:check_valid_json(jsoninput), BooleanType())
    json_test  = json_test.withColumn("is_valid_json", udf_check_json(col("document_info")))

    #Log with malformed JSON
    spknot = udf(lambda x:not(x), BooleanType())
    malformed_json = json_test.filter(spknot("is_valid_json"))
    [print("Warning: malformed JSON, skipping order_id {t}.".format(t = r.order_id)) for r in malformed_json.toLocalIterator()]
     json_test =  json_test.filter(col("is_valid_json"))
     json_test.show()

    #Generate documents
    def generate_docs(order_id, document_info):
        pdf = PDF_TEST(order_id=order_id, defense=document_info, pagesize=(210, 297))
        pdf.test_report(output=True, upload=True)
        print('Test order ' + order_id + ' completed.')

    [generate_docs(d.order_id, json.loads(d.document_info, strict=False)) for d in  json_test.toLocalIterator()]

**Error Output**

Traceback (most recent call last):
  File "main.py", line 215, in <module>
    [generate_docs(d.order_id, json.loads(d.document_info, strict=False)) for d in json_test.toLocalIterator()]
  File "main.py", line 215, in <listcomp>
    [generate_docs(d.order_id, json.loads(d.document_info, strict=False)) for d in json_test.toLocalIterator()]
  File "main.py", line 213, in generate_docs
    pdf.test_report(output=True, upload=True)
  File "main.py", line 168, in test_report
    self.add_wallet_history()
  File "main.py", line 147, in add_wallet_history
    self.add_page()
  File "/{hadoop}/fpdf/fpdf.py", line 813, in add_page
    self._out(fc.pdf_repr().lower())
**AttributeError: 'DeviceRGB' object has no attribute 'pdf_repr'**

**Environment**

* OS (Mac OSX)
* Python version: 3
* PySpark Version: 2.4
* `fpdf2` (not sure what version)

**Comment by Lucas-C** [comment]
Glad you found a solution to your original problem.
I received the initial code in a GitHub notification email.

I can other face the same error, could you just mention what was the source of the problem ? 😊

**Comment by thaicxx** [comment]
Hey @Lucas-C I was having an error after I updated my code to have page breaks > more especifically while using the add_page() function in offset_rendering() - the output was **_'DeviceRGB' object has no attribute 'pdf_repr'_**

 **with self.offset_rendering() as dummy:
            #print_caput(dummy, self)
            dummy.cell(h=25, w=dummy.epw/2)
        if dummy.page_break_triggered:
            self.add_page()
        #print_caput(self, self) **

Aso, if you could please remove my previous comments with my code. I shared some personal company property.
Thank you

**Comment by Lucas-C** [comment]
> Aso, if you could please remove my previous comments with my code. I shared some personal company property.

Sure, I removed the original first 2 revions from your original post

**Comment by thaicxx** [comment]
@Lucas-C Thank you very much.
I actually still haven't found a solution for the problem, are you familiar with this error?

**Comment by Lucas-C** [comment]
> I actually still haven't found a solution for the problem, are you familiar with this error?

No, sorry.
But if you provide some minimal code to reproduce the error,
I'd be happy to help you and maybe solve a the bug if there is one.
