### ISSUE TITLE
White border on right and bottom side & arabic script fix

### ISSUE THREAD

**Issue by semaeostomea** [PyFPDF/fpdf2#487]
I don't think it's necessarily a bug and might have to do with how firefox renders pdfs so I'm putting it here as a question

I wanted to add a background and I couldn't find any other function to do this _(if there is one, please tell me, otherwise I'd be happy to contribute once I've added a few customizations to it and figured out how pull requests work)_ so I overwrote the add_page() function.
in short, to determine the coordinates and apply the color: `self.rect(0, 0, self.w, self.h, style='F')`

When opening it in firefox, you can see a white border at the bottom and sometimes the right side as seen in the screenshot below
![Screenshot 2022-08-16 124923](https://user-images.githubusercontent.com/100974908/184868826-cb6132c6-787c-496e-8f59-09600161234c.png)
this doesn't happen when opening it with AdobeAcrobat
 
but: it gets fixed when adding some extra space to the rectangle that gets drawn, which is why I'm not sure it's actually a firefox bug
so when I use `self.rect(0, 0, self.w+2, self.h+3, style='F')` there's no white border anymore

I also tried googling for this as a firefox issue but everything I found was about regular borders all around

On a side note:
I know you're working on adding support for scripts like Devanagari, Arabic, etc. at the moment, but would it be possible to add a short code snippet to the documentation (below the info that they're not supported currently) for people that encounter this problem with the arabic script? Just so they know that there actually _is_ a temporary fix till you've added support?
```
from arabic_reshaper import reshape
from bidi.algorithm import get_display

some_text = 'اَلْعَرَبِيَّةُ'
fixed_text = get_display(reshape(some_text))
```
(also maybe important to note that this does not affect other scripts so it can safely be used without knowing the exact script this will convert)

**Comment by Lucas-C** [comment]
Interesting.
Could you provide the Python code ued to generate the PDF and/or the PDF itself?

**Comment by semaeostomea** [comment]
> Interesting. Could you provide the Python code ued to generate the PDF and/or the PDF itself?

Here's the code for the overwritten class
```
class PDF(FPDF):
    def __init__(self, font, fontsize, align, background=None, columns=0):
        super().__init__(unit='pt', format=(fontsize*50, fontsize*70))
        self.set_margins(fontsize*3, fontsize*3, fontsize*3)
        self.set_auto_page_break(auto=True, margin=fontsize*4)
        self.col = 0  # Current column
        self.y0 = 0  # Ordinate of column start
        self._fontsize = fontsize
        self._align = align
        self._columns = columns
        self.add_font('DefaultUni', '', font, uni=True)
        self._width = self.epw/(self._columns+1)
        self._lang = 'en'
        self._background = background

    def set_background(self, content):
        self._background = content

    def add_page(
        self, orientation="", format="", same=False, duration=0, transition=None, background=None):
        if self.state == DocumentState.CLOSED:
            raise FPDFException(
                "A page cannot be added on a closed document, after calling output()"
            )
        if self.state == DocumentState.UNINITIALIZED:
            self.open()

        family = self.font_family
        style = f"{self.font_style}U" if self.underline else self.font_style
        size = self.font_size_pt
        lw = self.line_width
        dc = self.draw_color
        fc = self.fill_color
        tc = self.text_color
        stretching = self.font_stretching

        if self.page > 0:
            # Page footer
            self.in_footer = 1
            self.footer()
            self.in_footer = 0
            # close page
            self._endpage()

        # Start new page
        self._beginpage(
            orientation,
            format,
            same,
            duration or self.page_duration,
            transition or self.page_transition,
            new_page=not self._has_next_page(),
        )

        # set background color
        if background:
            self._background = background

        if self._background:
            self.set_fill_color(*self._background)
            self.rect(0, 0, self.w, self.h, style='F')

        self._out("2 J")  # Set line cap style to square
        self.line_width = lw  # Set line width
        self._out(f"{lw * self.k:.2f} w")

        # Set font
        if family:
            self.set_font(family, style, size)

        # Set colors
        self.draw_color = dc
        if dc != self.DEFAULT_DRAW_COLOR:
            self._out(dc.pdf_repr().upper())
        self.fill_color = fc
        if fc != self.DEFAULT_FILL_COLOR:
            self._out(fc.pdf_repr().lower())
        self.text_color = tc

        # BEGIN Page header
        self.header()

        if self.line_width != lw:  # Restore line width
            self.line_width = lw
            self._out(f"{lw * self.k:.2f} w")

        if family:
            self.set_font(family, style, size)  # Restore font

        if self.draw_color != dc:  # Restore colors
            self.draw_color = dc
            self._out(dc.pdf_repr().upper())
        if self.fill_color != fc:
            self.fill_color = fc
            self._out(fc.pdf_repr().lower())
        self.text_color = tc

        if stretching != 100:  # Restore stretching
            self.set_stretching(stretching)


    def header(self):
        self.y0 = self.get_y()

    def footer(self):
        return
        self.set_x(0)
        self.set_y(-15)
        self.set_font("DefaultUni", size=8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def set_col(self, col, formatting=None):
        # Set column position:
        self.col = col
        x = self._fontsize*2 + self._width
        if formatting:
            x = formatting
        self.set_left_margin(x)
        self.set_x(x)

    @property
    def accept_page_break(self):
        formatting = []
        if self._lang in RTL_SCRIPTS:
            formatting.append(self._fontsize*2)
            formatting.append(self._width + self._fontsize*3)
        else:
            formatting.append(self._fontsize*3 + self._width)
            formatting.append(self._fontsize*3)
        if self.col < self._columns:
            # Go to next column:
            self.set_col(self.col + 1, formatting[0])
            # Set ordinate to top:
            self.set_y(self.y0)
            # Stay on the same page:
            return False
        # Go back to first column:
        self.set_col(0, formatting[1])
        # Trigger a page break:
        return True

    def chapter_title(self, title):
        self.set_font("DefaultUni", size=self._fontsize*1.5)
        self.set_fill_color(200, 220, 255)
        self.multi_cell(0, self._fontsize*2, txt=title[0], link=title[1], fill=False, align=self._align)
        self.ln(self._fontsize)
        self.y0 = self.get_y()

    def metadata(self, metadata):
        self.set_font("DefaultUni", size=self._fontsize/2)
        self.multi_cell(0, self._fontsize/2, txt=metadata, align=self._align)
        self.ln(self._fontsize)
        self.y0 = self.get_y()

    def description(self, description):
        self.set_margins(self._fontsize*3, self._fontsize*3, self._fontsize*3)
        self.set_font('DefaultUni', size=self._fontsize)
        self.cell(0, self._fontsize*1.5, 'Video Description', fill=False)
        self.ln(self._fontsize*2)
        self.y0 = self.get_y()
        self.set_font("DefaultUni", size=self._fontsize/1.3)
        if self._lang in RTL_SCRIPTS:
            w = self._width
            self.set_left_margin(self._width + self._fontsize*3)
        else:
            w = self._width - self._fontsize*2
        self.multi_cell(w, self._fontsize, txt=description, align=self._align)
        self.ln()

    def chapter_body(self, content):
        self.set_font('DefaultUni', size=self._fontsize)
        if self._lang in RTL_SCRIPTS:
            w = self._width
            self.set_left_margin(self._width + self._fontsize*3)
        else:
            w = self._width - self._fontsize*2
        self.multi_cell(w, self._fontsize+self._fontsize/2, txt=content, align=self._align, new_x='RIGHT')
        self.ln()
        self.set_col(0)

    def print_chapter(self, lang, content, title, metadata, description, translation, trans_lang):
        self._lang = lang
        self.add_page()
        self.chapter_title(title)
        if metadata:
            if description:
                if len(description.split('\n')) < 10:
                    metadata = metadata + '\n\nDescription:\n' + description
                    description = None
            self.metadata(metadata)
        self.chapter_body(content)
        if translation:
            self.add_page()
            self.set_margins(self._fontsize*3, self._fontsize*3, self._fontsize*3)
            self.chapter_title((f'{title[0]} | {trans_languages[trans_lang]} Translation | ', title[1]))
            self.chapter_body(translation)
        if description:
            self.add_page()
            self.description(description)
```

This is the code to generate the pdf. It's returned as bytes, but when I save them to my disk directly with output() I get the same results, so the steps in between the bytes and the final output can't be the cause
```python
        pdf = PDF(font=font, fontsize=fontsize, align=align, columns=1, background=(27,57,105))
        
        pdf.print_chapter(lang=lang, content=lines, title=title, metadata=metadata, description=description, translation=trans, trans_lang=trans_lang)

        pdf_bytes = pdf.output()
        return pdf_bytes
```

It's a bit messy but I hope it's still readable

I also just noticed that when I zoom out, the border appears on the supposedly fixed pdf as well. 
![2-3_pt](https://user-images.githubusercontent.com/100974908/184890912-9740422b-42a0-4f55-a380-5032dd7e23d6.png)

I increased the extra space to 10pt and it reduced the border:
![10-10_pt](https://user-images.githubusercontent.com/100974908/184891026-b269a74f-a452-4b5d-ac61-f924edc0df82.png)

Increasing it to 30pt and 50pt removes the border at first but the bottom one pops up on some pages again (which are always the same regardless of file, as with the other ones above)
![30-50_pt](https://user-images.githubusercontent.com/100974908/184891380-269e331f-610a-4087-9dd8-9c7033ef2dbc.png)

I don't know what other people will use to view the pdfs and I intended to provide options to choose different text and background colors and if they choose a dark one I hope I can find a way to prevent that border from popping up

this is a file without extra space:
[white-border.pdf](https://github.com/PyFPDF/fpdf2/files/9351551/white-border.pdf)
this with 30pt and 50pt
[30_50_pt.pdf](https://github.com/PyFPDF/fpdf2/files/9351553/30_50_pt.pdf)



> Would you mind submitting a PR please?
> It would be very welcome 😊
> Maybe just a short mention in docs/Text.md and docs/Unicode.md?

Sure, I'll do that once I've figured out how pull requests work!

**Comment by Lucas-C** [comment]
> Sure, I'll do that once I've figured out how pull requests work!

I suggest you get a look at this guide: https://opensource.guide/how-to-contribute/#opening-a-pull-request
😊

I'm assigning this issue to myself to investigate, but it may take a few days before I find the time to do so.
I have a hunch that it's due to rounding floats.

**Comment by semaeostomea** [comment]
@Lucas-C I've reduced the code I provided above, making sure it doesn't have anything do to with the overridden class after all.
I think you also prefer not having to go through all that code

here is the short version with the same result:
```python
fontsize = 12
pdf = FPDF(unit='pt', format=(fontsize*50, fontsize*70))
pdf.set_fill_color(0, 0, 0)
for x in range(5):
    pdf.add_page()
    pdf.rect(0, 0, pdf.w, pdf.h, style='F')
pdf.output('test.pdf')
```

**Comment by Lucas-C** [comment]
> When opening it in firefox, you can see a white border at the bottom and sometimes the right side as seen in the screenshot below

What version of Firefox are you using?
I could not reproduce your problem using 103.0.1 (64 bits) on Windows, nor with 104.0.5112.81 (64 bits).

There is the PDF I generated using the latest version of `fpdf2`:
[issue_487.pdf](https://github.com/PyFPDF/fpdf2/files/9364084/issue_487.pdf)

**Comment by Lucas-C** [comment]
Looking at the internal object stream generated, there does not seem to be any rounding issue:
```
$ qpdf --object-streams=disable --compress-streams=n --qdf issue_487{,-q}.pdf
$ grep ' re ' issue_487-q.pdf
0.00 840.00 600.00 -840.00 re f
0.00 840.00 600.00 -840.00 re f
0.00 840.00 600.00 -840.00 re f
0.00 840.00 600.00 -840.00 re f
0.00 840.00 600.00 -840.00 re f
```

**Comment by semaeostomea** [comment]
> What version of Firefox are you using? 
I'm using 103.0.2 64 bits on Windows
I also don't see that issue on Chrome either, just Firefox
same with the file you generated:
![Screenshot 2022-08-17 173600](https://user-images.githubusercontent.com/100974908/185181706-b70c1a1b-9d4a-47da-be08-354cb82e4052.png)

> What are your versions of Python & fpdf2?
3.10.5 and 2.5.5

**Comment by Lucas-C** [comment]
That is really strange...
At what zoom level do you ee those artifacts?

Firefox uses [PDF.js](https://mozilla.github.io/pdf.js/) as its default viewer.
Do you use an alternative PDF viewer by any chance, maybe through a browser addon?
Based on their [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-extensions), PDF.js is part of Firefox since version 19.

**Comment by semaeostomea** [comment]
> That is really strange...
> At what zoom level do you see those artifacts?

without extra space added to the rectangle I see them at 100% already. The weirdest part is that they disappear when I make the rectangle bigger. When I do that they only appear when I zoom out

> Firefox uses [PDF.js](https://mozilla.github.io/pdf.js/) as its default viewer.
> Do you use an alternative PDF viewer by any chance, maybe through a browser addon?

I use the default viewer

> I have to admit that I don't really see where your issue could be coming from,
> apart maybe from a graphic card / driver related [issue with PDF.js](https://github.com/mozilla/pdf.js/issues)?

That could be possible. I'm just confused as to why increasing the size of the rectangle fixes it to some extent 

I'll also look into other ways to add a background and see if that changes anything. Do you think this could be something that can be implemented in the future as a simple additional keyword on add_page() and/or the FPDF constructor?

**Comment by Lucas-C** [comment]
> I'll also look into other ways to add a background and see if that changes anything. Do you think this could be something that can be implemented in the future as a simple additional keyword on add_page() and/or the FPDF constructor?

What "other ways" are you thinking of?
I tested how LibreOffice & Word implement colored PDF backgrounds and they both use a rectangular shape.

**Comment by semaeostomea** [comment]
> What "other ways" are you thinking of? I tested how LibreOffice & Word implement colored PDF backgrounds and they both use a rectangular shape.

For one, adding the background as an image (same result) but I also tried finding other ways to apply the color directly. As I understand it the rectangle is simply placed on top of a white canvas. But that doesn't seem to be possible.

Apart from that I've found out that this must be related to the format. When using a DIN format (eg A4, A5, A3) there's no border unless I zoom out to 60% at which point there's just a slight border on the right side. When I increase the size of the rectangle a bit, the border is gone, even when zoomed out completely.

I might bring this up [as an issue with PDF.js](https://github.com/mozilla/pdf.js/issues) because I also noticed that a bit of the bottom of the pages gets cut off on some zoom levels

Just to double back on my question: could a background keyword (as I imagine it, it would be possible to set it for the whole pdf, per page, and with a function set_background(); colors and images) be implemented? Without overriding the class like I did it's not possible to set a proper background if one uses automatic page breaks like in multi_cell() because the following pages are obviously white

Thank you for your help! And for encouraging me to issue my first pull request 👍

**Comment by Lucas-C** [comment]
> I might bring this up [as an issue with PDF.js](https://github.com/mozilla/pdf.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) because I also noticed that a bit of the bottom of the pages gets cut off on some zoom levels

Sounds like a good idea to me.
They certainly know more about the viewer behaviour than me, and could be able to explain the glitch you see.

> Just to double back on my question: could a background keyword (as I imagine it, it would be possible to set it for the whole pdf, per page, and with a function `set_background()`; colors and images) be implemented? Without overriding the class like I did it's not possible to set a proper background if one uses automatic page breaks like in `multi_cell()` because the following pages are obviously white

I add another look at the [1.7 PDF spec](https://christianhaider.de/dokuwiki/lib/exe/fetch.php?media=pdf:pdf32000_2008.pdf) but sadly no, I don't see any support in it to define a background color or image 😔

**Comment by semaeostomea** [comment]
> I had another look at the [1.7 PDF spec](https://christianhaider.de/dokuwiki/lib/exe/fetch.php?media=pdf:pdf32000_2008.pdf) but sadly no, I don't see any support in it to define a background color or image 😔
> 
> The following HexaPDF issue also points toward the need to draw a rectangle: [gettalong/hexapdf#43](https://github.com/gettalong/hexapdf/issues/43)

Oh maybe I didn't express my idea properly. I mean by doing it like I did, by adding the rectangle/image in the add_page() function when a background is specified, so that users don't have to override the class just for adding a background(which will also be applied on new pages added in the multi_cell() function, which they don't if it's done outside of the class before the multi_cell() function. Only the first page has a background in that case)

**Comment by Lucas-C** [comment]
> I mean by doing it like I did, by adding the rectangle/image in the add_page() function when a background is specified, so that users don't have to override the class just for adding a background(which will also be applied on new pages added in the multi_cell() function, which they don't if it's done outside of the class before the multi_cell() function.

Oh OK, I understand now!
Alright, then yes, I would be open to a PR introducing a `set_background()` method,
which would then trigger the creation of a rectangle in every later call to `add_page()`.

**Comment by Lucas-C** [comment]
Also: 

> Thank you for your help! And for encouraging me to issue my first pull request 👍

You're very welcome, glad you've been contributing to `fpdf2` as your 1st project ^^

**Comment by gmischler** [comment]
@semaeostomea , sorry to come late to the party here...

I'm missing a way to clear the background settings again.
Say I want to have a background on some page(s), but not the following ones. The only way to do that now is to set the background to white for the rest of the document.
I think just allowing `None` as a valid argument would do the trick here.

A short explanation on the documentation page about [Page Format and Orientation](https://pyfpdf.github.io/fpdf2/PageFormatAndOrientation.html) would probably be helpful as well.

**Comment by Lucas-C** [comment]
> I think just allowing `None` as a valid argument would do the trick here.

I agree, good idea

**Comment by semaeostomea** [comment]
> I'm missing a way to clear the background settings again. Say I want to have a background on some page(s), but not the following ones. The only way to do that now is to set the background to white for the rest of the document. I think just allowing `None` as a valid argument would do the trick here.

You're right, I completely forgot about that after restricting the accepted values 😅 

I'll issue another pull request for the changes then?

**Comment by Lucas-C** [comment]
> I'll issue another pull request for the changes then?

Sounds great, thank you @semaeostomea!
A single unit test and minor change in `set_page_background` should be enough

**Comment by semaeostomea** [comment]
> @semaeostomea: do you think this issue can be closed, or do you have any remaining question/problem related to `fpdf2`?

oh yes of course this issue can be closed 😊 thank you
