### ISSUE TITLE
Any idea how to achieve letter spacing?

### ISSUE THREAD

**Issue by Beuthmaster** [PyFPDF/fpdf2#489]
Hey there, I'm looking for a way to enable customized letter spacing. Do you have any idea, how to achieve that?
I tried `write_html()`, but it seems like this library can't read html inline style properties, right? 

Any tips appreciated! Thanks in advance!

**Comment by aedvice** [comment]
Same issue here!

**Comment by Lucas-C** [comment]
Hi @Beuthmater @aedvice: have you tested [set_stretching()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_stretching)?

**Comment by gmischler** [comment]
There's currently no easy way to do that. Unfortunately, `set_stretching()` also changes the shape of the characters, which is probably not what you want.

It could be implemented, in a similar way as we currently use the `Tw` instruction to space words for justifying text.
The `Tc` instruction changes the space between individual characters.

A new method `set_character_spacing(spacing: float, unit: str = "Pt")` could be added to insert this instruction into the PDF.
Of course, the line wrapping algorithm will have to take this into account as well.
I think a default of typographic points (Pica) for the unit would make the most sense, but that's up for debate.

In the short term, and if you only want to do that for single-line text, you could make a subclass of `FPDF()` yourself that just does a `self._out(f"{wsp} Tc")` where desired, and a `self._out("0 Tc")` to reset to normal. I *think* the size of `wsp` needs to be in Pica, but you'd have to test this out.

**Comment by Beuthmaster** [comment]
Thanks @gmischler . Works out perfect!
