### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by pimuzzo** [PyFPDF/fpdf2#501]
I noticed it during a loop that generates PDFs inside a scheduled job that runs daily.

**Minimal code**
```python

import gc
import sys

import psutil
from fpdf import FPDF


def main(loops):
    ram_usage = round((psutil.Process().memory_info().rss / (1024 * 1024)), 2)
    print(f"Memory usage start - {ram_usage} MB")

    for i in range(loops):
        pdf = FPDF()

        pdf.add_page()
        pdf.image("pia22486_orig.png", x=20, y=60)

        pdf.add_page()
        pdf.image("maf_20210822_moonovernola_orig.jpeg", x=20, y=60)

        pdf.add_page()
        pdf.image("16188673307_e2f8cd50ed_o.jpeg", x=20, y=60)

        pdf.add_page()
        pdf.image("ksc-20211109-ph-jbs01_0151_orig.jpg", x=20, y=60)

        pdf.output(f"pdf-with-images-{i}.pdf")

    ram_usage = round((psutil.Process().memory_info().rss / (1024 * 1024)), 2)
    print(f"Memory usage end - {ram_usage} MB")


if __name__ == "__main__":
    loops = int(sys.argv[1])
    ram_usage = round((psutil.Process().memory_info().rss / (1024 * 1024)), 2)
    print(f"Memory usage before main({loops}) - {ram_usage} MB")

    main(loops)
    gc.collect()

    ram_usage = round((psutil.Process().memory_info().rss / (1024 * 1024)), 2)
    print(f"Memory usage after main({loops}) - {ram_usage} MB")
```

outputs:
```
python main.py 2
Memory usage before main(2) - 26.3 MB
Memory usage start - 26.3 MB
Memory usage end - 405.16 MB
Memory usage after main(2) - 270.79 MB

python main.py 10
Memory usage before main(10) - 26.23 MB
Memory usage start - 26.23 MB
Memory usage end - 1232.05 MB
Memory usage after main(10) - 1183.49 MB
```

* The images are high res pictures that can be found [here](https://www.nasa.gov/multimedia/imagegallery/iotd.html)
* I followed the [official tutorial](https://pyfpdf.github.io/fpdf2/Images.html)

Any help or workaround will be really appreciated!

**Environment**
* OS: Linux debian
* Python version: 3.10.4
* `fpdf2` version 2.5.6

**Comment by Lucas-C** [comment]
Hi @pimuzzo!

Thank you for reporting this.
I'm assigning this to myself and plan to get a look at it asap.

**Comment by pimuzzo** [comment]
Hi @Lucas-C!

I tried with a single page with one image and the output is:
```
python main2.py 10
Memory usage before main(10) - 26.17 MB
Memory usage start - 26.17 MB
Memory usage end - 95.15 MB
Memory usage after main(10) - 55.25 MB

python main.py 40     
Memory usage before main(40) - 26.27 MB
Memory usage start - 26.27 MB
Memory usage end - 95.22 MB
Memory usage after main(40) - 55.32 MB
```

The memory difference between start and end looks constant increasing the loops

**Comment by gmischler** [comment]
This [Pillow issue #5401](https://github.com/python-pillow/Pillow/issues/5401) may or may not be relevant.

How does memory consumption develop if you run your code in a much longer (1k+) loop?

Do the PILLOW_BLOCK_SIZE and PILLOW_BLOCKS_MAX envvars make any difference?

**Comment by pimuzzo** [comment]
I edited my code in this way:
```
if __name__ == "__main__":
    os.environ['PILLOW_BLOCK_SIZE'] = '1m'
    os.environ['PILLOW_BLOCKS_MAX'] = '5'

    loops = int(sys.argv[1])
    ram_usage = round((psutil.Process().memory_info().rss / (1024 * 1024)), 2)
    print(f"Memory usage before main({loops}) - {ram_usage} MB")

    main(loops)
    gc.collect()

    ram_usage = round((psutil.Process().memory_info().rss / (1024 * 1024)), 2)
    print(f"Memory usage after main({loops}) - {ram_usage} MB")
```

1k+ loop will take too long to complete, but I tried with this code and 10 and 50 loops:

```
python main.py 10     
Memory usage before main(10) - 26.3 MB
Memory usage start - 26.3 MB
Memory usage end - 1172.05 MB
Memory usage after main(10) - 1124.27 MB

python main.py 50     
Memory usage before main(50) - 26.38 MB
Memory usage start - 26.38 MB
Memory usage end - 1683.25 MB
Memory usage after main(50) - 870.55 MB
```

**Comment by Lucas-C** [comment]
I'm having trouble identifyig where this memory allocation happens...
I tried several approaches: `memory_profiler`, `pympler`, `tracemalloc`, `memleax`...
Those tools always report an amount of memory allocated far below the RSS value.

Example with `tracemalloc`, based on your original code @pimuzzo:
```python
import linecache, tracemalloc

...

def display_top(snapshot, key_type='lineno', limit=10):
    "Recipe from: https://confluence.desy.de/display/FSEC/Finding+memory+leaks"
    snapshot = snapshot.filter_traces((
        tracemalloc.Filter(False, "<frozen importlib._bootstrap>"),
        tracemalloc.Filter(False, "<unknown>"),
    ))
    top_stats = snapshot.statistics(key_type)
    print("Top %s lines allocating memory:" % limit)
    for index, stat in enumerate(top_stats[:limit], 1):
        print(stat)
        frame = stat.traceback[0]
        line = linecache.getline(frame.filename, frame.lineno).strip()
        if line:
            print('    %s' % line)
    other = top_stats[limit:]
    if other:
        size = sum(stat.size for stat in other)
        print("%s other lines: %.1f KiB" % (len(other), size / 1024))
    total = sum(stat.size for stat in top_stats)
    print("Total allocated size: %.1f MiB" % (total / 1024 / 1024))

if __name__ == "__main__":
    ...
    tracemalloc.start()
    main(loops)
    snapshot = tracemalloc.take_snapshot()
    display_top(snapshot)

```

Results in:
```
Memory usage before main(10) - 32.43 MB
Memory usage start - 32.45 MB
Memory usage end - 1608.16 MB
Top 10 lines allocating memory:
/opt/fpdf2/fpdf/fpdf.py:4651: size=269 MiB, count=5, average=53.7 MiB
    self.buffer += s + b"\n"
/opt/fpdf2/fpdf/image_parsing.py:41: size=205 MiB, count=26, average=8054 KiB
    return BytesIO(local_file.read())
/opt/fpdf2/fpdf/image_parsing.py:157: size=36.0 MiB, count=13, average=2839 KiB
    return compressed_bytes.getvalue()
/home/username/.local/share/virtualenvs/fpdf2/lib/python3.8/site-packages/PIL/ImageFile.py:549: size=460 KiB, count=153, average=3077 B
    data = fp.read(size)
<frozen importlib._bootstrap_external>:640: size=382 KiB, count=4250, average=92 B
/home/username/.local/share/virtualenvs/fpdf2/lib/python3.8/site-packages/PIL/ImageFile.py:518: size=371 KiB, count=26, average=14.3 KiB
    l, s, d = encoder.encode(bufsize)
/home/username/.local/share/virtualenvs/fpdf2/lib/python3.8/site-packages/PIL/JpegImagePlugin.py:126: size=158 KiB, count=171, average=945 B
    data = s[offset : offset + size]
/home/username/.local/share/virtualenvs/fpdf2/lib/python3.8/site-packages/PIL/Image.py:3522: size=142 KiB, count=13, average=10.9 KiB
    data = data[6:]
/home/username/.local/share/virtualenvs/fpdf2/lib/python3.8/site-packages/PIL/JpegImagePlugin.py:226: size=20.1 KiB, count=13, average=1581 B
    profile.append(p[14:])
/home/username/.local/share/virtualenvs/fpdf2/lib/python3.8/site-packages/PIL/JpegImagePlugin.py:258: size=17.2 KiB, count=56, average=314 B
    self.quantization[v & 15] = [data[i] for i in zigzag_index]
1004 other lines: 561.3 KiB
Total allocated size: 511.1 MiB
Memory usage after main(10) - 786.46 MB
```

**Comment by Lucas-C** [comment]
I tested adding those lines after the call to `pdf.output()`:
```python
del pdf
gc.collect()
```
As a result the memory usage is a lot lower:
```
$ python issue_501.py 10
Memory usage before main(10) - 32.43 MB
Memory usage start - 32.43 MB
Memory usage end - 106.62 MB
Memory usage after main(10) - 106.62 MB
```

**Comment by Lucas-C** [comment]
There is some minimal code that also displays the script peak memory usage:
```python
import gc, resource, sys
from time import perf_counter

from fpdf import FPDF
import psutil

if __name__ == "__main__":
    loops = int(sys.argv[1])
    ram_usage = round((psutil.Process().memory_info().rss / (1024 * 1024)), 2)
    peak_ram_usage = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024
    print(f"Memory usage start - {ram_usage} MiB / peak: {peak_ram_usage:.2f} MiB")

    for i in range(1, loops + 1):
        start = perf_counter()
        pdf = FPDF()
        pdf.set_margin(0)
        for img_path in ("pia22486_orig.png", "maf_20210822_moonovernola_orig.jpeg", "16188673307_e2f8cd50ed_o.jpeg", "ksc-20211109-ph-jbs01_0151_orig.jpg"):
            pdf.add_page()
            pdf.image(img_path, w=pdf.epw)
        pdf.output(f"issue_501-pdf-with-images-{i}.pdf")
        print(f"PDF generation in iteration {i} took {perf_counter() - start:.1f}s")
        del pdf
        start = perf_counter()
        gc.collect()
        print(f"gc.collect() in iteration {i} took {perf_counter() - start:.1f}s")

    ram_usage = round((psutil.Process().memory_info().rss / (1024 * 1024)), 2)
    peak_ram_usage = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024
    print(f"Memory usage end - {ram_usage} MiB / peak: {peak_ram_usage:.2f} MiB")
```

Results in:
```
$ python issue_501.py 2
Memory usage start - 32.15 MiB / peak: 32.16 MiB
PDF generation in iteration 1 took 28.2s
gc.collect() in iteration 1 took 0.1s
PDF generation in iteration 2 took 29.1s
gc.collect() in iteration 2 took 0.1s
Memory usage end - 46.38 MiB / peak: 518.02 MiB
```

And after disabling the GC collection by commenting out the last 4 lines of the `for` loop:
```
$ python issue_501.py 2
Memory usage start - 32.16 MiB / peak: 32.16 MiB
PDF generation in iteration 1 took 29.3s
PDF generation in iteration 2 took 28.3s
Memory usage end - 748.0 MiB / peak: 819.96 MiB
```

Note that if you re-use the same images in several PDF files you are generating, you can use a small hack to speed things up by to re-using the images cache among successive FPDF instances:
```python
    images_cache = None
    for i in range(1, loops + 1):
        start = perf_counter()
        pdf = FPDF()
        if images_cache:
            pdf.images = {k: dict(v) for k, v in images_cache.items()}
        pdf.set_margin(0)
        for img_path in ("pia22486_orig.png", "maf_20210822_moonovernola_orig.jpeg", "16188673307_e2f8cd50ed_o.jpeg", "ksc-20211109-ph-jbs01_0151_orig.jpg"):
            pdf.add_page()
            pdf.image(img_path, w=pdf.epw)
        if not images_cache:
            images_cache = {k: dict(v) for k, v in pdf.images.items()}
            for img in images_cache.values():
                img["usages"] = 0
        pdf.output(f"issue_501-pdf-with-images-{i}.pdf")
        print(f"PDF generation in iteration {i} took {perf_counter() - start:.1f}s")
```

Which results in:
```
$ python issue_501.py 10
Memory usage start - 32.17 MiB / peak: 32.18 MiB
PDF generation in iteration 1 took 29.0s
gc.collect() in iteration 1 took 0.1s
PDF generation in iteration 2 took 0.5s
gc.collect() in iteration 2 took 0.0s
PDF generation in iteration 3 took 0.5s
gc.collect() in iteration 3 took 0.0s
PDF generation in iteration 4 took 0.6s
gc.collect() in iteration 4 took 0.0s
PDF generation in iteration 5 took 0.5s
gc.collect() in iteration 5 took 0.0s
PDF generation in iteration 6 took 0.5s
gc.collect() in iteration 6 took 0.0s
PDF generation in iteration 7 took 0.5s
gc.collect() in iteration 7 took 0.0s
PDF generation in iteration 8 took 0.5s
gc.collect() in iteration 8 took 0.0s
PDF generation in iteration 9 took 0.5s
gc.collect() in iteration 9 took 0.0s
PDF generation in iteration 10 took 0.5s
gc.collect() in iteration 10 took 0.0s
Memory usage end - 215.81 MiB / peak: 517.57 MiB
```

**Comment by Lucas-C** [comment]
I don't really think there is a memory leak...

@pimuzzo: do you have any more questions/interrogations regarding this?

**Comment by pimuzzo** [comment]
I will add the `del` + `gc.collect()`.
Thank you for the small hack to speed things up and for your help.
No more questions for now.

**Comment by Lucas-C** [comment]
Glad that helped you!
Closing this issue then

**Comment by Lucas-C** [comment]
> My first hope was that png files just get copied into the pdf file like binary data. But it seems they get opened and analyzed and/or reencoded.

Indeed, the PDF spec only allows for JPEG files to be embedded, so PNG files need to be re-encoded.

> That means all temp data is stored somewhere until I call `pdf.output("myfile.pdf")`. In the source code I can't see the opening of a temp file in a temp directory. I assume all data is written to a string. If this is true, then the RAM usage growth linear to the number of pages.

Your assumptions are correct.

Sadly, for you use case, I don't see in any way how `fpdf2` could allow you to generate a single PDF document with 125+ PNG images without using that much RAM...
In theory, the Python code could lazily process every image file: at the very last moment when writing PDF document to a file, then load every PNG image used one by one, convert it to JPEG, write to disk and immediately free the memory used before handling the next PNG image.
But that would be very hard to implement with `fpdf2` because:
* it does not write to disk: its `.output()` method produces bytes written in RAM
* image conversion is currently perfomed immediately when `.image()` is called

As a side question, what size do you expect your final PDF document to be?
Have you considered automated image downscaling? _cf._ https://pyfpdf.github.io/fpdf2/Images.html#oversized-images-detection-downscaling

**Comment by Lucas-C** [comment]
> if I understand correctly, those are not reencoded and thus can directly be written

Yes exactly. Those images would still be loaded into memory as JPEG when calling `.image()` though.

> Ok, but it should be possible to replace all string concatenations and replace them by calls to file.write

I guess you could try subclassing `FPDF` and overriding its internal `._out()` & `_newobj` methods... and all other references to `self.buffer` in `fpdf2`. Which could be more difficult that you hoped.

**Comment by Lucas-C** [comment]
> @Lucas-C I just saw on [this](https://gitlab.mister-muffin.de/josch/img2pdf) page that more formats can be directly embedded into pdf (theoretically). Those are JPEG, JPEG2000, PNG (non-interlaced, no transparency) and TIFF (CCITT Group 4, monochrome).

Interesting. looking at their reference PDF files in [src/tests/output/](https://gitlab.mister-muffin.de/josch/img2pdf/src/branch/main/src/tests/output), what they call "embedding PNG" is simply embedding images without any compression.

I was wrong / unclear when I wrote earlier that _"the PDF spec only allows for JPEG files to be embedded"_.
JPEG is **the only [lossy image compression](https://en.wikipedia.org/wiki/Lossy_compression) algorithm natively supported by PDF** , but the PDF spec also allows to embed images **without any compression**. JPEG2000 is a close variant of JPEG so assimilated both.
To be really specific, the [1.7 PDF spec](https://christianhaider.de/dokuwiki/lib/exe/fetch.php?media=pdf:pdf32000_2008.pdf) allows for the following `/Filter`:
<img width="537" alt="2022-09-28 23_07_53-PDF32000_2008-decrypted pdf -  PDF32000 book  - SumatraPDF" src="https://user-images.githubusercontent.com/925560/192889446-d52c36f2-3bfb-4e8a-ae1a-b0f3e70b728f.png">
`fpdf2` allows you to set the `image_filter` you wish to use when loading images:
* [set_image_filter()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_image_filter)
* allowed values: https://github.com/PyFPDF/fpdf2/blob/2.5.7/fpdf/image_parsing.py#L21

> But on the other hand I also just saw that my use case won't work, because I planned to have images with transparency, which seems to not be supported at all in pdf.

Actually you can: https://github.com/PyFPDF/fpdf2/blob/master/test/image/image_types/test_insert_images.py#L70
Results in: https://github.com/PyFPDF/fpdf2/blob/master/test/image/image_types/image_types_insert_png_alpha.pdf

**Comment by Lucas-C** [comment]
FYI,regarding the initial memory leak issue,
I have just added checks in our unit tests suite to control memory usage of `fpdf2`:
https://github.com/PyFPDF/fpdf2/commit/7fce7231547060555fadb7bbeb05ef97d6dc8f4b
