### ISSUE TITLE
Suggestion: Add support for Inline bold Text

### ISSUE THREAD

**Issue by devansh-07** [PyFPDF/fpdf2#52]
I'm currently working on a project which uses the fpdf library to generate PDF files. I'm looking into options to highlight some specific words in a cell (or multi_cell) using **bold** or _Italic_ text. I found that we can use multiple cells with different font styles to achieve this but if we have multiple words that need to be styled, this idea is not so efficient. It makes the code messy and reduces the readability of the code.

I'm also willing to work on this and contribute to this library. Can we discuss it?

_Thank_**s**

**Comment by Lucas-C** [comment]
Interesting suggestion!

Could you develop what kind of Python usage you imagine?
Do you to support processing of Markdown-style markup on the `text` parameter in `FPDF.cell` for example?

I had a quick look at the PDf spec, and font weight control always seem to induce font switching with the `Tf` operator.

I also checked and this is not currently supported by the HTML conversion feature:

    pdf.write_html("Regular <bold>Bold</bold> <em>Italics</em>")

**Comment by devansh-07** [comment]
I haven't actually worked on it. But I was thinking of using something similar to what SO and Github uses
(i.e., \* for italic text, \**  for bold text, and \*** for Bold italic text. or \_ in place of \* and \\ to escape these characters).

For example,
```
pdf.cell(0, 12, "*This text is italic*. **This text is bold**. ***This text is bold italic***.")
```
Output:
*This text is italic*. **This text is bold**. ***This text is bold italic***.

I don't have much idea of how PDFs work internally, so, not sure if we can do something with the `tf` operator.

**Comment by Lucas-C** [comment]
Actually, my mistake, this is already supported by `FPDF.write_html`!

But you'll need to use the old HTML tags `<b>`, `<u>` and `<i>`:

```python
pdf.write_html(
    """<B>bold</B>
       <I>italic</I>
       <U>underlined</U>
       <B><I><U>all at once!</U></I></B>"""
)
```

**Comment by Lucas-C** [comment]
I added a test for this in https://github.com/PyFPDF/fpdf2/pull/55

**Comment by Lucas-C** [comment]
@devansh-07 Does this answer your initial request? Can this issue be closed?

**Comment by devansh-07** [comment]
Yeah sure! Thank you for the help.
