### ISSUE TITLE
.add_font() -- AttributeError: 'table__n_a_m_e' object has no attribute 'getBestFullName'

### ISSUE THREAD

**Issue by guillaume-dotcom** [PyFPDF/fpdf2#524]
When updating to latest release (v2.5.7) and checking out if my older scripts were compatible, I discovered that the add_font created an attribute error and seems to me like a bug. 

With code below on Windows assuming that the font file is accessible and all works just fine with fpdf2 v2.4.6.

```python
from fpdf import FPDF, HTMLMixin 
from pathlib import Path, PureWindowsPath

class FPDF(FPDF, HTMLMixin):
    pass

pdf = FPDF()
pdf.add_page()
pdf.add_font('DejaVuSans', '',str(Path(fontfolder/'DejaVuSans.ttf')),uni=True)
pdf.set_font('DejaVuSans', size=14)
```

I get the following error: 

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> ~\AppData\Local\Temp\1\ipykernel_33804\142261010.py in <module>
>      11 pdf = FPDF()
>      12 pdf.add_page()
> ---> 13 pdf.add_font('DejaVuSans', '', str(Path(fontfolder/'DejaVuSans.ttf')),uni=True)
>      14 pdf.set_font('DejaVuSans', size=14)
> 
> c:\Users\gmme\Anaconda3\lib\site-packages\fpdf\fpdf.py in add_font(self, family, style, fname, uni)
>    1914             "i": len(self.fonts) + 1,
>    1915             "type": "TTF",
> -> 1916             "name": re.sub("[ ()]", "", font["name"].getBestFullName()),
>    1917             "desc": desc,
>    1918             "up": round(font["post"].underlinePosition * scale),
> 
> AttributeError: 'table__n_a_m_e' object has no attribute 'getBestFullName'
> 

Thanks.

**Comment by Lucas-C** [comment]
Hi and thanks for reporting this @guillaume-dotcom 

I'm sorry but I couldn't reproduce your issue, neither under Linux (Ubuntu) nor Windows (10)

Note also that your sample code is not fully correct.
I defined `fontfolder = Path('test/fonts/')` in order for it to work when executed at the root of this repository.

**Comment by guillaume-dotcom** [comment]
Hi @Lucas-C  and thanks for the swift reply, 

Point taken. Apologies for leaving one the `fontfolder` definition. 

It is odd. Changing the interpreter to a previous version of fpdf2 worked just fine then. I wonder what could trigger this message. 

I also tried to reproduce your code (exactly) and get the same error.

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> ~\AppData\Local\Temp\1\ipykernel_26752\1024916228.py in <module>
>       6 pdf = FPDF()
>       7 pdf.add_page()
> ----> 8 pdf.add_font('DejaVuSans', '', fontfolder/'DejaVuSans.ttf')
>       9 pdf.set_font('DejaVuSans', size=14)
> 
> c:\Users\gmme\Anaconda3\lib\site-packages\fpdf\fpdf.py in add_font(self, family, style, fname, uni)
>    1914             "i": len(self.fonts) + 1,
>    1915             "type": "TTF",
> -> 1916             "name": re.sub("[ ()]", "", font["name"].getBestFullName()),
>    1917             "desc": desc,
>    1918             "up": round(font["post"].underlinePosition * scale),
> 
> AttributeError: 'table__n_a_m_e' object has no attribute 'getBestFullName'

**Comment by gmischler** [comment]
You don't seem to have a recent enough version of fonttools installed.
The name of the "missing" method was changed there from `getNiceFullName()` to `getBestFullName()` [a few months ago](https://github.com/fonttools/fonttools/commit/1649973800cbf0c8d96b785ccac381672a0996cc).
The version you have was probably installed as a dependency of some other package before that.

> It is odd. Changing the interpreter to a previous version of fpdf2 worked just fine then. I wonder what could trigger this message.

That's easy to explain, since fpdf2 only started to use fonttools with release 2.5.7 published just yesterday.

**Comment by guillaume-dotcom** [comment]
Hey @gmischler, 

That did the trick. thanks. :)

Shouldn't we have an updated fonttools requirements in setup.py to ensure this is not a recurring issue?

**Comment by gmischler** [comment]
> shouldn't we have an updated fonttools requirement in setup.py to ensure this is not a recurring issue?

Yes, setting a minimum version might be useful for several dependencies. We've had similar questions about Pillow in the past.

Some people even reccommend to pin all dependencies to a fixed version that has been checked and tested, in order to prevent supply chain attacks.

**Comment by Lucas-C** [comment]
> Yes, setting a minimum version might be useful for several dependencies. We've had similar questions about Pillow in the past.

I agree! Would you like to submit a PR introducing a minimum version for `fonttools` @guillaume-dotcom?

**Comment by guillaume-dotcom** [comment]
Yes @Lucas-C. I will submit a PR.
