### ISSUE TITLE
fonttools.svgPath.path.parse_path() to replace svg.path?

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#525]
I just discovered that fonttools have a module "svgLib", containing a class [svgLib.path](https://fonttools.readthedocs.io/en/latest/svgLib/path/index.html), which again has a method `parse_path()`. 

I wonder if this could be used to replace the "svg.path" package that we currently use, reducing the number of dependencies for fpdf2 again.

**Comment by Lucas-C** [comment]
This sounds interesting, well spotted @gmischler!

Have you checked their code quality / test coverage, and if they support as many use cases as `svg.path`?

**Comment by gmischler** [comment]
> Have you checked their code quality / test coverage, and if they support as many use cases as `svg.path`?

Fonttools looks to be a very well maintained and active project, but other than that I haven't looked into the details of this specific module yet.
