### ISSUE TITLE
Add support for <dl>/<dt>/<dd> in HTML2FPDF

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#534]
Documentation on `<dl>`/`<dt>`/`<dd>`: [MDN](https://developer.mozilla.org/fr/docs/Web/HTML/Element/dl)

The goal here is to add support for those HTML tags in [fpdf/html.py](https://github.com/PyFPDF/fpdf2/blob/master/fpdf/html.py)
Of course, new unit tests should be added, as well as a mention of those tags on [the dedicated documentation page](https://pyfpdf.github.io/fpdf2/HTML.html#supported-html-features)

This could also be an opportunity to deprecate [`HTMLMixin`](https://pyfpdf.github.io/fpdf2/HTML.html) and have `write_html()` being available directly on the `FPDF` class.

---
By implementing this feature you, as a benevolent [FLOSS](https://en.wikipedia.org/wiki/Free/libre_and_open-source_software) developper, will provide access to the large community of fpdf2 users to a useful functionality.
As a contributor you will get review feedbacks from the maintainer & other contributors, and learn about the lifecycle & structure of a Python library on the way.
You will also be added to the [contributors list & map](https://github.com/PyFPDF/fpdf2#contributors-).

This issue can count has part of [hacktoberfest](https://hacktoberfest.com)

**Comment by yk-jp** [comment]
@Lucas-C 
Hi, I would like to work on this issue.
I'm new to OSS contribution, but I'd like to try it.

**Comment by Lucas-C** [comment]
Welcome @yk-jp!
You are very welcome to work on this :)
You can start by having a look at our [Development](https://pyfpdf.github.io/fpdf2/Development.html) page,
and by installing the required packages on your development environment in order to be able to run `black` and `pytest`.

**Comment by Lucas-C** [comment]
Thank you and good job for submitting a PR @yk-jp!
I made a code review. Do not hesitate to ask questions if any part of the contribution process seems unclear to you.

@allcontributors please add @yk-jp for code
