### ISSUE TITLE
I am trying to use Tamil font (ttf). But the letters are jumbled up.  

### ISSUE THREAD

**Issue by Sriram1958** [PyFPDF/fpdf2#541]
Describe the bug

I want to print Tamil font letters in my report.  I used fpdf2 to send the output to PDF (& then I can send it to Printer).
It is printing without any errors.  But the letters are jumbled up. 

**Error details**
NIL reported. 

**Minimal code**
### Print_To_Pdf-From-Table-with-Header-Page-Control-with-Diff-Fonts.py
from fpdf import FPDF

pdf = FPDF()

s_font_name = "NotoSansTamil-Light"
s_font_ttf = s_font_name+".ttf"
pdf.add_font(s_font_name, 'B', s_font_ttf, uni=True)

pdf.add_page()

global record, mrecord_list, x, s_id, s_name, s_price, s_wefdt, m_price, m_after_dt

global rh, ph1, ph2, ph3, dh1, dh2, dh3, dh4, dh5, sh1, sh2, st1, st2, de1, de2, de3, pf1, rf1, no_lines, p_w, m_pgprice
rh = ph1 = ph2 = ph3 = dh1 = dh2 = dh3 = dh4 = dh5 = sh1 = sh2 = st1 = st2 = de1 = de2 = de3 = pf1 = rf1 = " "
no_lines = 19
p_w = 72
m_price = 15031
m_pgprice = float(0.00)
m_pgno = 1

pdf.set_font("TIMES", "B", size = 12)

rh = "SVVSS".ljust(int(p_w/2))+"Receipts & Payments System".rjust(int(p_w/2))

ph1 = "Mobile Table Report".center(p_w)
x = "Mobiles above "+str(m_price)
ph2 = x.center(p_w)
dh1 = "= " * 30 +"Page  No :  "+str(m_pgno)
dh2 = "Mob.Id |"+" Mobile Name".ljust(35)+"  |  MobilePrice |  W.E.F. Date"
dh3 = "= " * 37
pf1  = "= " * 26 +"Continued in Page :  "+str(m_pgno+1)
yyy = "{:.2f}".format(m_pgprice) 
st1  = " " * 34 + "Page Total : "+ yyy.rjust(12)
rf1  = "* " * 9 + " End of Report "+m_date_time+ "* " * 9

def pg_headr():
	pdf.set_font("Courier", "B", size = 12)
	x = rh
	pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
	x = ph1
	pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
	x = ph2
	pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
	dh1 = "= " * 30 +"Page  No :  "+str(m_pgno)   
	x = dh1
	pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
	x = dh2
	pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
	x = dh3
	pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
	pdf.set_font("Courier", "B", size = 12)

###
s_wefdt = datetime.datetime.today()
x = " "

#### Gather records from mobile table 

import psycopg2
from psycopg2 import Error

try:
    connection = psycopg2.connect(user="postgres",
                                               password="SVVssPSql@622",
                                               host="::1",
                                               port="5432",
                                               database="postgres")

    cursor = connection.cursor()
    sql_select_query = """select * from mobile where price > %s order by id """
    print(sql_select_query)
    cursor.execute(sql_select_query,(m_price,))   
    record = cursor.fetchall()
    print("Database records from table = ", record)
    pg_headr()
    row_num = 0
    for row in record:
         s_id = str(row[0])
         if s_id == '5':      ### Tamil Font printing only for this row.
              pdf.set_font(s_font_name, "B", size = 10)
         else:                   ### English Font printing for all other rows.
              pdf.set_font("Courier", "B", size = 12)

         s_name = row[1]
         s_price = "{:.2f}".format(row[2])
         s_wefdt = row[3]
         m_date=s_wefdt.strftime("%d")+'-'+s_wefdt.strftime("%b")+'-'+s_wefdt.strftime("%Y")
         s_name = s_name[:35]
         x = s_id.rjust(6)+" | "+ s_name.ljust(35)+" | "+s_price.rjust(12)+" | "+m_date.rjust(12)
         print(x)
         pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
         row_num += 1
         m_pgprice += row[2]
         if row_num > no_lines:
##### page total & footer lines 
            yyy = "{:.2f}".format(m_pgprice) 
            st1  = " " * 34 + "Page Total : "+ yyy.rjust(12)
            x = st1
            pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
            x = pf1
            pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
#####Next Page jump & initialisation
            m_pgno += 1
            row_num = 0
            m_pgprice = float(0.00)
            pdf.add_page()
            pg_headr()

    yyy = "{:.2f}".format(m_pgprice) 
    st1  = " " * 34 + "Page Total : "+ yyy.rjust(12)
    x = st1
    pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
    x = rf1
    pdf.cell(120, 5, txt = x, ln = 1, align = 'L')
    y = "Print-of-Mobile-Table-Price-More-Than-Courier-120-5-F-"+s_font_name+"-"+str(m_price)+".pdf"
    print("Name of file = ", y)
    pdf.output(y)
except (Exception, Error) as error:
          print("Error while collecting records from PostgreSQL ", error)
finally:
       if connection:
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed after collecting records")

**Environment**
* OS (Windows 10 Home, Version : 21H2, fully updated)
* Python version 3.10.5150.1013, Date : 18/6/2022
* fpdf2  version 2.5.7
*** So far installed packages using pip
D:\SRIRAM\Projects\SVVSS\Self-Python>python -m pip list
Package            Version
------------------ ---------
cachetools         5.2.0
certifi            2022.6.15
chardet            3.0.4
charset-normalizer 2.1.1
click              8.1.3
colorama           0.4.5
defusedxml         0.7.1
fontstyle          1.0.1.2
fonttools          4.37.1
fpdf               1.7.2
fpdf2              2.5.7
future             0.18.2
googletrans        4.0.0rc1
h11                0.9.0
h2                 3.2.0
hpack              3.0.0
hstspreload        2022.9.1
httpcore           0.9.1
httpx              0.13.3
hyperframe         5.2.0
idna               2.10
libretranslatepy   2.1.1
lxml               4.9.1
pdfkit             1.0.0
pefile             2022.5.30
Pillow             9.2.0
pip                22.2.2
psgdemos           1.10.0
psycopg2           2.9.3
py2exe             0.11.1.0
PySimpleGUI        4.60.1
pywin32            304
reportbro-fpdf     1.7.11
requests           2.28.1
rfc3986            1.5.0
setuptools         58.1.0
six                1.16.0
sniffio            1.3.0
svg.path           6.2
tabulate           0.8.10
urllib3            1.26.12
win32printing      0.1.3

***

Font used : NotoSansTamil-Light.ttf 
This is in the same (local) path where my "Print_To_Pdf-From-Table-with-Header-Page-Control-with-Diff-Fonts.py" code is saved.
I use command-prompt window & run the code by : python Print_To_Pdf-From-Table-with-Header-Page-Control-with-Diff-Fonts.py

What **I need is given below from Word** (Screen Shot).  Tamil Letters appear correctly as it should be in row 5 highlighted in yellow. 

![image](https://user-images.githubusercontent.com/113674588/190611394-98c5a3c8-16f6-418f-a6d9-7f8f8c3ee65e.png)

Whereas the same row is appearing jumbled up in the PDF(screen shot) as shown below (Highlighted in yellow) :

![image](https://user-images.githubusercontent.com/113674588/190612035-fb48722e-3be6-4e1f-b131-31d401dd7f13.png)

As you can notice only the letters are jumbled up.    Alignment No issues... I can take care of.  
It is stored in the table properly as you can see in this screen shot [Mobile_Table Row 5 highlighted].
![image](https://user-images.githubusercontent.com/113674588/190614944-686eb67d-bc2e-45cd-aff7-b5fe4ce4f823.png)

I am aware of few deprecated codes used in the ".py" which I will modify suitably to fpdf2.  So no issues about this also. 

Sorry for giving more elaborate explanation.  Idea is to take as little time from you, as possible, for identification of my problem. 

I will be much obliged if any one of you can help me to sort out this (probably what I think as encoding) issue. 
Thanking you in advance.

**Comment by gmischler** [comment]
Thanks for the report.

As specificly mentioned in the [documentation](https://pyfpdf.github.io/fpdf2/Text.html#typographical-limitations), fpdf2 does not currently support the automatic ligatures required for most indic scripts, including tamil.

The issue #540 just below this one summarizes the problem, all the previous reports about it, and a possible solution. But it will likely take quite a while until this solution is actually implemented. Contributions by anyone with practical experience in this area would be highly appreciated.

**Comment by Sriram1958** [comment]
Thanks for the quick & meaningful response **gmishler**.  
Thanks for pointing out the correct areas of the documentation.  I should have read this prior to disturbing you. Sorry. 
Thanks for giving clarity that it will take quite sometime for fpdf2, to provide a solution,  in this regard.

Would like to bring to your notice that MS-Word does it efficiently as also the browsers.  

Thanks a lot once again.
