### ISSUE TITLE
Issues loading font file due to pickle error

### ISSUE THREAD

**Issue by Spider2themax** [PyFPDF/fpdf2#546]
Error here is relatively straightforward; attaching font file (had to zip it first, apparently ttf format cannot be uploaded direct to ticket) and code for reproducing error:

```
from fpdf import FPDF

pdf = FPDF()
fontfile = "PATHTOFILE/Arboria Black Italic.ttf"
pdf.add_font(family="Arboria Black Italic", fname=fontfile)
```

Error:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 7: invalid start byte
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<command-2214908067690151> in <module>
      2 
      3 pdf = FPDF()
      4 fontfile = "PATHTOFILE/Arboria Black Italic.ttf"
----> 5 pdf.add_font(family="Arboria Black Italic", fname=fontfile)

/local_disk0/.../lib/python3.8/site-packages/fpdf/fpdf.py in add_font(self, family, style, fname, uni)
    538             fontfile = open(fname)
    539             try:
--> 540                 font_dict = pickle.load(fontfile)
    541             finally:
    542                 fontfile.close()

/usr/lib/python3.8/codecs.py in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]
```

This error occured on a Databricks instance, but I also reproduced this in a terminal on my local Mac v12.5.1 and python3 3.8.6

[Arboria Black Italic.ttf.zip](https://github.com/PyFPDF/fpdf2/files/9592170/Arboria.Black.Italic.ttf.zip)

**Comment by gmischler** [comment]
> 539             try:
> --> 540                 font_dict = **pickle**.load(fontfile)
>     541             finally:

Fpdf2 hasn't been using pickle for quite a while, which means you're using a outdated version of the library.
Please update to the current version and try again.

**Comment by Spider2themax** [comment]
@gmischler thanks - this was absolutely the issue. stupid error on my part, thanks!
