### ISSUE TITLE
Doc: provide an example on how to combine usages of PyPDF2 & fpdf2

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#554]
We already have a page about [editing existing PDFs using `pdfrw` & `fpdf2`](https://pyfpdf.github.io/fpdf2/ExistingPDFs.html) in our documentation, and another one about [combining `borb` & `fpdf2`](https://pyfpdf.github.io/fpdf2/borb.html).

Given that [PyPDF2](https://github.com/py-pdf/PyPDF2) is a lot more popular that `pdfrw`, we could provide another documentation page about combining `PyPDF2` & `fpdf2`.

Practically, we could:
* copy `docs/ExistingPDFs.md` into `docs/CombineWithPyPDF2.md`, a new documentation page describing how to
    - open a PDF file with `PyPDF2` and edit it with `fpdf2`
    - create a PDF document `fpdf2` and edit it with `PyPDF2`
* rename `docs/ExistingPDFs.md` into `docs/CombineWithPdfrw.md`
* rename `docs/borb.md` into `docs/CombineWithBorb.md`

**Comment by ahadmushir** [comment]
Hello, 
I would like to work on this.

**Comment by Lucas-C** [comment]
> I would like to work on this.

Welcome @ahadmushir!
That's nice, feel free to submit a PR 😊
Is it your first FLOSS project contribution?
If so, you can find some guidelines there:
https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution

**Comment by ahadmushir** [comment]
If I understand the problem correctly, do we just need to rename the documentation filename? 
Or am I mistaken? @Lucas-C

**Comment by Lucas-C** [comment]
> If I understand the problem correctly, do we just need to rename the documentation filename?

No, the idea is to <ins>**add**</ins> some new documentation page about combining `PyPDF2` & `fpdf2`, which will require some testing first 😊
The _issue_ description is not clear enough? If so, do you have questions to clarify things?

**Comment by ahadmushir** [comment]
> > If I understand the problem correctly, do we just need to rename the documentation filename?
> 
> No, the idea is to **add** some new documentation page about combining `PyPDF2` & `fpdf2`, which will require some testing first 😊 Maybe the _issue_ description is not clear enough? If so, do you have questions to clarify things?

Ok, now I understand. Thanks for the clarification 😊

**Comment by Lucas-C** [comment]
I'm reopening this.

A page has a been initialized by @devdev29: https://pyfpdf.github.io/fpdf2/CombineWithPyPDF2.html
That's great!

As mentioned in the initial issue description, it would also be interesting to have some documentation on how to **create a PDF document with `fpdf2` and edit it with `PyPDF2`**
PRs are welcome to add a section about this in `docs/CombineWithPyPDF2.md`
