### ISSUE TITLE
'FPDF' object has no attribute  'write_html'

### ISSUE THREAD

**Issue by antusystem** [PyFPDF/fpdf2#560]
Hi, I running the example [here](https://pyfpdf.github.io/fpdf2/HTML.html) to write html to PDF, but I get this error:

`AttributeError: 'FPDF' object has no attribute 'write_html'
`

The code I'm using is literally the one in the page of the example:

```
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.write_html("""
  <dl>
      <dt>Description title</dt>
      <dd>Description Detail</dd>
  </dl>
  <h1>Big title</h1>
  <section>
    <h2>Section title</h2>
    <p><b>Hello</b> world. <u>I am</u> <i>tired</i>.</p>
    <p><a href="https://github.com/PyFPDF/fpdf2">PyFPDF/fpdf2 GitHub repo</a></p>
    <p align="right">right aligned text</p>
    <p>i am a paragraph <br />in two parts.</p>
    <font color="#00ff00"><p>hello in green</p></font>
    <font size="7"><p>hello small</p></font>
    <font face="helvetica"><p>hello helvetica</p></font>
    <font face="times"><p>hello times</p></font>
  </section>
  <section>
    <h2>Other section title</h2>
    <ul><li>unordered</li><li>list</li><li>items</li></ul>
    <ol><li>ordered</li><li>list</li><li>items</li></ol>
    <br>
    <br>
    <pre>i am preformatted text.</pre>
    <br>
    <blockquote>hello blockquote</blockquote>
    <table width="50%">
      <thead>
        <tr>
          <th width="30%">ID</th>
          <th width="70%">Name</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>Alice</td>
        </tr>
        <tr>
          <td>2</td>
          <td>Bob</td>
        </tr>
      </tbody>
    </table>
  </section>
""")
pdf.output("html.pdf")
```
I'm on _Linux Mint 21_ with a _Conda_ environment with _Python v3.10.5_ installing the dependencies with _Python Poetry v1.2.1_ with _fpdf2 v2.5.7_. This is my pyproject.toml:

```
[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
readme = "README.md"
packages = [{include = "demo"}]

[tool.poetry.dependencies]
python = "^3.8"
openpyxl = "^3.0.10"
loguru = "^0.6.0"
playwright = "^1.26.0"
"pdfminer.six" = "^20220524"
PyMuPDF = "^1.20.2"
pandas = "^1.5.0"
fpdf2 = "^2.5.7"
Markdown = "^3.4.1"

[tool.poetry.group.development.dependencies]
pytest = "^7.1.3"
pylama = {extras = ["all"], version = "^8.4.1"}
bandit = "^1.7.4"
flake8-black = "^0.3.3"
flake8-bugbear = "^22.4.25"
flake8-import-order = "^0.18.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
Hope someone can help me, thanks.

**Comment by antusystem** [comment]
Thanks, that worked, though, I had to execute ` poetry remove fpdf2` because I don't remember how to install that way packages with Poetry, but it worked installing with the pip line you send. Thanks

**Comment by Lucas-C** [comment]
Sorry about this @antusystem, this is a recurring issue with our documentation at https://pyfpdf.github.io/fpdf2/ being about the code on the `master` code of this repo, not about the latest `fpdf2` release.

`HTMLMixin` has just been deprecated, _cf._ https://github.com/PyFPDF/fpdf2/blob/master/CHANGELOG.md#deprecated & #543

You can find some documentation on how to use `write_html()` with the latest `fpdf2` release here: https://github.com/PyFPDF/fpdf2/blob/2.5.7/docs/HTML.md

**Comment by antusystem** [comment]
Yes, this issue is closed. Thankss

**Comment by VCDragoon** [comment]
@Lucas-C @antusystem Just came here to say I hit this same issue going through the tutorials, from a fresh install of `pip install fpdf2`.  

The solution provided above worked, `pip uninstall fpdf2` and then `pip install git+https://github.com/PyFPDF/fpdf2.git@master` - but I had to hunt a little bit for it here.

Would recommend adding a note to the tutorial in that section, or even a link to this issue - if I have some time I'll look into making a PR on the doc build.  That is until the recurring issue of the release build is resolved!

**Comment by Lucas-C** [comment]
Sorry for the annoyance @VCDragoon.

I wanted to wait for a new major feature, like linearization or encryption, before publishing a new release.
I ended up making a new release today, so this specific issue should not bother anyone.
