### ISSUE TITLE
Add a FPDF.polyline method

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#58]
Inpiration could be taken from the existing [`line(x1, y1, x2, y2)` method](https://github.com/PyFPDF/fpdf2/blob/2.2.0/fpdf/fpdf.py#L470).

The table 4.9 of the [PDF 1.7 spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) should also be helpful

Adding this method will bring us one step further to map SVG primitives like `polyline` or `path`

An additional method `polygon` could also be added, that auto-join the start & end points, and fill the enclosed area using the `f` PDF operator.

**Comment by uovodikiwi** [comment]
Hi @Lucas-C, nice to meet you! I would like to contribute on the project :) I've recently forked it and worked on this issue in my local env. I didn't see that @alexanderankin was already assigned to this task but if they haven't started working on this I could create a PR for this in the following days :)

**Comment by Lucas-C** [comment]
Nice!

Welcome & thanks for contributing @uovodikiwi!

Feel free to submit a PR 😊

Ping @alexanderankin: can you confirm that's OK with you ?

**Comment by alexanderankin** [comment]
yes absolutely!
