### ISSUE TITLE
Is it possible to represent text inside a "box" in a specific position?

### ISSUE THREAD

**Issue by TeoColuccio** [PyFPDF/fpdf2#580]
The most suitable function seems to be .multi_cell(), but with this I can't set the coordinates on the y axis.
In fact I'm trying to set the "h" parameter, but this goes to set the height of the single cell (hence also the distance between them), and not where the text is to be printed.

**Comment by Lucas-C** [comment]
Hi @TeoColuccio!
Could you provide some <ins>minimal</ins> code describing what you are trying to achieve?
Maybe your problem is similar to issue #210?

**Comment by TeoColuccio** [comment]
Basically, what I would like to be able to do is insert a text box in a sheet position that I specify. As in this example created manually:
![es](https://user-images.githubusercontent.com/16000669/195698017-2a770862-0764-4b22-8e32-30d7be807929.png)

**Comment by TeoColuccio** [comment]
Ok, 

`
txt = """ 
Laborum ut aute occaecat laboris cupidatat sit. Cupidatat irure excepteur id labore sunt velit. Laborum in sit pariatur aliqua enim dolore sint nostrud eiusmod ex sunt elit. Enim ipsum sint reprehenderit laboris incididunt consequat amet ullamco laborum cillum nulla elit esse.

Sint occaecat aliqua do irure cupidatat et excepteur. Sint nisi do in ipsum irure. Elit sit quis enim commodo aliquip laborum ex pariatur elit anim id velit anim. Exercitation veniam id irure enim dolore ad enim elit. Non in est est excepteur.
"""

pdf.set_x(100)
pdf.set_y(100) 

print(pdf.get_x(), pdf.get_y())
pdf.multi_cell(w=x2-x1, 
               txt=txt)
`
Now the problem is that the .set_x () doesn't seem to work. Whatever value I enter, when I call get_x (), it always returns 9.999999999999998. Maybe it's a bug !?

**Comment by gmischler** [comment]
> Maybe it's a bug !?

No, it's working perfectly just as designed and documented.
While you were looking the other way, this happened (the very first sentence):

[set_y(y)](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_y)

    Moves the current abscissa back to the left margin and sets the ordinate.
    If the value provided is negative, it is relative to the bottom of the page.
    Args

    y : float
        the new current ordinate 

This behaviour may be somewhat surprising given the method name, but it has historical reasons and can't easily be changed without breaking a lot of existing code.
So either you need to switch the order of your `.set_x()` and `.set_y()` calls, or indeed use `.set_xy()`, which internally does exactly that.

**Comment by TeoColuccio** [comment]
> > Maybe it's a bug !?
> 
> No, it's working perfectly just as designed and documented. While you were looking the other way, this happened (the very first sentence):
> 
> [set_y(y)](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_y)
> 
> ```
> Moves the current abscissa back to the left margin and sets the ordinate.
> If the value provided is negative, it is relative to the bottom of the page.
> Args
> 
> y : float
>     the new current ordinate 
> ```
> 
> This behaviour may be somewhat surprising given the method name, but it has historical reasons and can't easily be changed without breaking a lot of existing code. So either you need to switch the order of your `.set_x()` and `.set_y()` calls, or indeed use `.set_xy()`, which internally does exactly that.

Ok I understand. But in fact set_xy () works perfectly and so I can also close the issue.

**Comment by Lucas-C** [comment]
Great!
Thank you for your help @gmischler 😊
