### ISSUE TITLE
Image is drawn on different position related to width, although x and y cords are supplied 

### ISSUE THREAD

**Issue by S0PEX** [PyFPDF/fpdf2#597]
Hey,

currently building a script that gets data from our database and creates a PDF table.
In this table, I need to insert .png files and resize them to fit a cell.
On paper, this cell is 4.85 cm x 2.54 cm, so I would like to resize the image to the same size and insert into cell `x`.
Based on this, the insert logic should look something like this:
```python
# Create PDF with margins
margin_top, margin_left, margin_right = (21.5, 9.8, 0.9)
pdf = FPDF(unit='mm')
pdf.set_margins(margin_left, margin_top, margin_right)
pdf.set_font('Helvetica', style='B', size=10)

# Create image
code = 'DUMMY TEXT'
image = code128.image(code)

# Cell information
cell_width, cell_height = (48.5, 25.4)

# Create PDF table
pdf.add_page()
for i in range(40):
    pdf.image(image,
                x=margin_left + cell_width * (i % 4),
                y=margin_top + cell_height * (int(i / 4)),
                w=cell_width,
                h=cell_height
                )
````

When I now change `code` I would imagine that the image is drawn (started) at position the supplied `x, y`. 
But the image start position changes based on the image input width, although resized with `w,h`.
Do you have any idea how I could fix this?

Regards Artur

**Comment by Lucas-C** [comment]
I adapted your code a little bit to demonstrate that everything works fine with `fpdf2`:
```python
from fpdf import FPDF
import code128

# Create PDF with margins
margin_top, margin_left, margin_right = (21.5, 9.8, 0.9)
pdf = FPDF(unit='mm')
pdf.set_margins(margin_left, margin_top, margin_right)

# Cell dimensions
cell_width, cell_height, cell_margin = (40, 25, 5)

# Create image & PDF table:
image = code128.image('DUMMY TEXT')
pdf.add_page()
for i in range(12):
    x = margin_left + (cell_width + cell_margin) * (i % 4)
    y = margin_top + (cell_height + cell_margin) * (i // 4)
    pdf.image(image, x=x, y=y, w=cell_width, h=cell_height)

# Testing alt text:
image = code128.image('DUMMY TEXT ALT')
pdf.add_page()
for i in range(12):
    x = margin_left + (cell_width + cell_margin) * (i % 4)
    y = margin_top + (cell_height + cell_margin) * (i // 4)
    pdf.image(image, x=x, y=y, w=cell_width, h=cell_height)

pdf.output("issue-597.pdf")
```

With `DUMMY TEXT ALT`, the 12 barcodes generated on the second page are different than the ones on the first page.

By the way, would you be open to submit a PR with an example on how to combine `code128` & `fpdf2`?
* https://pyfpdf.github.io/fpdf2/Barcodes.html
* [docs/Barcodes.md](docs/Barcodes.md)

**Comment by S0PEX** [comment]
Hey, thanks for the response. Are the x and y positions in mm, or which unit is used?
`margin_top, margin_left, margin_right = (21.5, 9.8, 0.9)` are mm values extracted from Word.
When I check the cells from Word and generated output, they are off by a couple of mm.
The `y` also has an increasing error for each new row. Not really sure where this is coming from.

I can account for that and adjust the margins, but not really sure where these offset is coming from.
[raster.pdf](https://github.com/PyFPDF/fpdf2/files/9873009/raster.pdf)

This is how I overlay both PDFs to get a combined one:
```python
import os
from pathlib import Path
from turtle import width
from fpdf import FPDF
import code128
from PyPDF2 import PdfFileReader, PdfFileWriter


def create_final_pdf(pdf: FPDF, path: Path):
    # Write temp pdf
    temp_pdf_path = path.parent.joinpath('temp.pdf')
    pdf.output(temp_pdf_path)

    # Load raster
    with open(path.parent.joinpath('raster.pdf'), 'rb') as raster_pdf:
        raster_pdf_reader = PdfFileReader(raster_pdf)

        # Merge pdf pages
        with open(temp_pdf_path, 'rb') as temp_pdf:
            # merge pdfs
            tmp_pdf_reader = PdfFileReader(temp_pdf)
            pdf_writer = PdfFileWriter()
            for i in range(0, tmp_pdf_reader.getNumPages(), 2):
                page = tmp_pdf_reader.getPage(i)
                page.mergePage(tmp_pdf_reader.getPage(i + 1))
                page.mergePage(raster_pdf_reader.getPage(0))
                pdf_writer.addPage(page)
            with open(path, "wb") as outputPdf:
                pdf_writer.write(outputPdf)
    os.remove(temp_pdf_path)


if __name__ == "__main__":
    # Create PDF with margins
    margin_top, margin_left, margin_right = (21.5, 9.8, 0.9)
    pdf = FPDF(unit='mm')
    pdf.set_margins(margin_left, margin_top, margin_right)

    # Cell dimensions
    cell_width, cell_height, cell_margin = (48, 25, 1)

    # Create image & PDF table:
    image = code128.image('DUMMY TEXT')
    pdf.add_page()
    for i in range(12):
        x = margin_left + (cell_width + cell_margin) * (i % 4)
        y = margin_top + (cell_height + cell_margin) * (i // 4)
        pdf.image(image, x=x, y=y, w=cell_width, h=cell_height)
    pdf.add_page()

    create_final_pdf(pdf, Path('output.pdf'))
```

Top:
![image](https://user-images.githubusercontent.com/1359645/198116071-1e54e8f2-f7dc-4d79-84b1-14c83edf25e4.png)

Bottom:
![image](https://user-images.githubusercontent.com/1359645/198116151-7a4a2e53-4e36-42ed-adb2-174ae0031bbc.png)

Regarding `code128` & `fpdf2`, I am happy to submit a PR once I got this generation working.

**Comment by Lucas-C** [comment]
> Hey, thanks for the response. Are the x and y positions in mm, or which unit is used?

The default unit is `mm`: https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF

>  When I check the cells from Word and generated output, they are off by a couple of mm.

This may be due to differing margins, or a different page format:
https://github.com/PyFPDF/fpdf2/blob/2.5.7/fpdf/fpdf.py#L105
I couldn't say for sure as I cannot compare with the Word document you mentioned 😊

> Regarding `code128` & `fpdf2`, I am happy to submit a PR once I got this generation working.

Awesome ! 🥳

**Comment by S0PEX** [comment]
Thanks for the info regarding the page format dimensions. I will check tomorrow once I am on Windows again.
Really appreciate your help.

Cheers

**Comment by Lucas-C** [comment]
> Really appreciate your help

You're welcome!
Good luck with your scripts 🤞
