### ISSUE TITLE
How to add watermarks on pdf?

### ISSUE THREAD

**Issue by rngallen** [PyFPDF/fpdf2#598]
Currently am creating my pdfs using fpdf2 but for some reason some of them should have watermark 

How to implement watermarks when creating pdfs?

**Comment by Lucas-C** [comment]
Hi @rngallen

Does this example answer your question?
https://github.com/digidigital/Extensions-and-Scripts-for-pyFPDF-fpdf2/blob/main/README.md#stamp-and-watermark-pdf-files
