### ISSUE TITLE
Add a FPDF.text_annotation method

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#60]
Section 12.5 of the [PDF 1.7 spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) should be helpful in implementing this.

It would be especially useful to add a documentation page indicating how to add such text annotations on an existing PDF.

**Comment by alexanderankin** [comment]
Graphics state? What will this method do?

**Comment by Lucas-C** [comment]
Wrong section sorry, it's in 12.5

This method would simply add a textual annotation on a range of text in the document.

**Comment by Lucas-C** [comment]
Note: _Link Annotations_ are already used in `FPDF._putpages` to render links

**Comment by Lucas-C** [comment]
A PR is on the way to implement this: https://github.com/PyFPDF/fpdf2/pull/134
