### ISSUE TITLE
Is it possible to create a shape relative to a cell?

### ISSUE THREAD

**Issue by MaKaNu** [PyFPDF/fpdf2#606]
So the title already mentions what my intention is. In detail, I like to have a shape (specific a line) which is positioned relative to a `cell` or `multicell`, so if the cell is moving the shape also gets a new position. My workaround for the moment is to position the cells first and than the shapes afterwards by hardcoding the position.

**Comment by gmischler** [comment]
> ...so if the cell is moving the shape also gets a new position.

What do you mean by "moving" a cell? As far as I'm aware, fpdf2 doesn't currently support animated content.

Can you be a bit more specific about what exactly you are trying to do?

**Comment by MaKaNu** [comment]
You are right about animations. That is not what my intention was. with moving I want to say I change manually the values of the position of a cell and my line is logical connected to cell but not programmatically.

**Comment by andersonhc** [comment]
You can use get_x() and get_y() to save the coordinates when you insert the cell, then you use the values to position your line.

Depending you what you need maybe this line can be drawn as cell border - that would be even easier.

**Comment by MaKaNu** [comment]
That sounds like the thing I was looking for, and you are right about the cell border I just used until now the `border=1` didn't recognized what is possible with strings. Now I understand why `str` is a possible type.

**Comment by MaKaNu** [comment]
Was exactly what I was looking for. maybe an addition in the tutorials would be nice.

**Comment by Lucas-C** [comment]
@all-contributors please add @andersonhc for question

**Comment by Lucas-C** [comment]
GLad you found what you were looking for @MaKaNu!
If you want to improve the docs regarding this, that's great! Feel free to submit a PR 😊

And thank you @andersonhc for helping here!
