### ISSUE TITLE
Add html <line-height> tag support

### ISSUE THREAD

**Issue by Bubbu0129** [PyFPDF/fpdf2#622]
**Please explain your intent**
The html to pdf functionality lacks support of line-height adjusting.

**Describe the solution you'd like**
I have read some parts of the documentation, but fails to find any reference to line height settings. Maybe there is one, but I didn't found it. 
Setting default line height while `setfont()` is also desired, though I consider it harder to implement.

**Additional context**
I'm willing to launch a PR to this issue. Let me know what think about this feature!

**Comment by Lucas-C** [comment]
>  The html to pdf functionality lacks support of line-height adjusting.

This is true. Related code:

* `self.h` is currently used in most places to set the vertical height of content produced by `HTML2FPDF`: https://github.com/PyFPDF/fpdf2/blob/2.6.0/fpdf/html.py#L326
* table row heights are defined with another property: https://github.com/PyFPDF/fpdf2/blob/2.6.0/fpdf/html.py#L254
