### ISSUE TITLE
DocumentState removed in 2.6.X

### ISSUE THREAD

**Issue by PhillCli** [PyFPDF/fpdf2#623]
DocumentState was removed from fpdf.enums in 2.6.X

**Minimal code**
```python
from fpdf.enums import DocumentState
```

**Environment**
* Linux
* Cpython3.7
* `fpdf2` version used `2.6.0`

Removed in [this](https://github.com/PyFPDF/fpdf2/commit/1a8dcd6d779aa72c31260218706d82428b4a87cf)  commit.
That's a breaking change not mentioned in the release log. A genuine question is fpdf2 following SemVer? I would like to know how to pin the version for the future.

Our custom logic around merging PDFs, was checking if the pdf was already saved, 
with:
```python
        # guard against non-saved state
        if self.pdf.state != DocumentState.CLOSED:
             pass
```
any tips on how to check that in `2.6.0`?

**Comment by Lucas-C** [comment]
This change has been documented there: https://github.com/PyFPDF/fpdf2/blob/master/CHANGELOG.md#removed
Sorry that this was a breaking change for you.

You can replace your original code by this snippet:
```python
if self.buffer:
     # document is closed, PDF content has already been generated into self.buffer
```
