### ISSUE TITLE
Question: Possibilty of WordWrap while represent data in Tabular format.

### ISSUE THREAD

**Issue by sree293** [PyFPDF/fpdf2#63]
Hii,
I am using fpdf2 and trying to write data into pdf in Tabular format. But if the length of the Table cell is less than the length of the text(string), data is overlapping with the content of another cell.Is there any way I use word wrap and have data in the next line instead of overlapping with adjacent cell content?

I have attached my test code and generated pdf files for reference and better explanation.
 
I know it is asking a lot but if this can be done I think it will make fpdf2 a formidable pdf writer tool.

Thanks in advance

Sree Harsha

[wordwrap.zip](https://github.com/PyFPDF/fpdf2/files/5829245/wordwrap.zip)

**Comment by Lucas-C** [comment]
Hi!

I had a look at your code, and I think the solution for you is to use the `multi_cell` method:
https://pyfpdf.github.io/fpdf2/reference/multi_cell.html

There is your code adapted for using it:

```python
from fpdf import FPDF
 
pdf=FPDF(format='letter', unit='in')
pdf.add_page()
 
# Effective page width, or just epw
epw = pdf.w - 2*pdf.l_margin
 
# Set column width to 1/4 of effective page width to distribute content 
# evenly across table and page
col_width = epw/4
 
# Since we do not need to draw lines anymore, there is no need to separate
# headers from data matrix.
data = [
    ['First name','Last name','Age','City'],
    ['Juleskfgjhfdkgfdhkghfdghfd;grdfgdfhghf','Smith',34,'San Juan'],
    ['Marydgfsfsfgdgvfdggfd','Ramos',45,'Orlando'],
    ['Carlsonfdgfdgsfdxhfggjdfgfgu','Banks',19,'Los Angeles']
]
 
# Document title centered, 'B'old, 14 pt
pdf.set_font('Times', 'B', 14) 
pdf.cell(epw, 0, 'Demographic data', align='C')
pdf.set_font('Times', size=10)
pdf.ln(0.5)

# Text height is the same as current font size
th = pdf.font_size * 2
 
for row in data:
    for datum in row:
        # Enter data in colums
        # Notice the use of the function str to coerce any input to the 
        # string type. This is needed since pyFPDF expects a string, not a number.
        pdf.multi_cell(col_width, th, str(datum), border=1, ln=0)
    pdf.ln(th)
 
# Line break equivalent to 4 lines
pdf.ln(4*th)
 
pdf.set_font('Times', 'B', 14)
pdf.cell(epw, 0, 'With more padding', align='C')
pdf.set_font('Times', size=10)
pdf.ln(0.5)
 
# Here we add more padding by passing 2*th as height
for row in data:
    for datum in row:
        # Enter data in colums
        pdf.multi_cell(col_width, 2*th, str(datum), border=1)
    pdf.ln(2*th)
 
pdf.output('wordwrap.pdf')
```

There are still issues remaining though:
- you will be impacted by this bug I found this morning: https://github.com/PyFPDF/fpdf2/issues/66. A PR has already been submitted to solve it.
- `FPDF.multi_cell` is not currently a drop-in replacement for `FPDF.cell`.
I am working on improving this, and I'll provide more information soon.

**Comment by Lucas-C** [comment]
Working on this in https://github.com/PyFPDF/fpdf2/pull/76

**Comment by Lucas-C** [comment]
PR #76 is ready.

Tests have been added, including one replicating what you were trying to achieve @sree293:
https://github.com/PyFPDF/fpdf2/blob/623ba13eaaf5cc7e06bfb5bf10bcd8e1b2de49c9/test/cells/test_multi_cell.py#L84

You can install the version from this branch this way, if you want to test it out:

    pip install git+https://github.com/PyPDF/fpdf2.git@multi_cell_ln3

**Comment by Lucas-C** [comment]
Closing this now that #76 has been merged
