### ISSUE TITLE
<img> without "height" attribute fails to leave enough blank space for itself

### ISSUE THREAD

**Issue by Bubbu0129** [PyFPDF/fpdf2#632]
Describe the bug

**Error details**
In `write_html()`, `<img>` without "`height`" attribute will not leave enough blank space for itself. As a result, following contents overlaps with the image.

**Minimal code**
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.write_html("""<img src="/path/to/img" width="500">
<p>text</p>
""")
pdf.output("issue_632.pdf")

```

**Environment**
* OS (Linux i686)
* Python version: 3.9.2
* `fpdf2` version: Latest

If necessary, I am ready to launch a PR to fix this.

**Comment by Lucas-C** [comment]
Thank you for reporting this @Bubbu0129!

Would you like to submit a PR in order to fix this?

**Comment by Lucas-C** [comment]
@allcontributors please add @Bubbu0129 for bug
