### ISSUE TITLE
Unsupport upper case font file name

### ISSUE THREAD

**Issue by CY-Qiu** [PyFPDF/fpdf2#638]
**Error details**
ValueError: Unsupported font file extension: .TTF. add_font() used to accept .pkl file as input, but for security reasons this feature is deprecated since v2.5.1 and has been removed in v2.5.3.

**Minimal code**
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_font("simsun", fname="fonts/SIMSUN.TTF", uni=True)
```

**Environment**
`fpdf2` version 2.6.0

**fix way**
I checked `fpdf.py`, line 1701 should be changed to the following code ,then this bug can be fixed.
```python
ext = splitext(str(fname))[1].lower()
```

**Comment by Lucas-C** [comment]
Thank you for the report @CY-Qiu!

This is indeed a bug.

Would you like to submit a PR to fix this? 😊

**Comment by Lucas-C** [comment]
@allcontributors please add @CY-Qiu for bug
