### ISSUE TITLE
Outputting pdf to a specific destination

### ISSUE THREAD

**Issue by muffymn** [PyFPDF/fpdf2#642]
How does one output a generated pdf to a specific directory/destination since the destination parameter on the output method seems to have been [DEPRECATED since 2.3.0]

**Comment by Lucas-C** [comment]
The very first example in thi project README shows an example of doing so...
https://github.com/PyFPDF/fpdf2

As well as the [Pypi page](https://pypi.org/project/fpdf2/) and the tutorial from the documentation:
https://pyfpdf.github.io/fpdf2/Tutorial.html

The `dest` parameter is deprecated, but not the `name` one:
https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.output

**Comment by Lucas-C** [comment]
Given that you added a thumb-up to my answer @muffymn,
I'm going to close this issue now 😃
