### ISSUE TITLE
Generate an empty line if one long line begin with some spaces

### ISSUE THREAD

**Issue by CY-Qiu** [PyFPDF/fpdf2#649]
**Error details**
Generate an empty line if one long line begin with some spaces.
This is the current output:
![image](https://user-images.githubusercontent.com/23075447/209785612-28622b57-9bf1-44e6-b52e-ebbc6dbba2d7.png)
This is what we want:
![image](https://user-images.githubusercontent.com/23075447/209785817-951806c8-844e-4281-b205-52b74841cb70.png)

**Minimal code**
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_text_color(0, 0, 0)
pdf.add_font(family="simsun", fname="/usr/share/fonts/simsun.ttf", uni=True)
pdf.set_font("simsun", size=10)
text = "       鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美"
pdf.multi_cell(w=150, txt=text, border=1, fill=False, split_only=False)
pdf.output("test.pdf")
```

**Environment**
* `fpdf2` version used: 2.6.0

I checked the code, it seems that `line_break.py` needs some changes to make the spaces in the beginning of one line being ignored.

**Comment by Lucas-C** [comment]
Thank you for opening this issue @CY-Qiu 😃 

However, I'm not sure that this is really a bug with `fpdf2`...

Users can call [`str.strip()`](https://www.w3schools.com/python/ref_string_strip.asp) themselves on the text input passed to `.cell()` / `.multi_cell()`.

**Comment by CY-Qiu** [comment]
The reason I add some spaces is I need indentation.
In the current design of fpdf2, It seems that add some spaces in the beginning of one sentence is the only choice.
So I cannot use strip to delete the spaces.

**Comment by Lucas-C** [comment]
Oh OK, I initially misunderstood...

Ping @gmischler as I think you have more expertise regarding this than myself 😃 

Do you think that `fpdf2` could/should honor leading whitespaces in `.cell()` / `.multi_cell()`?

**Comment by gmischler** [comment]
An interesting case!

The reason for the current behaviour is in the "line wrapping by word" algorithm, which assumes that words are seperated by space characters. In our case here, the supplied "word" does not fit on one line, so `multi_cell()` will perform a line break at the most recent space character.
This is evidently inconvenient for chinese writing (and japanese, possibly others), which does not usually seperate words with spaces, but places all the characters right after each other.

The most correct solution would be for fpdf2 to offer an alternative "line wrapping by character" algorithm. I don't think that would be very hard to implement (just skip the space and hyphen hinting), but we need to think a bit about what the best API for that would be.

> Do you think that fpdf2 could/should honor leading whitespaces in .cell() / .multi_cell()?

Of course it should. The task of fpdf2 is to render the characters supplied by the client code, and not to alter them (unless explicitly specified). And that is exactly what happens here too: Those space characters are represented by the initial empty line. If the rest of the text was short enough to fit that line, it would continue right after that indent as expected.

On the other hand: Is ist a good idea to use space characters for a first-line indent?
In general typographical terms, doing so is not usually encouraged.
With `mult_cell()`, it is currently the only way, though. A `first_line_indent=x` feature could be another enhancement idea.
With `write()`, you could just move `pdf.x` to the indented position any time you start a new paragraph, as long as you're happy to have your text left aligned (for now, anyway).
