### ISSUE TITLE
Doc: provide an usage example  of combining fpdf2 with Pygal

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#652]
We already have a page about [Charts & graphs](https://pyfpdf.github.io/fpdf2/Maths.html) in our documentation, and other ones about combining `fpdf2` with other libs.

[Pygal](https://www.pygal.org/) seems like a great charting library that can can produces SVG, even if it has received [zero development updates for a year now](https://github.com/Kozea/pygal/issues/520).

It would be interesting to provide a documentation section on how to generate a chart with `Pygal` and embed it in `fpdf2`.

---

By implementing this feature you, as a benevolent [FLOSS](https://en.wikipedia.org/wiki/Free/libre_and_open-source_software) developper, will provide access to the large community of fpdf2 users to a useful PDF functionality.
As a contributor you will get review feedbacks from maintainers & other contributors, and learn about the lifecycle & structure of a Python library on the way.
You will also be added into the [contributors list & map](https://github.com/PyFPDF/fpdf2#contributors-).

This issue can count as part of [hacktoberfest](https://hacktoberfest.com)

**Comment by ssavi-ict** [comment]
Hi @Lucas-C , Would like to contribute in this issue as well.

**Comment by Lucas-C** [comment]
> Hi @Lucas-C , Would like to contribute in this issue as well.

You are very welcome to do so!
Have you started to experiment with `Pygal`?

This task should be very similar to your great work on PR #746,
but this time the new section should be added to https://github.com/PyFPDF/fpdf2/blob/master/docs/Maths.md

**Comment by Lucas-C** [comment]
> Hi @Lucas-C , Would like to contribute in this issue as well.

You are very welcome to do so!
Have you started to experiment with `Pygal`?

This task should be very similar to your great work on PR #746,
but this time the new section should be added to https://github.com/PyFPDF/fpdf2/blob/master/docs/Maths.md

**Comment by ssavi-ict** [comment]
@Lucas-C, Yeah, I started reading some basic snippets using `Pygal`. I hope I can do this soon. 

> but this time the new section should be added to https://github.com/PyFPDF/fpdf2/blob/master/docs/Maths.md

How I understood this line is - I need to generate a demo chart using `Pygal`, embed it in `fpdf2`, and also provide some documentation. Like, in the section(s) [`Using Matplotlib`](https://pyfpdf.github.io/fpdf2/Maths.html#using-matplotlib), [`Using Pandas`](https://pyfpdf.github.io/fpdf2/Maths.html#using-pandas) section did.

Am I correct?

**Comment by Lucas-C** [comment]
> How I understood this line is - I need to generate a demo chart using `Pygal`, embed it in `fpdf2`, and also provide some documentation. Like, in the section(s) [`Using Matplotlib`](https://pyfpdf.github.io/fpdf2/Maths.html#using-matplotlib), [`Using Pandas`](https://pyfpdf.github.io/fpdf2/Maths.html#using-pandas) section did.

You do not need to "embed" it in `fpdf2`, only to produce some documentation 😊

> The new section will be - `Using Pygal` and it will take place after the [`Using Plotly`](https://pyfpdf.github.io/fpdf2/Maths.html#using-plotly) section.

Exactly!

**Comment by ssavi-ict** [comment]
Hi @Lucas-C , I have tried almost everything in my mind. It comes down to the following. I found only one way to do that using `pygal` and `fpdf2`. It takes more time than I really expect and I do not really like it.

```python
import pygal
from reportlab.graphics import renderPM
from svglib.svglib import svg2rlg
from fpdf import FPDF

# Create a Pygal bar chart
bar_chart = pygal.Bar()
bar_chart.title = 'Sales by Year'
bar_chart.x_labels = ['2016', '2017', '2018', '2019', '2020']
bar_chart.add('Product A', [500, 750, 1000, 1250, 1500])
bar_chart.add('Product B', [750, 1000, 1250, 1500, 1750])

# Render the chart to an SVG and PNG file
bar_chart.render_to_file('bar_chart.svg')
drawing = svg2rlg("bar_chart.svg")
renderPM.drawToFile(drawing, "bar_chart.png")

# Set the position and size of the image in the PDF
x = 50
y = 50
w = 100
h = 70

pdf = FPDF()
pdf.add_page()
pdf.image('bar_chart.png', x=x, y=y, w=w, h=h)
pdf.output('bar_chart_pdf.pdf')
```
I tried with the SVG file generated by the `pygal`. The `fpdf2` generates a black rectangular shape on the PDF. I tried several other ways. It returns the same. Will the above implementation be enough? or do you have any ideas other than this? You can try with the following implementation - 

```python
import pygal
from reportlab.graphics import renderPM
from svglib.svglib import svg2rlg
from fpdf import FPDF

# Create a Pygal bar chart
bar_chart = pygal.Bar()
bar_chart.title = 'Sales by Year'
bar_chart.x_labels = ['2016', '2017', '2018', '2019', '2020']
bar_chart.add('Product A', [500, 750, 1000, 1250, 1500])
bar_chart.add('Product B', [750, 1000, 1250, 1500, 1750])


# Render the chart to an SVG file
bar_chart.render_to_file('bar_chart.svg')

# Set the position and size of the image in the PDF
x = 50
y = 50
w = 100
h = 70

pdf = FPDF()
pdf.add_page()
pdf.image('bar_chart.svg', x=x, y=y, w=w, h=h)
pdf.output('bar_chart_pdf.pdf')
```
I also tried the `render_to_png()` method from `pygal`. It requires the `CairoSVG` library which is a bit problematic in Windows. Also need some DLLs to run the method.

Please let me know any queries.

**Comment by Lucas-C** [comment]
Thank you for your research @ssavi-ict!

It seems that Pygal introduces `<style>` & `<script>` elements to the SVG images it produces:
https://github.com/Kozea/pygal/blob/3.0.0/pygal/svg.py#L449

Sadly, `fpdf2` does not currently support those:
https://pyfpdf.github.io/fpdf2/SVG.html#currently-unsupported-notable-svg-features

As a consequence, I fear that we won't be able to embed Pytgal graphs as SVG in PDF documents produced by `fpdf2` 😞

Hence, you approach of embedding charts in a rasterized format seems like the best to me.

However, to convert SVG to a raster image, I don't think that installing reportlabs is needed.
Pygal actually suggests using the `cairosvg` library: https://github.com/Kozea/pygal/blob/3.0.0/pygal/graph/public.py#L116
We could even suggest to do the conversion in-memory, without writing anything to disk:
```python
img = BytesIO()
cairosvg.svg2png(bar_chart.render(), write_to=img)
pdf.image(img)
```

Do you feel that you have enough information to start a Pull Request @ssavi-ict? 😊

**Comment by ssavi-ict** [comment]
@Lucas-C , I tried that also.
```
img = BytesIO()
cairosvg.svg2png(bar_chart.render(), write_to=img)
pdf.image(img)
```
For this, `cairosvg` (`pip install cairosvg`) installations and importing will be required. Along with that if a user uses a windows PC (not sure about another environment) (s)he needs to install `GTK` (Gnome Toolkit) which can be found [Here](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases). 

I think we should provide both the solutions with enough explanations (I am OK with that). User can choose based on the requirements. Let me know what you think? 

I will provide the Doc after that. Thank you for the suggestion.

**Comment by Lucas-C** [comment]
Yes, explaining how to perform the SVG conversion to PNG with both libraries seem like a good idea!
