### ISSUE TITLE
Doc: provide an usage example of combining fpdf2 with Plotly

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#653]
We already have a page about [Charts & graphs](https://pyfpdf.github.io/fpdf2/Maths.html) in our documentation, and other ones about combining `fpdf2` with other libs.

[Plotly](https://plotly.com/python/) is a powerful and well-known charting library that can can produces SVG.
It would be interesting to provide a documentation section on how to generate a chart with `Plotly` and embed it in `fpdf2`.

Note that at least one `fpdf2` user has been successful in doing so in the past: #526

**Comment by ranbir7** [comment]
hey there 
How can I contribute to this??
Please give me a detailed guide since I'm very new to this.
