### ISSUE TITLE
'List' object has no attribute encode

### ISSUE THREAD

**Issue by TLPrice-52** [PyFPDF/fpdf2#662]
Describe the bug

**Error details**
If an exception is raised, it is very important that you provide the full error message.
Otherwise members of the fpdf2 won't be able to help you with your problem.

Traceback (most recent call last):
  File "/workspaces/110702199/shirtificate/experiments/tuto5.py", line 71, in <module>
    pdf.colored_table(col_names, data)
  File "/workspaces/110702199/shirtificate/experiments/tuto5.py", line 45, in colored_table
    self.cell(col_widths[0], 6, rows[0], border="LR", align="L", fill=fill)
  File "/home/ubuntu/.local/lib/python3.11/site-packages/fpdf/fpdf.py", line 216, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/fpdf/fpdf.py", line 2640, in cell
    txt = self.normalize_text(txt)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/fpdf/fpdf.py", line 3759, in normalize_text
    return txt.encode(self.core_fonts_encoding).decode("latin-1")
           ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'encode'

**Minimal code**
Please include some minimal Python code reproducing your issue:

import csv
from fpdf import FPDF

class PDF(FPDF):

    def basic_table(self, headings, rows):
        for heading in headings:
            self.cell(40, 7, heading, 1)
        self.ln()
        for row in rows:
            for col in row:
                self.cell(40, 6, col, 1)
            self.ln()

    def improved_table(self, headings, rows, col_widths=(42, 39, 35, 40)):
        for col_width, heading in zip(col_widths, headings):
            self.cell(col_width, 7, heading, border=1, align="C")
        self.ln()
        for row in rows:
            self.cell(col_widths[0], 6, row[0], border="LR")
            self.cell(col_widths[1], 6, row[1], border="LR")
            self.cell(col_widths[2], 6, row[2], border="LR", align="R")
            self.cell(col_widths[3], 6, row[3], border="LR", align="R")
            self.ln()
        # Closure line:
        self.cell(sum(col_widths), 0, "", border="T")

    def colored_table(self, headings, rows, col_widths=(42, 39, 35, 42)):
        # Colors, line width, and bold font:
        self.set_fill_color(255, 100, 0)
        self.set_text_color(255)
        self.set_draw_color(255, 0, 0)
        self.set_line_width(0.3)
        self.set_font(style="B")
        for col_width, heading, in zip(col_widths, headings):
            self.cell(col_width, 7, heading, border=1, align="C", fill=True)
        self.ln()
        # Color and font restoration:
        self.set_fill_color(224, 235, 255)
        self.set_text_color(0)
        self.set_font()
        fill=False
        for row in rows:
            self.cell(col_widths[0], 6, rows[0], border="LR", align="L", fill=fill)
            self.cell(col_widths[1], 6, rows[1], border="LR", align="L", fill=fill)
            self.cell(col_widths[2], 6, rows[2], border="LR", align="R", fill=fill)
            self.cell(col_widths[3], 6, rows[3], border="LR", align="R", fill=fill)
            self.ln()
            fill = not fill
        self.cell(sum(col_widths), 0, "", "T")

def load_data_from_csv(csv_filepath):
    headings, rows = [], []
    with open(csv_filepath) as csv_file:
        for row in csv.reader(csv_file, delimiter=","):
            if not headings: # extracting column names from first row:
                headings = row
            else:
                rows.append(row)
    return headings, rows

col_names, data = load_data_from_csv("countries.txt")
pdf = PDF()
pdf.set_font("helvetica", size=14)
pdf.add_page()
pdf.basic_table(col_names, data)
pdf.add_page()
pdf.improved_table(col_names, data)
pdf.add_page()
pdf.colored_table(col_names, data)
pdf.output("tuto5.pdf")

```
If you don't know how to build a minimal reproducible example, please check this tutorial: https://stackoverflow.com/help/minimal-reproducible-example

**Environment**
* OS (Windows, Mac OSX, Linux flavour...)
* Python version
* `fpdf2` version used

<!-- Bonus / recommended:

Often, there are bugfixes & other changes on fpdf2 git repo `master` branch
that have not been released yet. They are listed in the ChangeLog:
https://github.com/PyFPDF/fpdf2/blob/master/CHANGELOG.md

Hence, please check that your bug is still present using the latest version of fpdf2 from the git repository,
by installing it this way:

    pip install git+https://github.com/PyFPDF/fpdf2.git@master

-->

**Comment by TLPrice-52** [comment]
Both of the following produce the same:
Original from tutorial:
def load_data_from_csv(csv_filepath):
    headings, rows = [], []
    with open(csv_filepath, encoding="utf8") as csv_file:
        for row in csv.reader(csv_file, delimiter=","):
            if not headings: # extracting column names from first row:
                headings = row
            else:
                rows.append(row)
    return headings, rows

Altered:
def load_data_from_csv(csv_filepath):
    headings, rows = [], []
    with open(csv_filepath, encoding="utf-8") as csv_file:
        for row in csv.reader(csv_file, delimiter=","):
            if not headings: # extracting column names from first row:
                headings = row
            else:
                rows.append(row)
    return headings, rows

**Comment by TLPrice-52** [comment]
Copied directly from tutorial into codespace.  Works as designed.  My copy has to have an error.

**Comment by Lucas-C** [comment]
Glad that you found your error while reporting it there 👍 😃
