### ISSUE TITLE
FPDF.add_link() got an unexpected keyword argument 'page'

### ISSUE THREAD

**Issue by austinejose1516** [PyFPDF/fpdf2#663]
Describe the bug

**Error details**
If an exception is raised, it is very important that you provide the full error message.
Otherwise members of the fpdf2 won't be able to help you with your problem.

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF

pdf = FPDF()
link1 = pdf.add_link(page=1)
...
```
If you don't know how to build a minimal reproducible example, please check this tutorial: https://stackoverflow.com/help/minimal-reproducible-example

**Environment**
*  OS: MAC
* Python version: Python 3.9.6
* `fpdf2` version: 2.6.0

**Comment by Lucas-C** [comment]
The `page` parameter has been added in `fpdf2` 2.6.1 that has just been released today:
https://github.com/PyFPDF/fpdf2/releases/tag/2.6.1

Could you please retry with the latest version?

**Comment by Lucas-C** [comment]
Closing this as I'm sure the problem origin was `fpdf2` version being used
