### ISSUE TITLE
Internal link not working

### ISSUE THREAD

**Issue by austinejose1516** [PyFPDF/fpdf2#664]
Can someone tell me what am I doing wrong here. All link works fine except the link on the first page. Thanks in advance.

```python
from fpdf import FPDF

pdf = FPDF()

link1 = pdf.add_link()
link2 = pdf.add_link()
link3 = pdf.add_link()
link4 = pdf.add_link()

pdf.add_page()
pdf.set_link(link1, page=1)
pdf.set_font('helvetica', size=12)
pdf.cell(txt="Page 1", link=link4)

pdf.add_page()
pdf.set_link(link2, page=2)
pdf.set_font('helvetica', size=12)
pdf.cell(txt="Page 2", link=link3)

pdf.add_page()
pdf.set_link(link3, page=3)
pdf.set_font('helvetica', size=12)
pdf.cell(txt="Page 3", link= link2)

pdf.add_page()
pdf.set_link(link4, page=4)
pdf.set_font('helvetica', size=12)
pdf.cell(txt="Page 4", link=link3)

pdf.add_page()
pdf.set_font('helvetica', size=12)
pdf.cell(txt="Page 5", link=link2)

pdf.output("/*****/*****/*****/hello_world.pdf")
```

**Comment by Lucas-C** [comment]
I don't understand the logic of your links...

For example for your first page:
```python
pdf.add_page()
pdf.set_link(link1, page=1)
pdf.set_font('helvetica', size=12)
pdf.cell(txt="Page 1", link=link4)
```

You set the destination page number for `link1` but then insert `link4`, which has no page assigned yet!

I suggest you use the following code instead, with [the latest release 2.6.1 from today](https://github.com/PyFPDF/fpdf2/releases/tag/2.6.1):
```python
from fpdf import FPDF

pdf = FPDF()
pdf.set_font('helvetica', size=12)

pdf.add_page()
pdf.cell(txt="Page 1", link=pdf.add_link(page=2))

pdf.add_page()
pdf.cell(txt="Page 2", link=pdf.add_link(page=3))

pdf.add_page()
pdf.cell(txt="Page 3", link=pdf.add_link(page=4))

pdf.add_page()
pdf.cell(txt="Page 4", link=pdf.add_link(page=5))

pdf.add_page()
pdf.cell(txt="Page 5", link=pdf.add_link(page=1))

pdf.output("issue_664.pdf")
```

**Comment by austinejose1516** [comment]
Thanks for the quick response. However when I try your solution I get Type Error:
```
TypeError: add_link() got an unexpected keyword argument 'page'
```
I am wondering whats wrong here.

**Comment by austinejose1516** [comment]
Thanks a million. My idea about the links was wrong. I was trying to assign link to each page by set_link function and then trying to pass that value to the link attribute. 

Thanks you once again for the perfect solution!

**Comment by Lucas-C** [comment]
You're welcome, glad that I was able to help you a little 😊

**Comment by shayan-NECX** [comment]
Thanks for helping with this issue. I notice sometimes PDF crashes when clicking on the link. This issue is a bit inconsistent. I copied Lucas's code, ran it. Clicked on hyperlink and it crashed PDF. I restarted that PDF file, clicked on hyperlink and it took me to those pages. Strange .. has any one else encountered this issue ?

**Comment by Lucas-C** [comment]
> Thanks for helping with this issue. I notice sometimes PDF crashes in Adobe Acrobat Reader when clicking on the link. This issue is a bit inconsistent. I copied Lucas's code, ran it. Clicked on hyperlink and it crashed PDF. I restarted that PDF file, clicked on hyperlink and it took me to those pages. Strange .. has any one else encountered this issue ?

Hi @shayan-NECX!

Thanks for reporting this.
That must be quite annoying, and i'd be curious to know if other users sometimes have the same problem.

The fact that the crash does not happen every time makes it difficult to debug for us...

It seems that Adobe Acrobat Reader can generate `Acrobat.exe.dmp` dump files when it crashes: https://helpx.adobe.com/acrobat/kb/collect-logs-crash-freeze.html
It never tested this procedure though, but it may be an interesting lead to investigate further...

If someone wants to dig deeper on the subject, please open a dedicated issue 😊
Comments added to closed issues are very likely to be missed by maintainers and other `fpdf2` users passing by.

**Comment by shayan-NECX** [comment]
Actually, when i open the same file in Edge browser, it works fine and all the in-document links also work fine. Thats weird. So its just in acrobat reader this happens.
