### ISSUE TITLE
Customizing TOC rendering triggers deprecation warning

### ISSUE THREAD

**Issue by vonopr** [PyFPDF/fpdf2#670]
Hello! I want to customize the TOC rendering and found [a suitable example in the docs](https://pyfpdf.github.io/fpdf2/DocumentOutlineAndTableOfContents.html#with-html):

```python
from fpdf import FPDF, HTML2FPDF

class CustomHTML2FPDF(HTML2FPDF):
    def render_toc(self, pdf, outline):
        pdf.cell(txt='Table of contents:', new_x="LMARGIN", new_y="NEXT")
        for section in outline:
            pdf.cell(txt=f'* {section.name} (page {section.page_number})', new_x="LMARGIN", new_y="NEXT")

class PDF(FPDF):
    HTML2FPDF_CLASS = CustomHTML2FPDF

pdf = PDF()
pdf.add_page()
pdf.write_html("""<toc></toc>
    <h1>Level 1</h1>
    <h2>Level 2</h2>
    <h3>Level 3</h3>
    <h4>Level 4</h4>
    <h5>Level 5</h5>
    <h6>Level 6</h6>
    <p>paragraph<p>""")
pdf.output("html_toc.pdf")
```
This gives me a deprecation warning:
```
DeprecationWarning: The HTML2FPDF_CLASS is deprecated. It will be removed in a future release.
```

Is there a proper non-deprecated way to modify the rendering of TOC? I am not satisfied with the default style and it would be a pity if this ability will be removed.

**Comment by Lucas-C** [comment]
Hi @vonopr

Thanks for the report.

You are right, and I don't see a better way to provide full customization over `write_html()` behaviour than this `HTML2FPDF_CLASS` behaviour. I'm going to remove this warning in #671

**Comment by vonopr** [comment]
That's great. @Lucas-C, thanks a lot!

BTW. It's kinda offtopic and probably does not deserve a new issue. The mentioned example contains a typo:
it should be `<p>paragraph</p>` instead of  `<p>paragraph<p>` . A warning `Missing HTML end tag for <p>` is produced now.
