### ISSUE TITLE
PDF metadata doesn't work for Unicode strings

### ISSUE THREAD

**Issue by eroux** [PyFPDF/fpdf2#685]
When running the following:

```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page(format=(200,200))
pdf.set_creator("༄༅། །སྒྲུབ།")
pdf.output("test-tib.pdf")
```

I get

```
Traceback (most recent call last):
  File "test-tib-metadata.py", line 6, in <module>
    pdf.output("test-tib.pdf")
  File "/home/eroux/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 4492, in output
    self.buffer = output_producer.bufferize()
  File "/home/eroux/.local/lib/python3.7/site-packages/fpdf/output.py", line 442, in bufferize
    self._out(pdf_obj.serialize(_security_handler=fpdf._security_handler))
  File "/home/eroux/.local/lib/python3.7/site-packages/fpdf/output.py", line 462, in _out
    data = data.encode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 61-63: ordinal not in range(256)
```

I notice that the PHP FPDF has an [option for UTF8 metadata](http://www.fpdf.org/en/doc/setcreator.htm), perhaps a similar option could be implemented?

**Comment by Lucas-C** [comment]
Thank you for the bug report. I am currently working on a fix.

@allcontributors please add @eroux for bug

**Comment by Lucas-C** [comment]
@allcontributors please add @eroux for bug

**Comment by eroux** [comment]
fantastic, thanks!

**Comment by Lucas-C** [comment]
This has not been released in a new version of `fpdf2`, but you can already test it using the latest, unreleased, development version straight from the development branch of this repository:

    pip install git+https://github.com/PyFPDF/fpdf2.git@master
