### ISSUE TITLE
Feature request: allow CCITT image encoding

### ISSUE THREAD

**Issue by eroux** [PyFPDF/fpdf2#691]
I would like to be able to use the CCITT (TIFF) encoding for bitonal images. Currently these seem to be internally converted to grayscale pngs which produce a bigger output and requires more processing time. Now, for one or two files that is fine, but I'm in the process of creating PDFs for  a few million images and the difference become really noticeable.

Here's an example:

```python
from fpdf import FPDF

pdf = FPDF()
pdf.set_margin(0)
pdf.add_page(format=(2142,507))
pdf.image("020610001.tiff", x=0, y=0, w=2142, h=507)
pdf.output("test-tiff.pdf")
```

producing the following pdf (10,985 bytes):

[test-tiff.pdf](https://github.com/PyFPDF/fpdf2/files/10743602/test-tiff.pdf)

while I would expect the following one (produced with itext, 7,126 bytes, 35% smaller):

[test-tiff-expected.pdf](https://github.com/PyFPDF/fpdf2/files/10743604/test-tiff-expected.pdf)

The transformation into PNG can be seen through `pdfimages -all test-tiff.pdf test-tiff` that produces the following `test-tiff-000.png`:

![test-tiff-000](https://user-images.githubusercontent.com/60868/219045804-cc4726ff-6c48-4410-91fb-981f9369dc04.png)

**Comment by eroux** [comment]
https://gitlab.mister-muffin.de/josch/img2pdf/src/branch/main/src/img2pdf.py#L804 seems to do that for example

**Comment by Lucas-C** [comment]
Hi @eroux!

Have you tried configuring image compression?
_cf._ https://pyfpdf.github.io/fpdf2/Images.html#image-compression

If that does not fit your need, the feature you suggest would make for a great addition to `fpdf2` 😊
Would you like to contribute a PR implementing this?

Based on the [1.7 PDF spec](https://christianhaider.de/dokuwiki/lib/exe/fetch.php?media=pdf:pdf32000_2008.pdf), this would mean implementing support for `LZWDecode` filter here: https://github.com/PyFPDF/fpdf2/blob/master/fpdf/image_parsing.py#L21

> LZW (Lempel-Ziv-Welch) is a variable-length, adaptive compression method that has been adopted as one
of the standard compression methods in the Tag Image File Format (TIFF) standard. For details on LZW
encoding see 7.4.4.2, "Details of LZW Encoding."

**Comment by eroux** [comment]
In the PDF spec the encoding I'm thinking of is `CCITTFaxDecode`, which is clearly the best for bitonal pictures. I might create a PR, let's see

**Comment by eroux** [comment]
PR on https://github.com/PyFPDF/fpdf2/pull/695
