### ISSUE TITLE
Feature request: avoid altering images passed to FPDF.image() if there is no need to

### ISSUE THREAD

**Issue by eroux** [PyFPDF/fpdf2#693]
_(orignal title: "not parsing images when possible")_

A feature I really love in [img2pdf](https://gitlab.mister-muffin.de/josch/img2pdf/) is the fact that it doesn't load and save the image if it doesn't need to. For our use case this means a huge performance gain and also in the tests I made, a gain in size of the PDF since re-compression doesn't always produce smaller pictures. See [this function](https://gitlab.mister-muffin.de/josch/img2pdf/src/branch/main/src/img2pdf.py#L1440) for instance to get the CCITT payload from a tiff file, so that it can then be copied directly without even having to look at it

**Comment by Lucas-C** [comment]
Hi @eroux

I am sorry but I am not sure to fully understand your intent here:
is this a feature request? You would like `fpdf2` to **not** alter the image passed to `FPDF.image()` if it does not need to?

_(if you confirm that this your correct intent, we could rename this issue title accordingly)_

This would be possible for JPEG images, and [CCITT/TIFF images](https://github.com/PyFPDF/fpdf2/issues/691) I guess, but some images like PNG cannot be embedded in their native format in a PDF document.

In terms of code, this would mean a refactoring in `fpdf/image_parsing.py` and `fpdf/fpdf.py` to **not** systematically convert images to `PIL.Image intances`. This may not play well with existing features such as [oversized images detection & downscaling](https://pyfpdf.github.io/fpdf2/Images.html#oversized-images-detection-downscaling), but is in theory perfectly doable.

I don't personnally plan to work on this task, but you or other contributors are welcome to do so 😊

**Comment by Lucas-C** [comment]
@allcontributors please add @eroux for ideas
