### ISSUE TITLE
Feature request: include ICC profile in documents

### ISSUE THREAD

**Issue by eroux** [PyFPDF/fpdf2#697]
PDFs have a special way to indicate the ICC profile of an image that overrides the one potentially embedded in an image. This means that PDF viewers will ignore the ICC profile embedded in an image. Currently fpdf never writes the ICC profile so that they are consistently ignored.

Here's a sample image with an ICC profile:

![icc-embedded](https://user-images.githubusercontent.com/60868/219657351-e310ec47-7b76-4ea6-9ccd-21b3a6d66fad.jpg)

Here's a PDF embedding this image through img2pdf (which writes the ICC profile in the PDF):

[test-icc-img2pdf.pdf](https://github.com/PyFPDF/fpdf2/files/10766845/test-icc-img2pdf.pdf)

the code I'm using to test this is:

```
import fpdf

def test_insert_jpg_with_icc():
    pdf = fpdf.FPDF()
    pdf.compress = False
    pdf.add_page(format=(448,498))
    pdf.set_margin(0)
    pdf.image("icc-embedded.jpg", x=0, y=0, h=498)
    pdf.output("image_types_insert_jpg_with_icc.pdf")

test_insert_jpg_with_icc()
```

which produces the following PDF:

[image_types_insert_jpg_with_icc.pdf](https://github.com/PyFPDF/fpdf2/files/10766870/image_types_insert_jpg_with_icc.pdf)

The two PDFs look different in a a PDF viewer (the correct one is more red).

**Comment by Lucas-C** [comment]
Thank you for the feature suggestion @eroux 😊
This feature would sure make a great addition to `fpdf2`!
Any willing contributor is welcome to submit a PR implementing this,
and inspiration could be taken from `img2pdf` source code.

**Comment by Lucas-C** [comment]
Reopening as VeraPDF checker spotted a couple of issues with our current implementation:

* [Rule 6.2.3-1](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-623-1)
> All ICCBased colour spaces shall be embedded as ICC profile streams as described in PDF Reference 4.5

* [Rule 6.2.3-5](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-623-5)
> All ICCBased colour spaces shall be embedded as ICC profile streams as described in PDF Reference 4.5. The number of color components in the color space described by the ICC profile data must match the number of components actually in the ICC profile. As of PDF 1.4, N must be 1, 3, or 4.

Both checks failed for file `test/image/png_images/image_png_insert_png_files.pdf`

**Comment by Lucas-C** [comment]
The 1st check seems like a false positive, as `fpdf2` does not currently produce any `ICCInputProfile` object.

The 2nd one seems legit, I am creating a PR to fix it.

**Comment by eroux** [comment]
Thanks!
