### ISSUE TITLE
PDF not generated after exe file put into distribution (by Inno installer

### ISSUE THREAD

**Issue by vetross** [PyFPDF/fpdf2#717]
Describe the bug

Python file is made into exe file using pyinstaller and works fine i.e run Masters.exe file from dist file and works.
Once is compiled into setup file and installed, there is no output files generated.  no error messages are shown.
Tried it with installforge and installed on different computer with same result.  Rest of program runs fine.

**Comment by Lucas-C** [comment]
Hi @vetross

We welcome bug reports, but you probably noticed a template when redacting this issue.
It's there in this repository: https://github.com/PyFPDF/fpdf2/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
It has a purpose: make it possible for `fpdf2` contributors to help you with your issue.
Without detailed information, we won't be able to provide you any solution.

Could you please provide the following elements that would make it possible for us to reproduce this problem:
* some minimal Python code using `fpdf2`, that when compiled into an `.exe`, behave abnormally
* some minimal Pyinstaller configuration file(s)
* the detailed steps you followed to generate the problematic `.exe`

If you provide those elements, I guarantee you that I'll try to reproduce and solve the issue! 😊

**Comment by vetross** [comment]
I have tried to fill out your report template 
I cannot get the Dist folder to paste into this or the template.
Let me know if you want anything else.
John

**Comment by vetross** [comment]
Hi Lucas

I have found the problem!
I do not  think it has anything to do with fpdf2.
If I install the program into the program folder (default) it does not
work.  If I install it into a separate folder it works ok.

John

J H Ross
62 Kings Drive
Wanaka 9305
022 1614706
