### ISSUE TITLE
Generalize the font-alias mechanism

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#73]
Currently, "Arial" is defined in the code as an alias for "helvetica":
- [in `add_font`](https://github.com/PyFPDF/fpdf2/blob/2.2.0/fpdf/fpdf.py#L581)
- [in `set_font`](https://github.com/PyFPDF/fpdf2/blob/2.2.0/fpdf/fpdf.py#L709)

This could be generalized according to the table of alternatives from appendix H, section 5.5.1 of the [PDF 1.7 spec](https://ghostscript.com/~robin/pdf_reference17.pdf):

Standard name           | Alternative
------------------------|-
Courier                 | CourierNew
Courier − Oblique       | CourierNew,Italic
Courier − Bold          | CourierNew,Bold
Courier − BoldOblique   | CourierNew,BoldItalic
Helvetica               | Arial
Helvetica − Oblique     | Arial,Italic
Helvetica − Bold        | Arial,Bold
Helvetica − BoldOblique | Arial,BoldItalic
Times − Roman           | TimesNewRoman
Times − Italic          | TimesNewRoman,Italic
Times − Bold            | TimesNewRoman,Bold
Times − BoldItalic      | TimesNewRoman,BoldItalic

**Comment by fbernhart** [comment]
I'd like to give it a try. 😊 

I wanted to look up if there are more details in the mentioned 1.7 specs, but I couldn't your table. As well there is no section 5.5.1 in Annex H. 🤔

**Comment by Lucas-C** [comment]
Great!

Sorry for the erroneous reference. I mixed up two different documents:
- in [PDF Reference - Version 1.7 - sixth edition (1310 pages)](https://ghostscript.com/~robin/pdf_reference17.pdf) there is a section 5.5.1 on appendix H, it's on page 1109
- in [Portable Document Format - First Edition - 2008-7-1 (756 pages)](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) there is no such table indeed
