### ISSUE TITLE
ImportError: cannot import name 'FPDF' from partially initialized module 'fpdf' (most likely due to a circular import)

### ISSUE THREAD

**Issue by bnxvs** [PyFPDF/fpdf2#741]
Describe the bug

**Error details**
ImportError: cannot import name 'FPDF' from partially initialized module 'fpdf' (most likely due to a circular import)

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF
from fpdf import *
import fpdf

pdf = FPDF()
...
```

**Environment**
* OS Mac OSX
* Python version 3.9
* `fpdf2` version used - all. Also tried - pip install git+https://github.com/PyFPDF/fpdf2.git@master

**Comment by Lucas-C** [comment]
Hi @bnxvs

Thank you for the bug report.
Sadly, this is not enough for me to reproduce your error...
This code works totally fine on my computer with the latest version of `fpdf2`.

What was the stacktrace you faced exactly?
Maybe you put your code in a file named `fpdf.py`, which could explain the error?
