### ISSUE TITLE
Significant performance issue compare from 2.7.1 and 2.5.6

### ISSUE THREAD

**Issue by CY-Qiu** [PyFPDF/fpdf2#742]
Describe the bug

I tried same code with fpdf 2.5.6 and the latest 2.7.1 version. The 2.7.1 is significant slower than 2.5.6.
I research a little, it seems that there are many aspects related with this issue.
The following code produce different result.
In 2.5.6, the code only consumes 1.6s.
```
2023-03-30 19:58:30.041385
2023-03-30 19:58:30.041519
2023-03-30 19:58:30.804402
2023-03-30 19:58:31.680267
```
In 2.7.1, the code consumes 5.4s, which is three times more.
```
2023-03-30 19:58:15.936361
2023-03-30 19:58:15.936496
2023-03-30 19:58:18.571075
2023-03-30 19:58:21.581059
```

**Minimal code**
```python
from fpdf import FPDF
import datetime

if __name__ == "__main__":
    # Setup
    print(datetime.datetime.now())
    pdf = FPDF()
    pdf.add_page()
    pdf.set_text_color(0, 0, 0)
    print(datetime.datetime.now())
    # In our usage cirumstance, we have to use many different fonts in the same time.
    # Here we use SourceHanSerifSC by Adobe. See https://github.com/adobe-fonts/source-serif
    pdf.add_font(family="ChineseRegular", fname="/usr/share/fonts/opentype/SourceHanSerifSC-Regular.ttf")
    pdf.add_font(family="ChineseBold", fname="/usr/share/fonts/opentype/SourceHanSerifSC-Bold.ttf")
    pdf.add_font(family="ChineseExtraLight", fname="/usr/share/fonts/opentype/SourceHanSerifSC-ExtraLight.ttf")
    pdf.add_font(family="ChineseHeavy", fname="/usr/share/fonts/opentype/SourceHanSerifSC-Heavy.ttf")
    pdf.add_font(family="ChineseLight", fname="/usr/share/fonts/opentype/SourceHanSerifSC-Light.ttf")
    pdf.add_font(family="ChineseSemiBold", fname="/usr/share/fonts/opentype/SourceHanSerifSC-SemiBold.ttf")
    pdf.add_font(family="ChineseMedium", fname="/usr/share/fonts/opentype/SourceHanSerifSC-Medium.ttf")
    print(datetime.datetime.now())
    pdf.set_font("ChineseRegular", size=10)
    text = "       鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美"
    for i in range(0, 200):
        pdf.multi_cell(w=150, txt=text, border=1, new_x="LEFT", fill=False, split_only=False)
    # Save result
    pdf.output("/home/myuser/code/pythontest/test.pdf")
    print(datetime.datetime.now())
```

**Environment**
Ubuntu X86_64
* Python version
2.7.1 and 2.5.6

**Comment by Lucas-C** [comment]
Thank you for opening this issue @CY-Qiu!

This is very valuable analysis.

What numbers do you get with your test using `fpdf2` versions 2.5.7 / 2.6.0 / 2.6.1?
In [v2.5.7](https://github.com/PyFPDF/fpdf2/blob/master/CHANGELOG.md#257---2022-09-08), we started using `fonttools`, and I wonder if this could be one of the reasons behind the impact on performances you witnessed.

We should probably setup a performance test involving fonts.
We already have one involving images: https://github.com/PyFPDF/fpdf2/blob/master/test/test_perfs.py

Have you been able to figure which line / method call in your script
has seen the largest the increase in execution time between the 2 versions of `fpdf2` you tested?

**Comment by CY-Qiu** [comment]
It seems that both pdf.add_font and pdf.multi_cell are consuming more time.
The detail remains to be researched.

**Comment by Lucas-C** [comment]
> The detail remains to be researched.

Do you plan to go on investigating this issue?
Or maybe you just wanted to report it, with no intent to work on the subject yourself?

**Comment by CY-Qiu** [comment]
I tried to research, however it looks a little bit hard. I'm wandering if there are some coders more familiar with this issue. 😃

**Comment by Lucas-C** [comment]
For reference, the font files can be downloaded from this repo: https://github.com/adobe-fonts/source-han-serif/tree/release/OTF/SimplifiedChinese

**Comment by Lucas-C** [comment]
I investigated a litte bit more.

I used the following Python script as reference while benchmarking several version of `fpdf2`:
```python
import logging
logging.getLogger('fontTools.subset').level = logging.WARN

from fpdf import FPDF, FPDF_VERSION
from timeit import timeit

def build_pdf():
    pdf = FPDF()
    pdf.add_page()
    pdf.add_font(family="ChineseRegular", fname="fonts/SourceHanSerifSC-Regular.otf")
    pdf.set_font("ChineseRegular", size=10)
    text = "       鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美鸡你太美"
    for i in range(0, 200):
        pdf.multi_cell(w=150, txt=text, border=1, new_x="LEFT", fill=False, split_only=False)
    pdf.output("issue_742.pdf")

repeats = 10
total_elapsed = timeit(build_pdf, number=repeats)
print(f"[v{FPDF_VERSION}] Average exec time for {repeats} repeats: {total_elapsed/repeats:.2f}s")
```
Results, using Python 3.8:
```
for tag in 2.5.7 2.6.0 2.6.1 master; do git checkout --force $tag >/dev/null 2>&1; python issue_742.py; done
[v2.5.7] Average exec time for 10 repeats: 1.04s
[v2.6.0] Average exec time for 10 repeats: 1.09s
[v2.6.1] Average exec time for 10 repeats: 1.03s
[v2.7.3] Average exec time for 10 repeats: 1.02s
```

I used `.otf` font files though, which contain `Postscript outlines`, and the were not supported before `fpdf2` `v2.5.7`.

If you want me to continue investigating, could you provide a link to your `.ttf` font files please @CY-Qiu?

**Comment by Lucas-C** [comment]
> We should probably setup a performance test involving fonts.
> We already have one involving images: [`master`/test/test_perfs.py](https://github.com/PyFPDF/fpdf2/blob/master/test/test_perfs.py?rgh-link-date=2023-03-30T12%3A52%3A11Z)

For reference, I added a check on the duration of the unit test `test_charmap_first_999_chars()` that loads all test fonts:
https://github.com/PyFPDF/fpdf2/blob/master/test/fonts/test_charmap.py#L35

**Comment by Lucas-C** [comment]
Hi @CY-Qiu

We tried to answer your initial concern.

Unless you wish to follow on this, and provide the `.ttf` files you used, I'm planning on closing this issue.
