### ISSUE TITLE
Merge conflict artefact in docstring for `CoerciveIntFlag.coerce`

### ISSUE THREAD

**Issue by AlexWaygood** [PyFPDF/fpdf2#743]
The docstring for `CoerciveIntFlag.coerce` looks like it has an artefact of a merge conflict in it:

https://github.com/PyFPDF/fpdf2/blob/615db585a53dde9af5874fb0a58f33ee7f84aa2b/fpdf/enums.py#L110-L137

It looks like this happened relatively recently, in 0579097951177ba61ac196c1f0765abea710cdb9.

**Comment by AlexWaygood** [comment]
The [`check-merge-conflict` pre-commit hook](https://github.com/pre-commit/pre-commit-hooks#check-merge-conflict) can help spot these issues ahead of time, but it doesn't look like this project is using pre-commit right now.

**Comment by Lucas-C** [comment]
Thank you for reporting this @AlexWaygood!

I fixed this in https://github.com/PyFPDF/fpdf2/pull/744, but I'm going to keep this open as a reminder to add those pre-commit hooks, it's a good suggestion 😊
