### ISSUE TITLE
Convert tests to pytest

### ISSUE THREAD

**Issue by eumiro** [PyFPDF/fpdf2#75]
Would you consider converting the tests to pytest?

`assert expr` is easier to read than `self.assertSomething(x, y)`

Using their `tmp_path` fixture would simplify the temporary files manipulation enormously. Every test function gets its own subdirectory in `/tmp/pytest-of-$USER` and three latest test runs are kept there for further investigation. This would save the whole housekeeping after tests.

Reorganizing the tests to `/tests` and the testdata to `/tests/testdata` would also make the ubiquitous `relative_path_to` method redundant.

And, last, but not least, organizing tests to simple methods would remove one indentation level from the test files.

**Comment by alexanderankin** [comment]
Isn't the grouping of the test useful, also ( and this was more relevant
before we introduced qPDF) having the output of the test next to the test
kind of makes sense so that you can do comparisons. Assert is a python
keyword, right? So it seems like it can be used regardless of the framework

**Comment by Lucas-C** [comment]
I think switching to `assert` will break compatibility with `unittest`.

I'm used to `pytest` and I know the many useful features it would provide, so I'm favorable overall.

However @alexanderankin has been maintaining this project for longer than I have, and I'd prefer not to operate this change if he's not comfortable with it 😉

**Comment by eumiro** [comment]
@alexanderankin of course you can keep the test classes.

When unittest encounters `assert expr`, it only says the `expr` is but does not analyze the expression. That's what all those `self.assertSomething` methods are for. `pytest` analyzes the expression. That's why the switch would have to be planned and there's (almost) no way back to the stdlib unittest.

I am just asking whether you're considering it. Today I have also tried to introduce `pathlib.Path` for all directory/files operations, but in the tests that would be too much overhead without using the `tmp_path` fixture from `pytest`.

**Comment by alexanderankin** [comment]
I'm not super active anymore, so I dont know that the exception needs to be
made for me specifically, but surely there have to be some benefits to
using the std lib? I'm not sold but I'll do some research. Perhaps the
stdlib test framework isnt that great if it cant catch assertion errors

**Comment by eumiro** [comment]
It does catch `assert` errors:

`assert x > y, "wrong order`

will tell you `wrong order`

But if you give `pytest`

`assert x > y`

it will print the values of `x` and `y` as well.

**Comment by alexanderankin** [comment]
What id like to avoid is the tests being much different so that its easy to
see what changed and difficult to drop a lot of coverage in the move.
You'll notice above each test I have commands to run each class, as long as
stuff like that is preserved, etc. I don't know that it makes sense for me
to object to a framework if it's really mainstream, better, and @lucas-c is
familiar.

**Comment by alexanderankin** [comment]
there seems to be a consensus in the python community on pytest lol. I use java at work, so i see lots of the self.assertEquals and [hamcrest](https://github.com/hamcrest/PyHamcrest) methods (without the self, though b/c its java). I think pytest overall is the right move in order to keep it going. according to the internet this is worthwhile.

**Comment by Lucas-C** [comment]
Great!
Let's go with `pytest` then!

@eumiro are you volunteering to do the transition? 😊

**Comment by eumiro** [comment]
> Great!
> Let's go with `pytest` then!
> 
> @eumiro are you volunteering to do the transition? blush

I can certainly help you to prepare the directories and start the migration, but then it looks like a nice bunch of good-first-issues for other contributors.

I'd propose to create a new directory `tests` with the subdirectory `testdata` and in a new branch start copying the tests and their test data there. Once it's done, the old `test` directory can be removed and after the merge the CI will run the new tests.

**Comment by Lucas-C** [comment]
Thank you very much for the time you are taking in improving `fpdf2` tests!

I see you already opened a PR: https://github.com/PyFPDF/fpdf2/pull/80 😮

Awesome! I'm going to comment on it & continue the discussion there

**Comment by Lucas-C** [comment]
Done in https://github.com/PyFPDF/fpdf2/pull/82

Closing this
