### ISSUE TITLE
Support for rich text in table cell

### ISSUE THREAD

**Issue by Rahulscan** [PyFPDF/fpdf2#759]
I want to add rich text in the table cell and bold the first strings as below screenshot

![Screenshot 2023-04-10 at 5 59 05 PM](https://user-images.githubusercontent.com/129848996/230902159-e84b860c-42cd-43ff-aef6-25a89fbd3892.png)

I'm using the following code to generate table, however not sure how to make text bold inside the cell.

```python
 with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False) as table:
  row = table.row()
  row.cell('Seller Details  \n GSTIN...', align='L', style=FontFace(''))
  row.cell('Details of Invoice \n Invoice Number....')
  row.cell('')
```

I want to make bold **Seller Details** and **Details of Invoice** texts.

Is there a way to make particular string bold, may be using rich HTML `<b>Seller Details</b>` or markdown `**Seller Details**`?

**Comment by Lucas-C** [comment]
Hi @Rahulscan!

> Is there a way to make particular string bold, may be using rich HTML `<b>Seller Details</b>` or markdown `**Seller Details**`?

Yes, you can use `**markdown**` asterisks, but then you need to pass `markdown=True` to `FPDF.table()`:
https://pyfpdf.github.io/fpdf2/fpdf/table.html#fpdf.table.Table

Does that answer your need? 😊

**Comment by Rahulscan** [comment]
Hi @Lucas-C 
Thanks for the suggestion!! It did work.
