### ISSUE TITLE
Integrating pdf into pdf

### ISSUE THREAD

**Issue by Leopold194** [PyFPDF/fpdf2#767]
Is it possible to embed a pdf directly on a pdf page with FPDF2?

**Comment by Leopold194** [comment]
I created a pdf page with FPDF2, and I would like to integrate it on a second page that I created beforehand, as if I added a png with pdf.image()

**Comment by gmischler** [comment]
fpdf2 does not read PDF files.

For combining content from different PDF files, [pypdf](/py-pdf/pypdf) would be a better candidate.
More specifically, its [merge functionality](https://pypdf.readthedocs.io/en/stable/user/add-watermark.html) should be able to solve your task.

**Comment by Lucas-C** [comment]
We also have documentation on combining `fpdf2` with `pdfrw` there:
https://pyfpdf.github.io/fpdf2/CombineWithPdfrw.html

Do the links we provided answer your initial question @Leopold194?

**Comment by Lucas-C** [comment]
> I would like to be able to place the first pdf on a precise place of my page, of which I know the coordinates. How is it possible easily?

I think you should be able to achieve what you want by playing with the `.x` / `.y` attributes of the `RectXObj` instance,
in the examples listed on the documentation page I mentioned.

**Comment by Lucas-C** [comment]
Unless you have more questions @Leopold194,
I'll probably close this issue in a few days 😊

**Comment by Lucas-C** [comment]
I'm not totally sure to understand your requirements (and especially why you have this constraint),
but I'm sorry, I do not think that `fpdf2` can achieve what you want!
You may consider asking for some help on [StackOverflow](https://stackoverflow.com) ?
