### ISSUE TITLE
Table not load image with Pillow Instance Image

### ISSUE THREAD

**Issue by Valerus5685** [PyFPDF/fpdf2#771]
Table not load image with Pillow Instance Image

In documentation says

> Adds a cell to the row.
> 
> Args:
>     text (str): string content, can contain several lines.
>         In that case, the row height will grow proportionally.
>     align (str, fpdf.enums.Align): optional text alignment.
>     style (fpdf.fonts.FontFace): optional text style.
>     img: optional. Either a string representing a file path to an image,
>         an URL to an image, an io.BytesIO, or a instance of `PIL.Image.Image`.
>     img_fill_width (bool): optional, defaults to False. Indicates to render the image
>         using the full width of the current table column.
>     colspan (int): optional number of columns this cell should span.

but this doesn't work even with io.BytesIO

**Minimal code**
```python
from fpdf import FPDF
import qrcode
...
qrCodeGenerated = qrcode.make("https://google.com")
with pdf.table(first_row_as_headings=False) as table:
    row = table.row()
    row.cell(img=qrCodeGenerated.get_image(),img_fill_width=True)
    row.cell("Other field")
...
```

**Environment**
Please provide the following information:
* **Operating System**: Debian GNU/Linux 11 (bullseye)
* **Python version**:  Python 3.9.2
* **`fpdf2` version used**: fpdf2==2.7.3

**Comment by Lucas-C** [comment]
Hi @Valerus5685

Thank you for reporting this issue!

I'm having a look, I'll get back to you tomorrow.

**Comment by ssavi-ict** [comment]
Hi @Valerus5685 , I tried your minimal example with following - 
```
from fpdf import FPDF
import qrcode

pdf = FPDF()
pdf.add_page()

pdf.set_font("Times", size=16)
qrCodeGenerated = qrcode.make("https://google.com")
with pdf.table(first_row_as_headings=False) as table:
    row = table.row()
    row.cell(img=qrCodeGenerated.get_image(),img_fill_width=True)
    row.cell("Other field")
pdf.output('table.pdf')
```

Is it a correct code according to the context of your issue? It generates following output pdf - [table.pdf](https://github.com/PyFPDF/fpdf2/files/11280000/table.pdf)

**Comment by Lucas-C** [comment]
@allcntributors please add @Valerus5685 for bug

**Comment by Lucas-C** [comment]
@allcontributors please add @Valerus5685 for bug

**Comment by Lucas-C** [comment]
Actually, there were some some remaining bugs on the `develop` branch following PR #768, so I opened PR #771

But I agree with @ssavi-ict: with `fpdf2==2.7.3`, your code seems to work fine @Valerus5685!

Could you elaborate on what is the issue for you, and maybe share a PDF or screenshot of what you see?

**Comment by Lucas-C** [comment]
@allcontributors please add @ssavi-ict for question

**Comment by Lucas-C** [comment]
Hi @Valerus5685!

FYI, without any news on your part, I'll close this issue at some point.

**Comment by Lucas-C** [comment]
Closing this issue as it hasn't received any answer for 2 weeks.
