### ISSUE TITLE
AWS Lambda: No module named 'html.parser'; 'html' is not a package"

### ISSUE THREAD

**Issue by jonahmarc** [PyFPDF/fpdf2#778]
Added fpdf2 as a layer in the AWS Lambda function

**Error details**
Raises error, when I run the lamda function
```
{
  "errorMessage": "Unable to import module '<module_name>': No module named 'html.parser'; 'html' is not a package",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "460...3c",
  "stackTrace": []
}
```

they say i have to rename `fpdf/html.py`, since this file masks the standard library package. if I rename html.py, how much will it affect my use of `fpdf2` library?

**Code**
```python
import logging
import pymysql
import boto3
import json
import datetime

from fpdf2 import FPDF...
```

**Environment**
Please provide the following information:
* **Operating System**: AWS Lambda Console
* **Python version**: Python 3.10
* **`fpdf2` version used**: didn't install using pip, downloaded as zip file version (04/25/2023)

**Comment by jonahmarc** [comment]
they say i have to rename `fpdf/html.py`, since this file masks the standard library package. if I rename html.py, how much will it affect my use of `fpdf2` library?

**Comment by Lucas-C** [comment]
> they say i have to rename fpdf/html.py, since this file masks the standard library package. if I rename html.py, how much will it affect my use of fpdf2 library?

No, this does not sound like a good solution at all to me...

> `fpdf2` version used: didn't install using pip, downloaded as zip file version (04/25/2023)

This probably the issue.

`fpdf2` has a few dependencies, that `pip` would have installed:
https://github.com/PyFPDF/fpdf2/blob/master/setup.py#L30

You need to craft a lambda layer that includes those dependencies, for example using the `-t`. / `--target` argument of `pip install`.
You will fin a lot of documentation about this online:
https://repost.aws/knowledge-center/lambda-python-package-compatible

Does this answer helped you?

**Comment by Lucas-C** [comment]
@jonahmarc have you been able to solve your problem?

I'd be happy to help you further if you want to provide more details 😊
Otherwise, I'll probably close this issue if it stays inactive

**Comment by jonahmarc** [comment]
@Lucas-C hello, my bad for not updating the progress. 

I've solved it already, turns out the fpdf2 zip package added as layer in the lambda function wasn't complete. I had to update it. Thank you for the help.

**Comment by Lucas-C** [comment]
> @Lucas-C hello, my bad for not updating the progress.
> 
> I've solved it already, turns out the fpdf2 zip package added as layer in the lambda function wasn't complete, missing some dependencies/folders. I had to update it. Thank you for the help.

I'm glad that you solved your problem!

Well done 👍

I hope `fpdf2` will answer your PDF-generation needs 😊
