### ISSUE TITLE
Vertical line spacing inside a cell

### ISSUE THREAD

**Issue by Rahulscan** [PyFPDF/fpdf2#785]
i have a problem in cell inside a table 
```python
row2 = table.row()
            row2.cell(
                f'''\n **B (Bi)**
                    \n GSTIN : {self.p}
                    \n {self.p}
                    \n {self.address}
                    \n {self.p} 
                    \n {self.pa} - {self.e}
                    \n Email : {self.l}
                  '''
``` 
in the above code my self.address is of multiple lines so when my output is being produced, the spacing btw the 'self.address'
and the remaining is uneven.
is there any way i can fix that ?
![Screenshot 2023-05-16 at 1 44 07 PM](https://github.com/PyFPDF/fpdf2/assets/129848996/607171d2-1a00-4ea8-8218-cb8c12d56b02)

**Comment by Lucas-C** [comment]
Hi @Rahulscan!

Could you please provide an autonomous minimal Python code reproducing your issue:?

This is described in details in our bug report template: https://github.com/PyFPDF/fpdf2/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Rahulscan** [comment]
```python
from fpdf import FPDF
import qrcode

pdf = FPDF('P', 'mm', 'A4')
pdf.add_page()
pdf.set_font('helvetica', 'B', 15)
pdf.cell(65)
pdf.cell(60, 10, 'INVOICE', align='C', ln=1)
pdf.set_font('helvetica', '', size=7)

with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False, markdown=True, line_height=4) as table:
    row = table.row()
    row.cell('  **Seller Details** \n  ABCD '
             '\n  COMPANY NAME -- TECHNOLOGIES PRIVATE LIMITED'
             '\n  FLAT NO.123,PLOT NUMBER-1234, SETOR NO.123,'
             '\n  ABCD, THIS IS A DUMMY DATA, FOR TESTING PURPOSE, CODE-1234567, LINE NAME IS ABCDEF'
             '\n  DUMMY, 111301\n  FOR UNDERSTANDING PURPOSE'
             '\n  STATE NAME IS ASDFG - 111301 \n  Email : support@company.com \n\n\n\n\n\n', )
    row.cell('  **Details of Invoice**''\n  Invoice Number : 12345667899'
             '\n  Date : 01-JANUARY-2000 ''\n  Supply Type: Business to Business '
             '\n  Place of Supply : STATE \n  Reverse Charge : N''\n  Total Amount : 1,1111.11 \n\n\n\n\n\n\n')

    row.cell(img='abc.png')

    row2 = table.row()

    row2.cell('  **Buyer Details (Bill To)**'
              '\n  GSTIN : 1234567890 '
              '\n  DESIGN DESIGN '
              '\n  A 1235, HOMER 4, WORKING AREA '
              '\n  CITY NAME \n  STATE - 1234567 '
              '\n  Email : DESIGNDESIGN.ABC@ABCD.COM \n\n\n\n\n')
    row2.cell('**MAIL ---- ADDRESS** \n(Same as Bill To address) \n\n\n\n\n\n', align='L')
    row2.cell('**MAIL ---- Address** \n(Same as Seller address) \n\n\n\n\n\n', align='L')
pdf.ln(10)

pdf.output('pdf.pdf')

``` 
hopefully this helps
in case i wasn't able to make my self clear last time, the issue im facing is that if data i'm adding btw the line break( \n ) can't be fitted inside the cell. the vertical line spacing is uneven

**Comment by Lucas-C** [comment]
>  in case i wasn't able to make my self clear last time, the issue im facing is that if data i'm adding btw the line break( \n ) can't be fitted inside the cell. the vertical line spacing is uneven

Sorry, your question still remains a bit unclear to me 😅
* Do you want fixed table row heights?
* Or are you refering to the vertical spacing between lines of text inside a single cell?
* Or maybe you want control on the left margin of text lines that wrap to the following line?

Some suggestions anyway:
* line heights inside table cells can be controlled with the `line_height` parameter of `FPDF.table()`
* if you want to disable interpretation of double dashes (`--`) as Markdown underline markers, you can: `FPDF.MARKDOWN_UNDERLINE_MARKER = '---'`
* defining fixed heights for table rows is currently not supported, but this certainly could be a new feature that we could support

I fiddled a little with your code snippet.
Here is a modified version where I use some `fpdf2` utilities to pre-process your text lines
in order to line-wrap & indent them:
```python
#!/usr/bin/env python3
from fpdf import FPDF
from fpdf.enums import WrapMode
from fpdf.line_break import Fragment, MultiLineBreak
import qrcode, warnings
warnings.simplefilter("default", DeprecationWarning)

IMG_PATH = 'test/image/png_images/c-m3-66ac49ef3f48ac9482049e1ab57a53e9.png'
FPDF.MARKDOWN_UNDERLINE_MARKER = '---'

def wrap_and_indent(pdf, *lines, max_len=58, wrap_indent="  "):
    content = ''
    for line in lines:
        wrapped = False
        multi_line_break = MultiLineBreak(
            [Fragment(line, pdf._get_current_graphics_state(), pdf.k)],
            justify=True,
            wrapmode=WrapMode.WORD,
        )
        txt_line = multi_line_break.get_line_of_given_width(max_len)
        while txt_line is not None:
            str_line = ''.join(''.join(frag.characters) for frag in txt_line.fragments)
            content += f"\n  {wrap_indent if wrapped else ''}{str_line}"
            txt_line = multi_line_break.get_line_of_given_width(max_len)
            wrapped = True
    return content
    

pdf = FPDF('P', 'mm', 'A4')
pdf.add_page()
pdf.set_font('helvetica', 'B', 15)
pdf.cell(65)
pdf.cell(60, 10, 'INVOICE', align='C', ln=1)
pdf.set_font('helvetica', '', size=7)

with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False, markdown=True, line_height=4) as table:
    row = table.row()
    pdf.x += 10
    row.cell('**Seller Details**' + wrap_and_indent(pdf, 
                'ABCD',
                'COMPANY NAME -- TECHNOLOGIES PRIVATE LIMITED',
                'FLAT NO.123,PLOT NUMBER-1234, SETOR NO.123,',
                'ABCD, THIS IS A DUMMY DATA, FOR TESTING PURPOSE, CODE-1234567, LINE NAME IS ABCDEF',
                'DUMMY, 111301',
                'FOR UNDERSTANDING PURPOSE',
                'STATE NAME IS ASDFG - 111301',
                'Email : support@company.com',
                '\n'))
    row.cell('**Details of Invoice**' + wrap_and_indent(pdf, 
                'Invoice Number : 12345667899',
                'Date : 01-JANUARY-2000 ',
                'Supply Type: Business to Business',
                'Place of Supply : STATE',
                'Reverse Charge : N',
                'Total Amount : 1,1111.11'))
    row.cell(img=IMG_PATH)

    row2 = table.row()
    row2.cell('**Buyer Details (Bill To)**' + wrap_and_indent(pdf, 
               'GSTIN : 1234567890',
               'DESIGN DESIGN',
               'A 1235, HOMER 4, WORKING AREA',
               'CITY NAME',
               'STATE - 1234567',
               'Email : DESIGNDESIGN.ABC@ABCD.COM',
                '\n'))
    row2.cell('**MAIL ---- ADDRESS** \n(Same as Bill To address)', align='L')
    row2.cell('**MAIL ---- Address** \n(Same as Seller address)', align='L')
pdf.ln(10)

pdf.output('issue_785.pdf')
```

**Comment by Rahulscan** [comment]
Yes, I was referring to the vertical spacing between lines of text within a single cell. In the code that I wrote, I had to use multiple curly braces ({}) inside each cell. However, if the content within one of the curly braces exceeds the width of the cell and moves to the next line, it results in uneven vertical spacing compared to the rest of the curly braces.
![](https://user-images.githubusercontent.com/129848996/238581215-607171d2-1a00-4ea8-8218-cb8c12d56b02.png)
Just like in this image, the 4th and 5th line has less vertical spacing compared to the rest of the line

**Comment by Lucas-C** [comment]
> Yes, I was referring to the vertical spacing between lines of text within a single cell. In the code that I wrote, I had to use multiple curly braces ({}) inside each cell. However, if the content within one of the curly braces exceeds the width of the cell and moves to the next line, it results in uneven vertical spacing compared to the rest of the curly braces.
> Just like in this image, the 4th and 5th line has less vertical spacing compared to the rest of the line

Have you tested the code that I provided?

I don't think this problem occurs anymore:
[issue_785.pdf](https://github.com/PyFPDF/fpdf2/files/11525724/issue_785.pdf)

**Comment by Rahulscan** [comment]
Yes, i tested your code. It didn't fix the problem
If i have to import multiple data from a database inside a single cell and one of the them is exceeding a single line it is still 
![Screenshot 2023-05-22 at 10 57 24 AM](https://github.com/PyFPDF/fpdf2/assets/129848996/d0a19c6d-7ceb-4365-95b5-2daecf9ab833)
This is the output im getting from your code

**Comment by Lucas-C** [comment]
Hi @Rahulscan

I was planning to get another look at this today, but you closed that issue.

Have you solved it? Or maybe you switched to another solution and don't need an answer anymore?

**Comment by Rahulscan** [comment]
Yes, when i added f-string individually to each instance variable. The code you provided worked but as it is going to the next line there remains a gap 
![Screenshot 2023-05-22 at 3 00 38 PM](https://github.com/PyFPDF/fpdf2/assets/129848996/ec3e5376-ff73-4930-8d6c-d655dcba4850)
Like the above image, in the 5th line 
also the top margin increased, is there a way to decrease it ?

**Comment by Rahulscan** [comment]
The gap issue was fixed, only remains the top margin issue to be fixed

**Comment by Lucas-C** [comment]
> The gap issue was fixed, only remains the top margin issue to be fixed

Alright 😊

If you expect more help regarding this,
please understand that without sharing the code your are working with,
I really cannot help you much... 😅
And also that it is best to first narrow down the problem to the smallest piece of code possible:
https://en.wikipedia.org/wiki/Minimal_reproducible_example

Using the code I shared with you yesterday, there is no issue with the top cell margin is minimal,
and I cannot reproduce the problem from your screenshot only.

As the maintainer of the `fpdf2` library, I'll be happy to help you
if you have a bug to report regarding `fpdf2`, or a precise question regarding this library.
Hence, could you be a bit more precise please?

**Comment by Rahulscan** [comment]
```python
font_family = 'helvetica'
font_size = 9

 with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False, markdown=True,
                       line_height=4.5, text_align="LEFT") as table:
            row = table.row()
            row.cell('  **Seller Details**' +
                     wrap_and_indent(
                         pdf,
                         f'GSTIN : 123456789',
                         f'1234567890',
                         f'dummy data 1234, dummy data 1234 dummy data - 1122334455',
                         f'city',
                         f'state, postal_code',
                         f'email_address'''
                     ), 'L')

            row.cell('  **Details of Invoice**' +
                     wrap_and_indent(
                         pdf,
                         f'Invoice Number : invoice_number',
                         f'Invoice Date : payment_time',
                         f'Supply Type: Business to Business',
                         f'Place of Supply : bill_state',
                         f'Reverse Charge : N',
                         f'Total Amount : amount'
                      ), 'L')

            row.cell(img=qr_code.png)

            row2 = table.row()
            row2.cell('  **Buyer Details (Bill To)**' +
                      wrap_and_indent(
                          pdf,
                          f'GSTIN : bill_tax_number',
                          f'bill_customer_name',
                          f'bill_address',
                          f'bill_city',
                          f'bill_state - bill_postal_code',
                          f'Email : bill_customer_email_address'
                      ), 'L')

            row2.cell('  **Ship to Address**' +
                      wrap_and_indent(
                          pdf,
                          '(Same as Bill To address)'
                          f'\n\n\n\n\n\n\n'
                      ), 'L')

            row2.cell('  **Dispatch to Address**' +
                      wrap_and_indent(
                          pdf,
                          '(Same as Bill To address)'
                          f'\n\n\n\n\n\n\n'
                      ), 'L')
``` 
This is the code(i hope it helps), 
Although i created another issue regarding the padding of cell inside a table so i think its clear i cant have custom padding/margins inside a cell which is in a table

**Comment by Lucas-C** [comment]
> This is the code(i hope it helps),

Thank you 😊
I plugged the snippet from your latest comment inside your previous script, and it does not reproduce the bug, sorry...
This is the output I get, using the image https://github.com/PyFPDF/fpdf2/blob/master/test/image/png_images/c-m3-66ac49ef3f48ac9482049e1ab57a53e9.png: 

[issue_785b.pdf](https://github.com/PyFPDF/fpdf2/files/11541440/issue_785b.pdf)

Some tips to provide a **minimal**, **autonomous** script:
1. Please ensure that your script is **complete**, and generates a PDF that demonstrates your problem
1. Your code depends on a `qr_code` variable, but you did not provide it, so I cannot use the same image when running your script. Please make sure your script includes everything required, without any external image or ressource

**Comment by Lucas-C** [comment]
Hi @Rahulscan

Is this still an issue for you?

Otherwise I will probably close this thread

**Comment by Rahulscan** [comment]
Hey @Lucas-C 
i think we can close the thread !!
Thanks
