### ISSUE TITLE
Q: Does fpdf2 support different font size in .multi_cell()? 

### ISSUE THREAD

**Issue by jonahmarc** [PyFPDF/fpdf2#786]
Hi. 
I was just wondering if there are ways on how to enable different font size of the `txt` when using `.multi_cell()`?

If there aren't any, _**I would like to request this feature**_ (if possible). I think it's very helpful when generating pdfs especially with sections/paragraphs that are hard to break apart. Also, very useful when implementing dynamic contents.

Thank you.

**Comment by gmischler** [comment]
Hi @jonahmarc ,

to mix different fonts within a paragraph, you currently need to use the `.write()` method.

The downside of that is that at the moment it only supports left aligned text. I'm working to change that (as soon as I get around to finishing it) as outlined in #339 .

**Comment by Lucas-C** [comment]
I fully agree with @gmischler answer.

For now, alternative approach can `write_html()`:
```python
pdf.write_html('Hello <font size="7">world</font>!')
```

**Comment by jonahmarc** [comment]
@gmischler @Lucas-C  Thank you. Hoping to more features.

**Comment by gmischler** [comment]
I've just checked in #897, which should be a general solution to this problem.
