### ISSUE TITLE
multi_cell and line does not respect left and right margins

### ISSUE THREAD

**Issue by aleksilahis** [PyFPDF/fpdf2#805]
At least `multi_cell` and `line` doesn't seem to respect left and right margins. Looks like `line` draws a little bit over from the margin and `multi_cell` has more margin than `text`. The same happens in both ends: in left and right margins.

The code below creates a document like this (cropped the relevant top part of it):

![image](https://github.com/PyFPDF/fpdf2/assets/36207259/ecf24d64-78e2-482c-88b6-6314c52cde61)

When drawing a line starting from the first edge of the header you can see the line and multi cell texts are not aligned with the header.

![image](https://github.com/PyFPDF/fpdf2/assets/36207259/70502178-819c-459e-96fd-3f338d6fed6e)

Is it working as intended? To me it looks like a bug and it's a bit annoying to reduce/add pixels here and there to get all things aligned vertically.

**Minimal code**
```python
pdf = FPDF()
pdf.add_page()
pdf.set_font("helvetica", "B", 16)

pdf.text(x=pdf.l_margin, y=pdf.get_y(), txt="Header")

pdf.multi_cell(
    w=20,
    h=pdf.font_size * 2,
    txt="Cell 1",
    align=Align.L,
    new_x=XPos.RIGHT,
    new_y=YPos.TOP,
)

pdf.multi_cell(
    w=20,
    h=pdf.font_size * 2,
    txt="Cell 2",
    align=Align.L,
    new_x=XPos.RIGHT,
    new_y=YPos.TOP,
)

pdf.ln(pdf.font_size * 2)

pdf.multi_cell(
    w=20,
    h=pdf.font_size * 2,
    txt="Cell 3",
    align=Align.L,
    new_x=XPos.RIGHT,
    new_y=YPos.TOP,
)

pdf.multi_cell(
    w=20,
    h=pdf.font_size * 2,
    txt="Cell 4",
    align=Align.L,
    new_x=XPos.RIGHT,
    new_y=YPos.NEXT,
)

pdf.set_draw_color(r=123, g=123, b=123)
pdf.line(x1=pdf.l_margin + 20, y1=pdf.get_y(), x2=pdf.r_margin, y2=pdf.get_y())
pdf.output()
```

**Environment**

* **Operating System**: Ubuntu
* **Python version**: 3.10.6
* **`fpdf2` version used**: 2.7.4

**Comment by aleksilahis** [comment]
Thanks for quick answer! I already tried adding borders, but we only need separator lines above and below the table which is not possible with `multi_cell`. Would be nice if the padding could be set explicitly to `multi_cell` or there was a parameter for x coordinate. Now it's a bit difficult to get everything vertically aligned since `text` seems to place the text starting from left margin, while `line` has less margin and `multi_cell` has its own inner margin.

**Comment by aleksilahis** [comment]
Thanks again for you answer! I think playing with `c_margin` is what I need - did not notice such before you pointed it out. Thanks for quick support and great library! 😎

**Comment by Lucas-C** [comment]
Glad that I could help you

Closing this now, but feel free to open another issue anytime you need it!
