### ISSUE TITLE
meta NOT subset; don't know how to subset; dropped

### ISSUE THREAD

**Issue by ShawnDriscoll** [PyFPDF/fpdf2#831]
**Error details**
Recently updated fpdf2 to 2.7.4, after updating Python from 3.10 to 3.11. I was using fpdf2 2.6.0 before.

Anyway, I now see "meta NOT subset; don't know how to subset; dropped" in my CMD when running my Python code. The PDF output looks the same as it did previously, though. Is this just a warning or depreciation of some sort? I know these things can happen a year later with software updates.

**Minimal code**
add_font() or set_font() is triggering the message.
```python
from fpdf import FPDF

pdf = FPDF(orientation='P', unit='in', format='Letter')
pdf.add_page()
pdf.add_font(family='Comic Sans MS', style='B', fname=r'C:\Windows\Fonts\comicbd.ttf')
pdf.set_font('Comic Sans MS', 'B', 20)
pdf.cell(txt=' ')
pdf.ln()
pdf.cell(txt='Some Game Name')
pdf.ln()
pdf.cell(txt='CHARACTER LOGBOOK')
pdf.ln()
pdf.cell(txt=' ')
pdf.ln()
pdf.cell(txt='Name: ' + 'Pirate Jones')

pdf.output(CURRENT_DIR + '/' + 'Pirate Jones' + '.pdf')
```

**Environment**
* **Operating System**: Windows 10
* **Python version**: 3.11.4
* **`fpdf2` version used**: 2.7.4

**Comment by Lucas-C** [comment]
Hi!

Thank you for the report @ShawnDriscoll

This seems to be a warning produced by `fonttools`: https://github.com/fonttools/fonttools/issues/2256

Have you tried setting up some basic logging configuration in order to find what produces those logs?
_cf._ https://pyfpdf.github.io/fpdf2/Logging.html

You can also find on this documentation page how to disable some verbose loggers.

Does that solves your issue?

**Comment by ShawnDriscoll** [comment]
When I use WARN, I just see the original message.

When I use DEBUG, I see all this:

01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'head' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'head' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'hmtx' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'hmtx' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'maxp' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'maxp' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'hhea' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'hhea' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'post' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'post' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'cmap' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'cmap' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'OS/2' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'OS/2' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'cmap' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'cmap' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'name' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'name' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'cmap' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'cmap' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'post' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'post' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'maxp' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'maxp' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'cmap' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'cmap' table
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to load 'maxp'
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to prune 'maxp'
01:52:09 fontTools.subset [INFO] maxp pruned
01:52:09 fontTools.subset [INFO] LTSH dropped
01:52:09 fontTools.subset [INFO] hdmx dropped
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to load 'cmap'
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to prune 'cmap'
01:52:09 fontTools.subset [INFO] cmap pruned
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to load 'post'
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to prune 'post'
01:52:09 fontTools.subset [INFO] post pruned
01:52:09 fontTools.subset [INFO] DSIG dropped
01:52:09 fontTools.subset [INFO] GDEF dropped
01:52:09 fontTools.subset [INFO] GPOS dropped
01:52:09 fontTools.subset [INFO] GSUB dropped
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'name' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'name' table
01:52:09 fontTools.subset.timer [DEBUG] Took 0.001s to load 'name'
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'fvar' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'STAT' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'CPAL' table from disk
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to prune 'name'
01:52:09 fontTools.subset [INFO] name pruned
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'glyf' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'glyf' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'loca' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'loca' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'head' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'head' table
01:52:09 fontTools.subset.timer [DEBUG] Took 0.015s to load 'glyf'
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to prune 'glyf'
01:52:09 fontTools.subset [INFO] glyf pruned
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to close glyph list over 'cmap'
01:52:09 fontTools.subset [INFO] Added gid0 to subset
01:52:09 fontTools.subset [INFO] Added first four glyphs to subset
01:52:09 fontTools.subset [INFO] Closing glyph list over 'glyf': 42 glyphs before
01:52:09 fontTools.subset [INFO] Glyph names: ['.notdef', 'A', 'B', 'C', 'E', 'G', 'H', 'J', 'K', 'L', 'N', 'O', 'P', 'R', 'S', 'T', 'a', 'b', 'braceleft', 'braceright', 'colon', 'e', 'eight', 'five', 'four', 'glyph00001', 'glyph00002', 'i', 'm', 'n', 'nine', 'o', 'one', 'r', 's', 'seven', 'six', 'space', 't', 'three', 'two', 'zero']
01:52:09 fontTools.subset [INFO] Glyph IDs:   [0, 1, 2, 3, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 36, 37, 38, 40, 42, 43, 45, 46, 47, 49, 50, 51, 53, 54, 55, 68, 69, 72, 76, 80, 81, 82, 85, 86, 87, 94, 96]
01:52:09 fontTools.subset [INFO] Closed glyph list over 'glyf': 42 glyphs after
01:52:09 fontTools.subset [INFO] Glyph names: ['.notdef', 'A', 'B', 'C', 'E', 'G', 'H', 'J', 'K', 'L', 'N', 'O', 'P', 'R', 'S', 'T', 'a', 'b', 'braceleft', 'braceright', 'colon', 'e', 'eight', 'five', 'four', 'glyph00001', 'glyph00002', 'i', 'm', 'n', 'nine', 'o', 'one', 'r', 's', 'seven', 'six', 'space', 't', 'three', 'two', 'zero']
01:52:09 fontTools.subset [INFO] Glyph IDs:   [0, 1, 2, 3, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 36, 37, 38, 40, 42, 43, 45, 46, 47, 49, 50, 51, 53, 54, 55, 68, 69, 72, 76, 80, 81, 82, 85, 86, 87, 94, 96]
01:52:09 fontTools.subset.timer [DEBUG] Took 0.001s to close glyph list over 'glyf'
01:52:09 fontTools.subset [INFO] Retaining 42 glyphs
01:52:09 fontTools.subset [INFO] head subsetting not needed
01:52:09 fontTools.subset [INFO] hhea subsetting not needed
01:52:09 fontTools.subset [INFO] maxp subsetting not needed
01:52:09 fontTools.subset [INFO] OS/2 subsetting not needed
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'hmtx' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'hmtx' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'hhea' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'hhea' table
01:52:09 fontTools.subset.timer [DEBUG] Took 0.001s to subset 'hmtx'
01:52:09 fontTools.subset [INFO] hmtx subsetted
01:52:09 fontTools.subset [INFO] VDMX subsetting not needed
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to subset 'cmap'
01:52:09 fontTools.subset [INFO] cmap subsetted
01:52:09 fontTools.subset [INFO] fpgm subsetting not needed
01:52:09 fontTools.subset [INFO] prep subsetting not needed
01:52:09 fontTools.subset [INFO] cvt  subsetting not needed
01:52:09 fontTools.subset [INFO] loca subsetting not needed
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to subset 'post'
01:52:09 fontTools.subset [INFO] post subsetted
01:52:09 fontTools.subset [INFO] gasp subsetting not needed
01:52:09 fontTools.subset [WARNING] meta NOT subset; don't know how to subset; dropped
01:52:09 fontTools.subset [INFO] name subsetting not needed
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to subset 'glyf'
01:52:09 fontTools.subset [INFO] glyf subsetted
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to subset GlyphOrder
01:52:09 fontTools.subset.timer [DEBUG] Took 0.000s to prune 'head'
01:52:09 fontTools.subset [INFO] head pruned
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'OS/2' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Decompiling 'OS/2' table
01:52:09 fontTools.subset [INFO] OS/2 Unicode ranges pruned: [0]
01:52:09 fontTools.subset.timer [DEBUG] Took 0.001s to prune 'glyf'
01:52:09 fontTools.subset [INFO] glyf pruned
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'glyf' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'glyf' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'maxp' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'maxp' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'loca' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'loca' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'head' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'head' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'hmtx' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'hmtx' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'hhea' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'hhea' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'OS/2' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'OS/2' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'VDMX' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'VDMX' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'cmap' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'cmap' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'fpgm' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'fpgm' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'prep' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'prep' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'cvt ' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'cvt ' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'name' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'name' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Compiling 'post' table
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'post' table to disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Reading 'gasp' table from disk
01:52:09 fontTools.ttLib.ttFont [DEBUG] Writing 'gasp' table to disk
01:52:09 fpdf.output [DEBUG] Final size summary of the biggest document sections:
01:52:09 fpdf.output [DEBUG] - pages: 305.0B
01:52:09 fpdf.output [DEBUG] - fonts: 13.1KiB

**Comment by Lucas-C** [comment]
That's expected for DEBUG logs 😊

You can set the level of the corresponding logger to `ERROR` in order to ignore WARN messages, if that's what you want.

**Comment by Lucas-C** [comment]
On `fpdf2`, maybe we should drop the `meta` table to avoid this warning being produced:
https://github.com/PyFPDF/fpdf2/blob/master/fpdf/output.py#L576

With which font do you see this warning @ShawnDriscoll?

**Comment by ShawnDriscoll** [comment]
The WARNING is in the middle of that mess. But I don't know what the DEBUG messages mean just above it. Sorry, I can't help much more in any way.

**Comment by ShawnDriscoll** [comment]
> ```python
> df.add_font(family='Comic Sans MS', style='B', fname=r'C:\Windows\Fonts\comicbd.ttf')
> pdf.set_font('Comic Sans MS', 'B', 20)
> ```

**Comment by Lucas-C** [comment]
> pdf.add_font(family='Comic Sans MS', style='B', fname=r'C:\Windows\Fonts\comicbd.ttf')
> pdf.set_font('Comic Sans MS', 'B', 20)

Interesting, I do not get the warnings you mentioned when using this minimal code:
```python
import logging
from fpdf import FPDF

logging.basicConfig(format="%(asctime)s %(name)s [%(levelname)s] %(message)s",
                    datefmt="%H:%M:%S", level=logging.WARN)

pdf = FPDF()
pdf.add_font(family="Comic Sans MS", style="B", fname=r"fonts/comicbd.ttf")
pdf.set_font("Comic Sans MS", "B", 20)
pdf.add_page()
pdf.cell(txt="Hello world!")
pdf.output("issue_831.pdf")
```
But I get those warnings:
```
11:18:26 fontTools.ttLib.tables._h_e_a_d [WARNING] 'created' timestamp out of range; ignoring top bytes
11:18:26 fontTools.ttLib.tables._h_e_a_d [WARNING] 'created' timestamp out of range; ignoring top bytes
```

Maybe it's linked to the `fonttools` you are using?
I used the latest release, `4.35.0`

**Comment by ShawnDriscoll** [comment]
In pip list, my ``fonttools`` is ``4.4.0``

**Comment by Lucas-C** [comment]
Maybe you could try to `pip install --upgrade foottools` and see if your WARN changes or disappear?

**Comment by ShawnDriscoll** [comment]
You mean downgrade. 4.40.0 came out recently. I'm not going to worry about the message I'm getting if it is just a warning.

**Comment by Lucas-C** [comment]
> You mean downgrade. 4.40.0 came out recently. I'm not going to worry about the message I'm getting if it is just a warning. Thanks for your help.

Oh you are right, my mistake, sorry 🤦‍♂️😅

I thought I had upgraded.
I just did upgrade to `fonttools==4.40.0` and I still see the 2 same warning logs, distinct from the one you mentioned...

Maybe the font file used is not exactly the same?
Have you tried running the code snippet I provided, with the same font file I linked to?

**Comment by ShawnDriscoll** [comment]
Ok. This is getting bizarre now. Why is my comicbd.ttf version 5.14 from 2018, and yours is 1.20 from 1995? It's Windows10 vs Windows95! The battle begins!

Anyway, my font is Editable. Your font is Installable.

**Comment by ShawnDriscoll** [comment]
[comic font.zip](https://github.com/PyFPDF/fpdf2/files/11941745/comic.font.zip)

**Comment by gmischler** [comment]
I think we had similar reports before.
Font files can contain lots of different types of data, often proprietary to specific tools.
When fonttools creates the subset for embedding the used glyphs in the PDF and it encounters such data that it isn't familiar with, it simply outputs this message and ignores the unknown data.
This is entirely harmless and working as designed.
We could try to get rid of that message, since the information it provides does not realy have any practical relevance.

**Comment by ShawnDriscoll** [comment]
That is what I thought was happening.

**Comment by Lucas-C** [comment]
> [comic font.zip](https://github.com/PyFPDF/fpdf2/files/11941745/comic.font.zip)

Thank you @ShawnDriscoll

I opened #839 to get rid of this warning
