### ISSUE TITLE
Modyfing `test/requirements.txt` cause pytest fails

### ISSUE THREAD

**Issue by qarmin** [PyFPDF/fpdf2#832]
**Error details**
Changing `test/requirements.txt` file causes to show error in pytest - I have no idea what cause this .

This is why some of tests from https://github.com/PyFPDF/fpdf2/pull/829 fails

https://github.com/PyFPDF/fpdf2/assets/41945903/a0a78a5e-7b91-4c02-9664-145119b8d9c6

EDIT: 
Looks that this line cause problems
```
EMBEDDED_FILE = HERE / "requirements.txt"
```
requirements file should not be used for tests.

**Environment**
Please provide the following information:
* **Operating System**: Ubuntu 22.04
* **Python version**: 3.7.17
* **`fpdf2` version used**: master branch

**Comment by Lucas-C** [comment]
Hi @qarmin

This is absolutely not a bug.
We simply have a unit test relying on the content of this file:
https://github.com/PyFPDF/fpdf2/blob/master/test/test_embed_file.py

A simple text search in the `test/` directory would have easily revealed that.

This simply means that if you modify the content of `test/requirements.txt` in a PR,
you must re-generate the reference PDF files for `test_embed_file.py`,

Our documentation dedicated to code contributors will provide you explanations on how to do so:
https://pyfpdf.github.io/fpdf2/Development.html#why-is-a-test-failing
