### ISSUE TITLE
Font becomes black inside and after a font tag in write_html

### ISSUE THREAD

**Issue by stenci** [PyFPDF/fpdf2#846]
The output from the following code should all be red, instead it becomes black starting from the `font` tag:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_text_color(200, 50, 50)
pdf.set_font(family='Helvetica', size=13)
pdf.write_html('one <font size=8>two</font> three')
pdf.output('html.pdf')
```

This is the output:
![image](https://github.com/PyFPDF/fpdf2/assets/5955495/f54f533c-7007-4401-a191-aff8d5e31f18)

Notice that family and size are correctly restored, only the color is reset to black.

**Environment**
* **Operating System**: Windows
* **Python version**: 3.7
* **`fpdf2` version used**: 2.7.4

**Comment by Lucas-C** [comment]
Thank you for the report @stenci

This is indeed a bug

I opened #848 to fix it

**Comment by Lucas-C** [comment]
@allcontrubutors please add @stenci for bug

**Comment by Lucas-C** [comment]
@allcontributors please add @stenci for bug
