### ISSUE TITLE
[Feature Request] Import an existing PDF

### ISSUE THREAD

**Issue by Aurnytoraink** [PyFPDF/fpdf2#9]
This will be usefull to fill already existed PDF

**Comment by Lucas-C** [comment]
This sure would be handy, but would require a massive code change, as this lib currently does not implement PDF parsing.

For this use case, you may try `pikepdf` or `pdfrw` and combine libs. For example, you could craft new pages with `pyfpdf2` and add them to existing PDFs using `pdfrw`.

**Comment by Lucas-C** [comment]
Documented as part of https://github.com/PyFPDF/fpdf2/pull/57

Closing this
