### ISSUE TITLE
Avoid page break

### ISSUE THREAD

**Issue by limo49** [PyFPDF/fpdf2#95]
Is it possible to specify that a paragraph or table should not be divided on two pages?

**Comment by Lucas-C** [comment]
Hi,

I'm in the process of documenting this in https://github.com/PyFPDF/fpdf2/pull/96

It's redacted yet for tables,
but for text rendered with the `FPDF.cell` method,
there is an example on how to control this here: https://github.com/PyFPDF/fpdf2/blob/more-docs/tutorial/tuto4.py#L39

**Comment by Lucas-C** [comment]
Documentation added in https://github.com/PyFPDF/fpdf2/pull/96

Closing this
