### ISSUE TITLE
Possible bug in `template.py` accessing different levels of `self.texts`?

### ISSUE THREAD

**Issue by eumiro** [PyFPDF/fpdf2#98]
These three lines:

https://github.com/PyFPDF/fpdf2/blob/6511eb02bd38acfd871e299cb781052f4fd0c73f/fpdf/template.py#L116-L118

are in the code unchanged since ten years. The check and retrieval access different levels of the `self.texts` dict.

**Comment by Lucas-C** [comment]
This should be fixed by https://github.com/PyFPDF/fpdf2/pull/100

**Comment by Lucas-C** [comment]
Closing this now that the fix has been released
